package com.abyssia;

import com.abyssia.fauna.external.ExternalFaunaConfig;
import com.abyssia.network.AbyssiaNetwork;
import com.abyssia.registry.GeneratedFauna;
import com.abyssia.registry.ModBlocks;
import com.abyssia.registry.ModDataComponents;
import com.abyssia.registry.ModEntities;
import com.abyssia.registry.ModFurniture;
import com.abyssia.registry.ModHabitat;
import com.abyssia.registry.ModIndustry;
import com.abyssia.registry.ModItems;
import com.abyssia.registry.ModParticles;
import com.abyssia.registry.ModSounds;
import com.abyssia.worldgen.ModWorldgen;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.fml.common.Mod;
import net.neoforged.fml.config.ModConfig;
import net.neoforged.fml.ModContainer;

// The value here should match an entry in the META-INF/neoforge.mods.toml file
@Mod(Abyssia.MODID)
public class Abyssia
{
    // Define mod id in a common place for everything to reference
    public static final String MODID = "abyssia";

    public Abyssia(IEventBus modEventBus, ModContainer context)
    {
        // data-driven fauna (generated by tools/gen_fauna.py): load first so its registrations join the DeferredRegisters
        GeneratedFauna.init();
        modEventBus.addListener(AbyssiaNetwork::register);
        ModDataComponents.register(modEventBus);
        com.abyssia.guide.GuideBookRegistry.register(modEventBus);
        modEventBus.addListener(com.abyssia.item.electric.ElectricTools::registerCapabilities);
        ModBlocks.register(modEventBus);
        // industrial blocks, block entities and menu (I01); their block items join ModItems
        ModIndustry.register(modEventBus);
        ModHabitat.register(modEventBus);
        ModFurniture.register(modEventBus);
        // BT01 constructor build menu entries (sub-specs add theirs in BuildContent)
        com.abyssia.habitat.build.BuildContent.register(modEventBus);
        ModItems.register(modEventBus);
        ModEntities.register(modEventBus);
        ModSounds.register(modEventBus);
        ModParticles.register(modEventBus);
        ModWorldgen.register(modEventBus);
        // EN01 effects and potions (enchantments are data-driven: data/abyssia/enchantment)
        com.abyssia.registry.ModMobEffects.register(modEventBus);
        com.abyssia.registry.ModPotions.register(modEventBus);

        // Register our mod's ModConfigSpec so that Forge can create and load the config file for us
        context.registerConfig(ModConfig.Type.COMMON, Config.SPEC);
        modEventBus.addListener(Config::onLoading);
        modEventBus.addListener(Config::onReloading);
        // Client-only presentation options; a dedicated server never loads them.
        context.registerConfig(ModConfig.Type.CLIENT, ClientConfig.SPEC);
        // Other mods' sea animals in the deep ocean: a file of its own so abyssia-common.toml keeps its shape.
        context.registerConfig(ModConfig.Type.COMMON, ExternalFaunaConfig.SPEC, ExternalFaunaConfig.FILE_NAME);
    }
}
