package com.abyssia;

import com.abyssia.fauna.external.ExternalFaunaConfig;
import com.abyssia.network.AbyssiaNetwork;
import com.abyssia.registry.GeneratedFauna;
import com.abyssia.registry.ModBlocks;
import com.abyssia.registry.ModEntities;
import com.abyssia.registry.ModItems;
import com.abyssia.registry.ModParticles;
import com.abyssia.registry.ModSounds;
import com.abyssia.worldgen.ModWorldgen;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.config.ModConfig;
import net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext;

// The value here should match an entry in the META-INF/mods.toml file
@Mod(Abyssia.MODID)
public class Abyssia
{
    // Define mod id in a common place for everything to reference
    public static final String MODID = "abyssia";

    public Abyssia(FMLJavaModLoadingContext context)
    {
        IEventBus modEventBus = context.getModEventBus();

        // data-driven fauna (generated by tools/gen_fauna.py): load first so its registrations join the DeferredRegisters
        GeneratedFauna.init();
        AbyssiaNetwork.register();
        ModBlocks.register(modEventBus);
        ModItems.register(modEventBus);
        ModEntities.register(modEventBus);
        ModSounds.register(modEventBus);
        ModParticles.register(modEventBus);
        ModWorldgen.register(modEventBus);

        // Register our mod's ForgeConfigSpec so that Forge can create and load the config file for us
        context.registerConfig(ModConfig.Type.COMMON, Config.SPEC);
        // Client-only presentation options; a dedicated server never loads them.
        context.registerConfig(ModConfig.Type.CLIENT, ClientConfig.SPEC);
        // Other mods' sea animals in the deep ocean: a file of its own so abyssia-common.toml keeps its shape.
        context.registerConfig(ModConfig.Type.COMMON, ExternalFaunaConfig.SPEC, ExternalFaunaConfig.FILE_NAME);
    }
}
