package com.abyssia.worldgen.deposit;

import net.minecraft.core.BlockPos;
import net.minecraft.core.HolderLookup;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.phys.AABB;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.UUID;
import java.util.concurrent.ConcurrentLinkedQueue;
import java.util.stream.Collectors;

/**
 * Manager for ore deposit registration and querying.
 * Provides a clean API for the vein feature and future scanner/mining systems.
 */
public final class OreDepositManager
{
    private OreDepositManager() {}

    /** A deposit queued from a worldgen worker thread, registered later on the main thread. */
    private record Pending(ServerLevel level, ResourceLocation mineralId, BlockPos center, AABB bounds,
                           com.abyssia.worldgen.OreVeinFeature.Size size, com.abyssia.worldgen.OreVeinFeature.Shape shape, int totalOre) {}

    private static final ConcurrentLinkedQueue<Pending> PENDING = new ConcurrentLinkedQueue<>();

    /**
     * Thread-safe: queues a deposit for registration. Safe to call from chunk-generation worker threads (the SavedData is
     * not thread-safe, so it is only touched by {@link #flush} on the server thread).
     */
    public static void enqueue(
            ServerLevel level,
            ResourceLocation mineralId,
            BlockPos center,
            AABB bounds,
            com.abyssia.worldgen.OreVeinFeature.Size size,
            com.abyssia.worldgen.OreVeinFeature.Shape shape,
            int totalOre)
    {
        PENDING.add(new Pending(level, mineralId, center.immutable(), bounds, size, shape, totalOre));
    }

    /**
     * Main thread only: registers up to {@code max} queued deposits, skipping one whose centre already lies inside an
     * existing deposit of the same mineral.
     */
    public static void flush(int max)
    {
        Pending next;
        for (int n = 0; n < max && (next = PENDING.poll()) != null; n++)
        {
            final Pending p = next;
            if (p.level().isClientSide) continue;
            boolean known = OreDepositData.get(p.level()).getAll().values().stream().anyMatch(d ->
                    d.mineralId().equals(p.mineralId()) && d.bounds().contains(p.center().getX() + 0.5, p.center().getY() + 0.5, p.center().getZ() + 0.5));
            if (!known) register(p.level(), p.mineralId(), p.center(), p.bounds(), p.size(), p.shape(), p.totalOre());
        }
    }

    /**
     * Registers a new ore deposit generated by a vein feature.
     *
     * @param level        the server level
     * @param mineralId    the resource location of the ore block (e.g., "abyssia:deep_copper_ore")
     * @param center       the center position of the vein
     * @param bounds       the bounding box of the vein
     * @param size         the vein size category
     * @param shape        the vein shape
     * @param totalOre     the actual number of ore blocks placed
     * @return the created deposit, or empty if registration failed
     */
    public static Optional<OreDeposit> register(
            ServerLevel level,
            ResourceLocation mineralId,
            BlockPos center,
            AABB bounds,
            com.abyssia.worldgen.OreVeinFeature.Size size,
            com.abyssia.worldgen.OreVeinFeature.Shape shape,
            int totalOre)
    {
        if (level.isClientSide) return Optional.empty();

        OreDepositData data = OreDepositData.get(level);
        UUID depositId = UUID.randomUUID();

        OreDeposit deposit = new OreDeposit(
                depositId,
                mineralId,
                center,
                bounds,
                size,
                shape,
                totalOre,
                0
        );

        data.register(deposit);
        return Optional.of(deposit);
    }

    /**
     * Gets a deposit by its UUID.
     */
    public static Optional<OreDeposit> get(ServerLevel level, UUID id)
    {
        return OreDepositData.get(level).get(id);
    }

    /**
     * Gets all deposits in the world.
     */
    public static Map<UUID, OreDeposit> getAll(ServerLevel level)
    {
        return OreDepositData.get(level).getAll();
    }

    /**
     * Removes a deposit (e.g., when fully depleted or for admin cleanup).
     */
    public static boolean remove(ServerLevel level, UUID id)
    {
        return OreDepositData.get(level).remove(id);
    }

    /**
     * Increments the mined amount for a deposit.
     * Called when ore blocks from this deposit are broken.
     */
    public static void incrementMined(ServerLevel level, UUID id, int amount)
    {
        OreDepositData.get(level).incrementMined(id, amount);
    }

    /**
     * Finds deposits whose bounds intersect the given AABB.
     * Useful for scanner systems to find nearby deposits.
     */
    public static List<OreDeposit> findIntersecting(ServerLevel level, AABB searchArea)
    {
        return OreDepositData.get(level).getAll().values().stream()
                .filter(deposit -> deposit.bounds().intersects(searchArea))
                .collect(Collectors.toList());
    }

    /**
     * Finds deposits within a horizontal radius of a position.
     * Searches a vertical column from bedrock to ceiling.
     */
    public static List<OreDeposit> findNearby(ServerLevel level, BlockPos center, int horizontalRadius)
    {
        AABB searchArea = new AABB(
                center.getX() - horizontalRadius,
                level.getMinBuildHeight(),
                center.getZ() - horizontalRadius,
                center.getX() + horizontalRadius + 1,
                level.getMaxBuildHeight(),
                center.getZ() + horizontalRadius + 1
        );
        return findIntersecting(level, searchArea);
    }

    /**
     * Finds deposits containing a specific mineral type.
     */
    public static List<OreDeposit> findByMineral(ServerLevel level, ResourceLocation mineralId)
    {
        return OreDepositData.get(level).getAll().values().stream()
                .filter(deposit -> deposit.mineralId().equals(mineralId))
                .collect(Collectors.toList());
    }

    /**
     * Finds deposits containing a specific mineral block.
     */
    public static List<OreDeposit> findByMineral(ServerLevel level, Block mineralBlock)
    {
        ResourceLocation mineralId = BuiltInRegistries.BLOCK.getKey(mineralBlock);
        return findByMineral(level, mineralId);
    }

    /**
     * Gets the total number of registered deposits.
     */
    public static int count(ServerLevel level)
    {
        return OreDepositData.get(level).size();
    }

    /**
     * Checks if there are any deposits registered.
     */
    public static boolean hasDeposits(ServerLevel level)
    {
        return !OreDepositData.get(level).isEmpty();
    }
}