package com.abyssia.client.entity.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Generated by tools/bbmodel-generator (black_scabbardfish.bbmodel, template eel, seed 1).
 * Texture 64x32 UV (64x32 px): textures/entity/black_scabbardfish.png.
 * Regenerate with: node tools/bbmodel-generator/cli.js black_scabbardfish
 */
public final class BlackScabbardfishGeometry
{
	public static final String BLACK_SCABBARDFISH = "black_scabbardfish";
	public static final String BODY = "body";
	public static final String BODY_2 = "body_2";
	public static final String BODY_3 = "body_3";
	public static final String BODY_4 = "body_4";
	public static final String BODY_5 = "body_5";
	public static final String BODY_6 = "body_6";
	public static final String BODY_7 = "body_7";
	public static final String BODY_8 = "body_8";
	public static final String HEAD = "head";
	public static final String MOUTH = "mouth";
	public static final String LOWER_TEETH = "lower_teeth";
	public static final String UPPER_TEETH = "upper_teeth";
	public static final String RIGHT_EYE = "right_eye";
	public static final String LEFT_EYE = "left_eye";
	public static final String RIGHT_FIN = "right_fin";
	public static final String LEFT_FIN = "left_fin";
	public static final String DORSAL_FIN = "dorsal_fin";
	public static final String DORSAL_FIN_2 = "dorsal_fin_2";
	public static final String DORSAL_FIN_3 = "dorsal_fin_3";
	public static final String DORSAL_FIN_4 = "dorsal_fin_4";
	public static final String DORSAL_FIN_5 = "dorsal_fin_5";
	public static final String DORSAL_FIN_6 = "dorsal_fin_6";
	public static final String DORSAL_FIN_7 = "dorsal_fin_7";
	public static final String DORSAL_FIN_8 = "dorsal_fin_8";
	public static final String ANAL_FIN = "anal_fin";
	public static final String ANAL_FIN_2 = "anal_fin_2";
	public static final String ANAL_FIN_3 = "anal_fin_3";
	public static final String ANAL_FIN_4 = "anal_fin_4";
	public static final String TAIL_FIN = "tail_fin";

	private BlackScabbardfishGeometry()
	{
	}

	public static LayerDefinition create()
	{
		MeshDefinition mesh = new MeshDefinition();
		PartDefinition root = mesh.getRoot();
		PartDefinition blackScabbardfish = root.addOrReplaceChild(BLACK_SCABBARDFISH, CubeListBuilder.create(),
			PartPose.offset(0.0F, 24.0F, 0.0F));
		PartDefinition body = blackScabbardfish.addOrReplaceChild(BODY, CubeListBuilder.create()
			.texOffs(16, 10).addBox(-1.0F, -2.0F, 0.0F, 2.0F, 4.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -2.2766F, -17.0F));
		PartDefinition body2 = body.addOrReplaceChild(BODY_2, CubeListBuilder.create()
			.texOffs(0, 10).addBox(-1.0F, -2.0F, -1.0F, 2.0F, 4.0F, 6.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 5.0F));
		PartDefinition body3 = body2.addOrReplaceChild(BODY_3, CubeListBuilder.create()
			.texOffs(0, 20).addBox(-1.0F, -2.0F, -1.0F, 2.0F, 3.0F, 6.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 5.0F));
		PartDefinition body4 = body3.addOrReplaceChild(BODY_4, CubeListBuilder.create()
			.texOffs(18, 0).addBox(-0.5F, -2.0F, -1.0F, 1.0F, 3.0F, 6.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 5.0F));
		PartDefinition body5 = body4.addOrReplaceChild(BODY_5, CubeListBuilder.create()
			.texOffs(16, 19).addBox(-0.5F, -1.0F, -1.0F, 1.0F, 2.0F, 6.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 5.0F));
		PartDefinition body6 = body5.addOrReplaceChild(BODY_6, CubeListBuilder.create()
			.texOffs(30, 9).addBox(-0.5F, -1.0F, -1.0F, 1.0F, 2.0F, 6.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 5.0F));
		PartDefinition body7 = body6.addOrReplaceChild(BODY_7, CubeListBuilder.create()
			.texOffs(32, 0).addBox(-0.5F, -1.0F, -1.0F, 1.0F, 2.0F, 6.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 5.0F));
		PartDefinition body8 = body7.addOrReplaceChild(BODY_8, CubeListBuilder.create()
			.texOffs(46, 0).addBox(-0.5F, -1.0F, -1.0F, 1.0F, 1.0F, 6.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 5.0F));
		PartDefinition dorsalFin8 = body8.addOrReplaceChild(DORSAL_FIN_8, CubeListBuilder.create()
			.texOffs(40, 14).addBox(0.0F, -1.0F, 0.0F, 0.0F, 2.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -1.0F, 0.0F));
		PartDefinition analFin4 = body8.addOrReplaceChild(ANAL_FIN_4, CubeListBuilder.create()
			.texOffs(30, 12).addBox(0.0F, -1.0F, 0.0F, 0.0F, 2.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 0.0F));
		PartDefinition tailFin = body8.addOrReplaceChild(TAIL_FIN, CubeListBuilder.create()
			.texOffs(30, 18).addBox(0.0F, -2.0F, -1.0F, 0.0F, 4.0F, 4.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 5.0F));
		PartDefinition dorsalFin7 = body7.addOrReplaceChild(DORSAL_FIN_7, CubeListBuilder.create()
			.texOffs(44, 11).addBox(0.0F, -2.0F, 0.0F, 0.0F, 3.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -1.0F, 0.0F));
		PartDefinition analFin3 = body7.addOrReplaceChild(ANAL_FIN_3, CubeListBuilder.create()
			.texOffs(20, 25).addBox(0.0F, -1.0F, 0.0F, 0.0F, 2.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 1.0F, 0.0F));
		PartDefinition dorsalFin6 = body6.addOrReplaceChild(DORSAL_FIN_6, CubeListBuilder.create()
			.texOffs(54, 8).addBox(0.0F, -2.0F, 0.0F, 0.0F, 3.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -1.0F, 0.0F));
		PartDefinition analFin2 = body6.addOrReplaceChild(ANAL_FIN_2, CubeListBuilder.create()
			.texOffs(54, 13).addBox(0.0F, -1.0F, 0.0F, 0.0F, 2.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 1.0F, 0.0F));
		PartDefinition dorsalFin5 = body5.addOrReplaceChild(DORSAL_FIN_5, CubeListBuilder.create()
			.texOffs(44, 8).addBox(0.0F, -2.0F, 0.0F, 0.0F, 3.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -1.0F, 0.0F));
		PartDefinition analFin = body5.addOrReplaceChild(ANAL_FIN, CubeListBuilder.create()
			.texOffs(54, 11).addBox(0.0F, -1.0F, 0.0F, 0.0F, 2.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 1.0F, 0.0F));
		PartDefinition dorsalFin4 = body4.addOrReplaceChild(DORSAL_FIN_4, CubeListBuilder.create()
			.texOffs(20, 22).addBox(0.0F, -2.0F, 0.0F, 0.0F, 3.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -2.0F, 0.0F));
		PartDefinition dorsalFin3 = body3.addOrReplaceChild(DORSAL_FIN_3, CubeListBuilder.create()
			.texOffs(10, 24).addBox(0.0F, -2.0F, 0.0F, 0.0F, 3.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -2.0F, 0.0F));
		PartDefinition dorsalFin2 = body2.addOrReplaceChild(DORSAL_FIN_2, CubeListBuilder.create()
			.texOffs(0, 24).addBox(0.0F, -2.0F, 0.0F, 0.0F, 3.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -2.0F, 0.0F));
		PartDefinition head = body.addOrReplaceChild(HEAD, CubeListBuilder.create()
			.texOffs(0, 0).addBox(-1.0F, -2.0F, -6.0F, 2.0F, 3.0F, 7.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 0.0F));
		PartDefinition mouth = head.addOrReplaceChild(MOUTH, CubeListBuilder.create()
			.texOffs(46, 7).addBox(-1.0F, 0.0F, -4.0F, 2.0F, 1.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 1.0F, -1.0F, 0.0698F, 0.0F, 0.0F));
		PartDefinition lowerTeeth = mouth.addOrReplaceChild(LOWER_TEETH, CubeListBuilder.create()
			.texOffs(36, 19).addBox(-1.0F, -1.0F, 0.5F, 1.0F, 1.0F, 0.0F, new CubeDeformation(0.0F))
			.texOffs(38, 19).addBox(0.0F, -1.0F, 0.5F, 1.0F, 1.0F, 0.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, -4.0F));
		PartDefinition upperTeeth = head.addOrReplaceChild(UPPER_TEETH, CubeListBuilder.create()
			.texOffs(50, 19).addBox(-0.5F, 0.0F, 0.5F, 1.0F, 1.0F, 0.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 1.0F, -6.0F));
		PartDefinition rightEye = head.addOrReplaceChild(RIGHT_EYE, CubeListBuilder.create()
			.texOffs(40, 21).addBox(-1.0F, -1.0F, -1.0F, 2.0F, 2.0F, 2.0F, new CubeDeformation(0.0F)),
			PartPose.offset(-0.8F, -1.0F, -4.0F));
		PartDefinition leftEye = head.addOrReplaceChild(LEFT_EYE, CubeListBuilder.create()
			.texOffs(50, 20).addBox(-1.0F, -1.0F, -1.0F, 2.0F, 2.0F, 2.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.8F, -1.0F, -4.0F));
		PartDefinition rightFin = body.addOrReplaceChild(RIGHT_FIN, CubeListBuilder.create()
			.texOffs(18, 6).addBox(0.0F, -0.5F, -1.0F, 0.0F, 1.0F, 3.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(-1.0F, -0.5F, 1.0F, 0.0F, -0.5236F, -0.2618F));
		PartDefinition leftFin = body.addOrReplaceChild(LEFT_FIN, CubeListBuilder.create()
			.texOffs(30, 16).addBox(0.0F, -0.5F, -1.0F, 0.0F, 1.0F, 3.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(1.0F, -0.5F, 1.0F, 0.0F, 0.5236F, 0.2618F));
		PartDefinition dorsalFin = body.addOrReplaceChild(DORSAL_FIN, CubeListBuilder.create()
			.texOffs(30, 15).addBox(0.0F, -1.0F, 0.0F, 0.0F, 2.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -2.0F, 0.0F));
		return LayerDefinition.create(mesh, 64, 32);
	}
}
