package com.abyssia.environment;

import net.minecraft.world.phys.Vec3;

import java.util.List;

/**
 * One CU01 current stream: a band of strong current around a smooth centre line. The centre line is a uniform
 * Catmull-Rom spline through 4-6 control points (the end points repeated), flowing from the first point to
 * the last; the flow direction at any point is the line's tangent there. Generated by {@link CurrentStreams}.
 *
 * @param id            deterministic id (the generating cell's seed)
 * @param controlPoints 4-6 points of the centre line, upstream first
 * @param length        nominal length in blocks (straight-line distance from the first to the last point before bending)
 * @param radius        half the band's diameter (4-10 by default)
 * @param strength      0.65-1.2 by default (WEAK / NORMAL / STRONG)
 */
public record CurrentStream(long id, List<Vec3> controlPoints, double length, double radius, double strength)
{
    public enum Tier
    {
        WEAK, NORMAL, STRONG
    }

    private static final int SAMPLES_PER_SEGMENT = 12;
    private static final int REFINE_STEPS = 12;

    public CurrentStream
    {
        controlPoints = List.copyOf(controlPoints);
    }

    /** WEAK below 0.80, STRONG from 1.00, NORMAL between. */
    public Tier tier()
    {
        return strength < 0.80 ? Tier.WEAK : strength < 1.00 ? Tier.NORMAL : Tier.STRONG;
    }

    public int segments()
    {
        return controlPoints.size() - 1;
    }

    public Vec3 start()
    {
        return controlPoints.get(0);
    }

    public Vec3 end()
    {
        return controlPoints.get(controlPoints.size() - 1);
    }

    /** The centre line's middle point (t = 0.5). */
    public Vec3 center()
    {
        return point(0.5);
    }

    /** Point on the centre line, t in 0..1 from the first control point to the last. */
    public Vec3 point(double t)
    {
        double[] out = new double[3];
        eval(t, out, null);
        return new Vec3(out[0], out[1], out[2]);
    }

    /** Unit flow direction at t (the centre line's tangent). */
    public Vec3 tangent(double t)
    {
        double[] d = new double[3];
        eval(t, null, d);
        double len = Math.sqrt(d[0] * d[0] + d[1] * d[1] + d[2] * d[2]);
        return len < 1.0E-9 ? end().subtract(start()).normalize() : new Vec3(d[0] / len, d[1] / len, d[2] / len);
    }

    /** True when the point may be within {@code margin} of the band (bounding box of the control points, padded). */
    public boolean roughlyNear(double x, double y, double z, double margin)
    {
        double pad = margin + radius + length * 0.15 + 4.0;
        double minX = Double.MAX_VALUE, minY = Double.MAX_VALUE, minZ = Double.MAX_VALUE;
        double maxX = -Double.MAX_VALUE, maxY = -Double.MAX_VALUE, maxZ = -Double.MAX_VALUE;
        for (Vec3 p : controlPoints)
        {
            minX = Math.min(minX, p.x);
            minY = Math.min(minY, p.y);
            minZ = Math.min(minZ, p.z);
            maxX = Math.max(maxX, p.x);
            maxY = Math.max(maxY, p.y);
            maxZ = Math.max(maxZ, p.z);
        }
        return x >= minX - pad && x <= maxX + pad && y >= minY - pad && y <= maxY + pad && z >= minZ - pad && z <= maxZ + pad;
    }

    /**
     * Nearest point of the centre line to (x, y, z): returns {t, distance}. Coarse samples along every segment, then a
     * ternary refinement around the best one.
     */
    public double[] nearest(double x, double y, double z)
    {
        int samples = segments() * SAMPLES_PER_SEGMENT;
        double[] p = new double[3];
        double bestT = 0.0, bestD = Double.MAX_VALUE;
        for (int i = 0; i <= samples; i++)
        {
            double t = i / (double) samples;
            eval(t, p, null);
            double d = sq(p[0] - x) + sq(p[1] - y) + sq(p[2] - z);
            if (d < bestD)
            {
                bestD = d;
                bestT = t;
            }
        }
        double lo = Math.max(0.0, bestT - 1.0 / samples), hi = Math.min(1.0, bestT + 1.0 / samples);
        for (int k = 0; k < REFINE_STEPS; k++)
        {
            double m1 = lo + (hi - lo) / 3.0, m2 = hi - (hi - lo) / 3.0;
            eval(m1, p, null);
            double d1 = sq(p[0] - x) + sq(p[1] - y) + sq(p[2] - z);
            eval(m2, p, null);
            double d2 = sq(p[0] - x) + sq(p[1] - y) + sq(p[2] - z);
            if (d1 < d2) hi = m2;
            else lo = m1;
        }
        double t = (lo + hi) * 0.5;
        eval(t, p, null);
        double d = sq(p[0] - x) + sq(p[1] - y) + sq(p[2] - z);
        if (d > bestD)
        {
            t = bestT;
            d = bestD;
        }
        return new double[] {t, Math.sqrt(d)};
    }

    /** Arc length of the centre line (approximate, from the same samples as {@link #nearest}). */
    public double arcLength()
    {
        int samples = segments() * SAMPLES_PER_SEGMENT;
        double[] p = new double[3], q = new double[3];
        eval(0.0, q, null);
        double total = 0.0;
        for (int i = 1; i <= samples; i++)
        {
            eval(i / (double) samples, p, null);
            total += Math.sqrt(sq(p[0] - q[0]) + sq(p[1] - q[1]) + sq(p[2] - q[2]));
            double[] swap = q;
            q = p;
            p = swap;
        }
        return total;
    }

    /** Uniform Catmull-Rom position (pos) and derivative (deriv) at global t; either may be null. */
    private void eval(double t, double[] pos, double[] deriv)
    {
        int n = controlPoints.size();
        double g = Math.max(0.0, Math.min(1.0, t)) * (n - 1);
        int seg = Math.min(n - 2, (int) Math.floor(g));
        double s = g - seg;
        Vec3 p1 = controlPoints.get(seg), p2 = controlPoints.get(seg + 1);
        Vec3 p0 = seg > 0 ? controlPoints.get(seg - 1) : null;
        Vec3 p3 = seg + 2 < n ? controlPoints.get(seg + 2) : null;
        double[] a = new double[3], b = new double[3], c = new double[3], d = new double[3];
        coords(p1, b);
        coords(p2, c);
        // End points repeated (P-1 = P0, Pn = Pn-1).
        coords(p0 != null ? p0 : p1, a);
        coords(p3 != null ? p3 : p2, d);
        for (int i = 0; i < 3; i++)
        {
            double c1 = -a[i] + c[i];
            double c2 = 2 * a[i] - 5 * b[i] + 4 * c[i] - d[i];
            double c3 = -a[i] + 3 * b[i] - 3 * c[i] + d[i];
            if (pos != null) pos[i] = 0.5 * (2 * b[i] + c1 * s + c2 * s * s + c3 * s * s * s);
            if (deriv != null) deriv[i] = 0.5 * (c1 + 2 * c2 * s + 3 * c3 * s * s);
        }
    }

    private static void coords(Vec3 v, double[] out)
    {
        out[0] = v.x;
        out[1] = v.y;
        out[2] = v.z;
    }

    private static double sq(double v)
    {
        return v * v;
    }
}
