package com.abyssia.client.entity.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Generated by tools/bbmodel-generator (snipe_eel.bbmodel, template eel, seed 1).
 * Texture 64x64 UV (64x64 px): textures/entity/snipe_eel.png.
 * Regenerate with: node tools/bbmodel-generator/cli.js snipe_eel
 */
public final class SnipeEelGeometry
{
	public static final String SNIPE_EEL = "snipe_eel";
	public static final String BODY = "body";
	public static final String BODY_2 = "body_2";
	public static final String BODY_3 = "body_3";
	public static final String BODY_4 = "body_4";
	public static final String BODY_5 = "body_5";
	public static final String BODY_6 = "body_6";
	public static final String BODY_7 = "body_7";
	public static final String BODY_8 = "body_8";
	public static final String BODY_9 = "body_9";
	public static final String BODY_10 = "body_10";
	public static final String BODY_11 = "body_11";
	public static final String BODY_12 = "body_12";
	public static final String HEAD = "head";
	public static final String MOUTH = "mouth";
	public static final String RIGHT_EYE = "right_eye";
	public static final String LEFT_EYE = "left_eye";
	public static final String RIGHT_FIN = "right_fin";
	public static final String LEFT_FIN = "left_fin";
	public static final String DORSAL_FIN = "dorsal_fin";
	public static final String DORSAL_FIN_2 = "dorsal_fin_2";
	public static final String DORSAL_FIN_3 = "dorsal_fin_3";
	public static final String DORSAL_FIN_4 = "dorsal_fin_4";
	public static final String DORSAL_FIN_5 = "dorsal_fin_5";
	public static final String DORSAL_FIN_6 = "dorsal_fin_6";
	public static final String DORSAL_FIN_7 = "dorsal_fin_7";
	public static final String DORSAL_FIN_8 = "dorsal_fin_8";
	public static final String DORSAL_FIN_9 = "dorsal_fin_9";
	public static final String DORSAL_FIN_10 = "dorsal_fin_10";
	public static final String DORSAL_FIN_11 = "dorsal_fin_11";
	public static final String ANAL_FIN = "anal_fin";
	public static final String ANAL_FIN_2 = "anal_fin_2";
	public static final String ANAL_FIN_3 = "anal_fin_3";
	public static final String ANAL_FIN_4 = "anal_fin_4";
	public static final String ANAL_FIN_5 = "anal_fin_5";
	public static final String ANAL_FIN_6 = "anal_fin_6";
	public static final String ANAL_FIN_7 = "anal_fin_7";
	public static final String ANAL_FIN_8 = "anal_fin_8";
	public static final String ANAL_FIN_9 = "anal_fin_9";
	public static final String ANAL_FIN_10 = "anal_fin_10";

	private SnipeEelGeometry()
	{
	}

	public static LayerDefinition create()
	{
		MeshDefinition mesh = new MeshDefinition();
		PartDefinition root = mesh.getRoot();
		PartDefinition snipeEel = root.addOrReplaceChild(SNIPE_EEL, CubeListBuilder.create(),
			PartPose.offset(0.0F, 24.0F, 0.0F));
		PartDefinition body = snipeEel.addOrReplaceChild(BODY, CubeListBuilder.create()
			.texOffs(16, 14).addBox(-0.5F, -1.0F, 0.0F, 1.0F, 2.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -3.8734F, -25.0F));
		PartDefinition body2 = body.addOrReplaceChild(BODY_2, CubeListBuilder.create()
			.texOffs(0, 22).addBox(-0.5F, -1.0F, -1.0F, 1.0F, 2.0F, 6.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 5.0F));
		PartDefinition body3 = body2.addOrReplaceChild(BODY_3, CubeListBuilder.create()
			.texOffs(32, 21).addBox(-0.5F, -1.0F, -1.0F, 1.0F, 2.0F, 6.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 5.0F));
		PartDefinition body4 = body3.addOrReplaceChild(BODY_4, CubeListBuilder.create()
			.texOffs(46, 21).addBox(-0.5F, -1.0F, -1.0F, 1.0F, 2.0F, 6.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 5.0F));
		PartDefinition body5 = body4.addOrReplaceChild(BODY_5, CubeListBuilder.create()
			.texOffs(44, 13).addBox(-0.5F, -1.0F, -1.0F, 1.0F, 1.0F, 7.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 5.0F));
		PartDefinition body6 = body5.addOrReplaceChild(BODY_6, CubeListBuilder.create()
			.texOffs(0, 44).addBox(-0.5F, -1.0F, -1.0F, 1.0F, 1.0F, 6.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 6.0F));
		PartDefinition body7 = body6.addOrReplaceChild(BODY_7, CubeListBuilder.create()
			.texOffs(0, 14).addBox(-0.5F, -1.0F, -1.0F, 1.0F, 1.0F, 7.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 5.0F));
		PartDefinition body8 = body7.addOrReplaceChild(BODY_8, CubeListBuilder.create()
			.texOffs(0, 51).addBox(-0.5F, -1.0F, -1.0F, 1.0F, 1.0F, 6.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 6.0F));
		PartDefinition body9 = body8.addOrReplaceChild(BODY_9, CubeListBuilder.create()
			.texOffs(16, 21).addBox(-0.5F, -1.0F, -1.0F, 1.0F, 1.0F, 7.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 5.0F));
		PartDefinition body10 = body9.addOrReplaceChild(BODY_10, CubeListBuilder.create()
			.texOffs(0, 30).addBox(-0.5F, -1.0F, -1.0F, 1.0F, 1.0F, 6.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 6.0F));
		PartDefinition body11 = body10.addOrReplaceChild(BODY_11, CubeListBuilder.create()
			.texOffs(28, 13).addBox(-0.5F, -1.0F, -1.0F, 1.0F, 1.0F, 7.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 5.0F));
		PartDefinition body12 = body11.addOrReplaceChild(BODY_12, CubeListBuilder.create()
			.texOffs(0, 37).addBox(-0.5F, -1.0F, -1.0F, 1.0F, 1.0F, 6.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 6.0F));
		PartDefinition dorsalFin11 = body11.addOrReplaceChild(DORSAL_FIN_11, CubeListBuilder.create()
			.texOffs(14, 25).addBox(0.0F, -1.0F, 0.0F, 0.0F, 2.0F, 6.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -1.0F, 0.0F));
		PartDefinition analFin10 = body11.addOrReplaceChild(ANAL_FIN_10, CubeListBuilder.create()
			.texOffs(12, 52).addBox(0.0F, -1.0F, 0.0F, 0.0F, 2.0F, 6.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 0.0F));
		PartDefinition dorsalFin10 = body10.addOrReplaceChild(DORSAL_FIN_10, CubeListBuilder.create()
			.texOffs(14, 40).addBox(0.0F, -1.0F, 0.0F, 0.0F, 2.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -1.0F, 0.0F));
		PartDefinition analFin9 = body10.addOrReplaceChild(ANAL_FIN_9, CubeListBuilder.create()
			.texOffs(14, 36).addBox(0.0F, -1.0F, 0.0F, 0.0F, 2.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 0.0F));
		PartDefinition dorsalFin9 = body9.addOrReplaceChild(DORSAL_FIN_9, CubeListBuilder.create()
			.texOffs(14, 31).addBox(0.0F, -1.0F, 0.0F, 0.0F, 2.0F, 6.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -1.0F, 0.0F));
		PartDefinition analFin8 = body9.addOrReplaceChild(ANAL_FIN_8, CubeListBuilder.create()
			.texOffs(14, 23).addBox(0.0F, -1.0F, 0.0F, 0.0F, 2.0F, 6.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 0.0F));
		PartDefinition dorsalFin8 = body8.addOrReplaceChild(DORSAL_FIN_8, CubeListBuilder.create()
			.texOffs(14, 50).addBox(0.0F, -1.0F, 0.0F, 0.0F, 2.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -1.0F, 0.0F));
		PartDefinition analFin7 = body8.addOrReplaceChild(ANAL_FIN_7, CubeListBuilder.create()
			.texOffs(14, 34).addBox(0.0F, -1.0F, 0.0F, 0.0F, 2.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 0.0F));
		PartDefinition dorsalFin7 = body7.addOrReplaceChild(DORSAL_FIN_7, CubeListBuilder.create()
			.texOffs(14, 29).addBox(0.0F, -1.0F, 0.0F, 0.0F, 2.0F, 6.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -1.0F, 0.0F));
		PartDefinition analFin6 = body7.addOrReplaceChild(ANAL_FIN_6, CubeListBuilder.create()
			.texOffs(12, 56).addBox(0.0F, -1.0F, 0.0F, 0.0F, 2.0F, 6.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 0.0F));
		PartDefinition dorsalFin6 = body6.addOrReplaceChild(DORSAL_FIN_6, CubeListBuilder.create()
			.texOffs(14, 48).addBox(0.0F, -1.0F, 0.0F, 0.0F, 2.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -1.0F, 0.0F));
		PartDefinition analFin5 = body6.addOrReplaceChild(ANAL_FIN_5, CubeListBuilder.create()
			.texOffs(54, 6).addBox(0.0F, -1.0F, 0.0F, 0.0F, 2.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 0.0F));
		PartDefinition dorsalFin5 = body5.addOrReplaceChild(DORSAL_FIN_5, CubeListBuilder.create()
			.texOffs(14, 27).addBox(0.0F, -1.0F, 0.0F, 0.0F, 2.0F, 6.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -1.0F, 0.0F));
		PartDefinition analFin4 = body5.addOrReplaceChild(ANAL_FIN_4, CubeListBuilder.create()
			.texOffs(12, 54).addBox(0.0F, -1.0F, 0.0F, 0.0F, 2.0F, 6.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 0.0F));
		PartDefinition dorsalFin4 = body4.addOrReplaceChild(DORSAL_FIN_4, CubeListBuilder.create()
			.texOffs(14, 46).addBox(0.0F, -1.0F, 0.0F, 0.0F, 2.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -1.0F, 0.0F));
		PartDefinition analFin3 = body4.addOrReplaceChild(ANAL_FIN_3, CubeListBuilder.create()
			.texOffs(54, 4).addBox(0.0F, -1.0F, 0.0F, 0.0F, 2.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 1.0F, 0.0F));
		PartDefinition dorsalFin3 = body3.addOrReplaceChild(DORSAL_FIN_3, CubeListBuilder.create()
			.texOffs(14, 44).addBox(0.0F, -1.0F, 0.0F, 0.0F, 2.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -1.0F, 0.0F));
		PartDefinition analFin2 = body3.addOrReplaceChild(ANAL_FIN_2, CubeListBuilder.create()
			.texOffs(54, 2).addBox(0.0F, -1.0F, 0.0F, 0.0F, 2.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 1.0F, 0.0F));
		PartDefinition dorsalFin2 = body2.addOrReplaceChild(DORSAL_FIN_2, CubeListBuilder.create()
			.texOffs(14, 42).addBox(0.0F, -1.0F, 0.0F, 0.0F, 2.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -1.0F, 0.0F));
		PartDefinition analFin = body2.addOrReplaceChild(ANAL_FIN, CubeListBuilder.create()
			.texOffs(54, 0).addBox(0.0F, -1.0F, 0.0F, 0.0F, 2.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 1.0F, 0.0F));
		PartDefinition head = body.addOrReplaceChild(HEAD, CubeListBuilder.create()
			.texOffs(0, 58).addBox(-1.0F, -2.0F, -3.0F, 2.0F, 2.0F, 4.0F, new CubeDeformation(0.0F))
			.texOffs(28, 0).addBox(-0.5F, -1.0F, -14.0F, 1.0F, 1.0F, 12.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 0.0F));
		PartDefinition mouth = head.addOrReplaceChild(MOUTH, CubeListBuilder.create()
			.texOffs(0, 0).addBox(-0.5F, 0.0F, -12.0F, 1.0F, 1.0F, 13.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, -1.0F, 0.2443F, 0.0F, 0.0F));
		PartDefinition rightEye = head.addOrReplaceChild(RIGHT_EYE, CubeListBuilder.create()
			.texOffs(24, 39).addBox(-1.0F, -1.0F, -1.0F, 2.0F, 2.0F, 2.0F, new CubeDeformation(0.0F)),
			PartPose.offset(-0.8F, -1.0F, -2.0F));
		PartDefinition leftEye = head.addOrReplaceChild(LEFT_EYE, CubeListBuilder.create()
			.texOffs(54, 0).addBox(-1.0F, -1.0F, -1.0F, 2.0F, 2.0F, 2.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.8F, -1.0F, -2.0F));
		PartDefinition rightFin = body.addOrReplaceChild(RIGHT_FIN, CubeListBuilder.create()
			.texOffs(58, 2).addBox(0.0F, -0.5F, -1.0F, 0.0F, 1.0F, 2.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(-0.5F, -0.5F, 1.0F, 0.0F, -0.6981F, -0.2618F));
		PartDefinition leftFin = body.addOrReplaceChild(LEFT_FIN, CubeListBuilder.create()
			.texOffs(54, 2).addBox(0.0F, -0.5F, -1.0F, 0.0F, 1.0F, 2.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.5F, -0.5F, 1.0F, 0.0F, 0.6981F, 0.2618F));
		PartDefinition dorsalFin = body.addOrReplaceChild(DORSAL_FIN, CubeListBuilder.create()
			.texOffs(14, 38).addBox(0.0F, -1.0F, 0.0F, 0.0F, 2.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -1.0F, 0.0F));
		return LayerDefinition.create(mesh, 64, 64);
	}
}
