package com.abyssia.registry;

import com.abyssia.block.HangingPlantBlock;
import com.abyssia.block.ResourcePlantBlock;
import com.abyssia.block.SporeEmitter;
import com.abyssia.block.StackingPlantBlock;
import com.abyssia.block.UnderwaterPlantBlock;
import com.abyssia.item.MaterialItem;
import com.abyssia.item.ResinItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.Rarity;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.material.MapColor;
import net.minecraftforge.registries.RegistryObject;

/**
 * Resource plants and their materials. GENERATED by tools/plant_assets.py from tools/plant_defs.py: edit the
 * table there and rerun tools/gen_deep_assets.py. Existing plants that also yield materials stay in ModBlocks;
 * only their loot tables change.
 */
public final class ModPlants
{
    // ---------- Phase 1: fiber, resin, hard, luminous
    public static final RegistryObject<Block> STRANDWEED = ModBlocks.block("strandweed", () -> new ResourcePlantBlock(ModBlocks.plantProps(MapColor.COLOR_GREEN, 0), SporeEmitter.NONE, 0.12f));
    public static final RegistryObject<Block> AMBER_FAN = ModBlocks.block("amber_fan", () -> new ResourcePlantBlock(ModBlocks.plantProps(MapColor.TERRACOTTA_RED, 0), SporeEmitter.NONE, 0.06f));
    public static final RegistryObject<Block> RESIN_ROOT = ModBlocks.block("resin_root", () -> new HangingPlantBlock(ModBlocks.plantProps(MapColor.TERRACOTTA_BROWN, 0), 10, SporeEmitter.NONE));
    public static final RegistryObject<Block> KNOTSTALK = ModBlocks.block("knotstalk", () -> new StackingPlantBlock(ModBlocks.plantProps(MapColor.TERRACOTTA_WHITE, 0), 6, false, SporeEmitter.NONE));
    public static final RegistryObject<Block> LUMEN_QUILL = ModBlocks.block("lumen_quill", () -> new ResourcePlantBlock(ModBlocks.plantProps(MapColor.COLOR_PURPLE, 0).lightLevel(s -> s.getValue(ResourcePlantBlock.RIPE) ? 4 : 0), SporeEmitter.GLOW_DUST, 0.05f));
    // ---------- Phase 2: oil, crystal symbiosis
    public static final RegistryObject<Block> OIL_BLADDER_WEED = ModBlocks.block("oil_bladder_weed", () -> new ResourcePlantBlock(ModBlocks.plantProps(MapColor.COLOR_BROWN, 0), SporeEmitter.NONE, 0.05f));
    public static final RegistryObject<Block> GLASSLACE = ModBlocks.block("glasslace", () -> new ResourcePlantBlock(ModBlocks.plantProps(MapColor.COLOR_LIGHT_GRAY, 0).lightLevel(s -> s.getValue(ResourcePlantBlock.RIPE) ? 3 : 0), SporeEmitter.NONE, 0.025f));
    // ---------- Phase 3: mud and volcanic flora
    public static final RegistryObject<Block> SILT_COMB = ModBlocks.block("silt_comb", () -> new UnderwaterPlantBlock(ModBlocks.plantProps(MapColor.TERRACOTTA_GRAY, 0), SporeEmitter.NONE));
    public static final RegistryObject<Block> CINDER_STALK = ModBlocks.block("cinder_stalk", () -> new UnderwaterPlantBlock(ModBlocks.plantProps(MapColor.COLOR_BLACK, 0), SporeEmitter.NONE));
    // ---------- Phase 4: hadal
    public static final RegistryObject<Block> PRESSURE_GOURD = ModBlocks.block("pressure_gourd", () -> new ResourcePlantBlock(ModBlocks.plantProps(MapColor.COLOR_BLUE, 0), SporeEmitter.NONE, 0.008f));

    // ---------- materials: base
    public static final RegistryObject<Item> DEEP_FIBER = ModItems.tabItem("deep_fiber", () -> new MaterialItem(new Item.Properties().rarity(Rarity.COMMON), 0, true));
    public static final RegistryObject<Item> PLANT_RESIN = ModItems.tabItem("plant_resin", () -> new ResinItem(new Item.Properties().rarity(Rarity.COMMON), 0, true));
    public static final RegistryObject<Item> HARD_STALK = ModItems.tabItem("hard_stalk", () -> new MaterialItem(new Item.Properties().rarity(Rarity.COMMON), 200, true));
    public static final RegistryObject<Item> ORGANIC_MATTER = ModItems.tabItem("organic_matter", () -> new MaterialItem(new Item.Properties().rarity(Rarity.COMMON), 0, true));
    public static final RegistryObject<Item> BIO_OIL = ModItems.tabItem("bio_oil", () -> new MaterialItem(new Item.Properties().rarity(Rarity.UNCOMMON), 800, true));
    public static final RegistryObject<Item> LUMEN_GEL = ModItems.tabItem("lumen_gel", () -> new MaterialItem(new Item.Properties().rarity(Rarity.UNCOMMON), 0, true));
    public static final RegistryObject<Item> DEEP_PIGMENT = ModItems.tabItem("deep_pigment", () -> new MaterialItem(new Item.Properties().rarity(Rarity.UNCOMMON), 0, true));
    public static final RegistryObject<Item> THERMAL_FIBER = ModItems.tabItem("thermal_fiber", () -> new MaterialItem(new Item.Properties().rarity(Rarity.UNCOMMON), 0, true));
    public static final RegistryObject<Item> CRYSTAL_SAP = ModItems.tabItem("crystal_sap", () -> new MaterialItem(new Item.Properties().rarity(Rarity.RARE), 0, true));
    public static final RegistryObject<Item> HADAL_HUSK = ModItems.tabItem("hadal_husk", () -> new MaterialItem(new Item.Properties().rarity(Rarity.EPIC), 0, true));
    // ---------- materials: processed
    public static final RegistryObject<Item> FIBER_ROPE = ModItems.tabItem("fiber_rope", () -> new MaterialItem(new Item.Properties().rarity(Rarity.COMMON), 0, false));
    public static final RegistryObject<Item> SEA_CLOTH = ModItems.tabItem("sea_cloth", () -> new MaterialItem(new Item.Properties().rarity(Rarity.COMMON), 0, false));
    public static final RegistryObject<Item> MARINE_ADHESIVE = ModItems.tabItem("marine_adhesive", () -> new MaterialItem(new Item.Properties().rarity(Rarity.COMMON), 0, false));
    public static final RegistryObject<Item> REFINED_OIL = ModItems.tabItem("refined_oil", () -> new MaterialItem(new Item.Properties().rarity(Rarity.UNCOMMON), 2400, false));
    public static final RegistryObject<Item> LUMEN_CELL = ModItems.tabItem("lumen_cell", () -> new MaterialItem(new Item.Properties().rarity(Rarity.UNCOMMON), 0, false));
    public static final RegistryObject<Item> THERMAL_FELT = ModItems.tabItem("thermal_felt", () -> new MaterialItem(new Item.Properties().rarity(Rarity.UNCOMMON), 0, false));
    public static final RegistryObject<Item> CRYSTAL_LENS = ModItems.tabItem("crystal_lens", () -> new MaterialItem(new Item.Properties().rarity(Rarity.RARE), 0, false));
    public static final RegistryObject<Item> HADAL_PLATING = ModItems.tabItem("hadal_plating", () -> new MaterialItem(new Item.Properties().rarity(Rarity.EPIC), 0, false));

    private ModPlants() {}

    /** Loads the class, so the entries above join ModBlocks' and ModItems' registers. */
    static void init() {}
}
