// Java export for Minecraft Forge 1.20.1 (Mojang mappings), following exactly the conversions of
// Blockbench's Modded Entity exporter (template "Forge 1.17+", modded_entity_flip_y = true):
//   bone offset: x negated, y negated (+24 for the root), rotation x / y negated;
//   cube box:    x = pivot.x - to.x, y = -from.y - size.y + pivot.y, z = from.z - pivot.z;
//   rotated cubes become "<cube>_r1" sub-parts; animations use AnimationDefinition with
//   position x and rotation x / y negated.
// Output matches the Abyssia convention: <Name>Geometry.create() + bone name constants,
// and <Name>Animations with AnimationDefinition constants for HierarchicalModel#animate.

import { pascalCase } from '../generator/util.js';
import { cubeSize } from '../uv/box_uv.js';

const DEG = Math.PI / 180;

function f(v) {
	const r = Math.round(v * 10000) / 10000;
	const s = String(Object.is(r, -0) ? 0 : r);
	return (s.includes('.') || s.includes('e') ? s : s + '.0') + 'F';
}
const constName = (name) => name.toUpperCase().replace(/[^A-Z0-9]+/g, '_');
const javaVar = (name) => name.replace(/_([a-z0-9])/g, (_, c) => c.toUpperCase());

/** Geometry class: bone constants + create() returning the LayerDefinition. */
export function javaGeometry(model, { pkg = 'com.abyssia.client.entity.model', className } = {}) {
	const cls = className || `${pascalCase(model.id)}Geometry`;
	const { geometry, uv } = model;
	const bones = new Map(geometry.bones.map((b) => [b.name, b]));
	const children = new Map(geometry.bones.map((b) => [b.name, []]));
	for (const b of geometry.bones) if (b.parent) children.get(b.parent).push(b);
	const cubesOf = new Map(geometry.bones.map((b) => [b.name, []]));
	for (const c of geometry.cubes) cubesOf.get(c.bone).push(c);
	const usedNames = new Set(geometry.bones.map((b) => b.name));
	const lines = [];

	const offset = (origin, parent) => {
		const o = parent ? origin.map((v, i) => v - parent.pivot[i]) : origin.slice();
		return [-o[0], parent ? -o[1] : -o[1] + 24, o[2]];
	};
	const pose = (origin, rotation, parent) => {
		const [x, y, z] = offset(origin, parent);
		if (rotation.every((v) => !v)) return `PartPose.offset(${f(x)}, ${f(y)}, ${f(z)})`;
		return `PartPose.offsetAndRotation(${f(x)}, ${f(y)}, ${f(z)}, ${f(-rotation[0] * DEG)}, ${f(-rotation[1] * DEG)}, ${f(rotation[2] * DEG)})`;
	};
	const boxes = (cubes, pivot) =>
		cubes
			.map((c) => {
				const size = cubeSize(c);
				const cuv = uv.cubes[c.name];
				const m = cuv.mirror ? '.mirror()' : '';
				const mEnd = cuv.mirror ? '.mirror(false)' : '';
				const x = pivot[0] - c.to[0], y = -c.from[1] - size[1] + pivot[1], z = c.from[2] - pivot[2];
				return `.texOffs(${Math.floor(cuv.offset[0])}, ${Math.floor(cuv.offset[1])})${m}.addBox(${f(x)}, ${f(y)}, ${f(z)}, ${f(size[0])}, ${f(size[1])}, ${f(size[2])}, new CubeDeformation(0.0F))${mEnd}`;
			})
			.join('\n\t\t\t');
	const unique = (base) => {
		let n = 1;
		while (usedNames.has(`${base}_r${n}`)) n++;
		const name = `${base}_r${n}`;
		usedNames.add(name);
		return name;
	};

	const emit = (bone, parentVar) => {
		const parent = bone.parent ? bones.get(bone.parent) : null;
		const v = javaVar(bone.name);
		const plain = cubesOf.get(bone.name).filter((c) => c.rotation.every((r) => !r));
		const rotated = cubesOf.get(bone.name).filter((c) => c.rotation.some((r) => r));
		lines.push(`\t\tPartDefinition ${v} = ${parentVar}.addOrReplaceChild(${constName(bone.name)}, CubeListBuilder.create()${plain.length ? '\n\t\t\t' + boxes(plain, bone.pivot) : ''},\n\t\t\t${pose(bone.pivot, bone.rotation, parent)});`);
		// Rotated cubes -> one sub-part per distinct (origin, rotation), like Blockbench's cube_r1 groups
		const groups = new Map();
		for (const c of rotated) {
			const key = `${c.origin.join(',')}|${c.rotation.join(',')}`;
			if (!groups.has(key)) groups.set(key, []);
			groups.get(key).push(c);
		}
		for (const list of groups.values()) {
			const c0 = list[0];
			const name = unique(c0.name);
			lines.push(`\t\t${v}.addOrReplaceChild("${name}", CubeListBuilder.create()\n\t\t\t${boxes(list, c0.origin)},\n\t\t\t${pose(c0.origin, c0.rotation, bone)});`);
		}
		for (const child of children.get(bone.name)) emit(child, v);
	};
	for (const b of geometry.bones.filter((x) => !x.parent)) emit(b, 'root');

	return `package ${pkg};

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Generated by tools/bbmodel-generator (${model.id}.bbmodel, template ${model.template}, seed ${model.settings.seed}).
 * Texture ${uv.width}x${uv.height} UV (${model.textures.base.width}x${model.textures.base.height} px): textures/entity/${model.id}.png${model.textures.glow ? `, glow mask textures/entity/${model.id}_glow.png` : ''}.
 * Regenerate with: node tools/bbmodel-generator/cli.js ${model.id}
 */
public final class ${cls}
{
${geometry.bones.map((b) => `\tpublic static final String ${constName(b.name)} = "${b.name}";`).join('\n')}

\tprivate ${cls}()
\t{
\t}

\tpublic static LayerDefinition create()
\t{
\t\tMeshDefinition mesh = new MeshDefinition();
\t\tPartDefinition root = mesh.getRoot();
${lines.join('\n')}
\t\treturn LayerDefinition.create(mesh, ${uv.width}, ${uv.height});
\t}
}
`;
}

/** Animations class: one AnimationDefinition constant per clip. */
export function javaAnimations(model, { pkg = 'com.abyssia.client.entity.model', className } = {}) {
	const cls = className || `${pascalCase(model.id)}Animations`;
	const kf = (channel, k) => {
		let [x, y, z] = k.value;
		if (channel === 'position') x = -x;
		if (channel === 'rotation') {
			x = -x;
			y = -y;
		}
		const vec = channel === 'rotation' ? 'degreeVec' : channel === 'position' ? 'posVec' : 'scaleVec';
		const interp = k.interpolation === 'catmullrom' ? 'CATMULLROM' : 'LINEAR';
		return `new Keyframe(${f(k.time)}, KeyframeAnimations.${vec}(${f(x)}, ${f(y)}, ${f(z)}), AnimationChannel.Interpolations.${interp})`;
	};
	const target = { rotation: 'ROTATION', position: 'POSITION', scale: 'SCALE' };
	const defs = model.animations.map((clip) => {
		const channels = [];
		for (const [bone, chs] of Object.entries(clip.tracks)) {
			for (const [channel, keys] of Object.entries(chs)) {
				channels.push(`\t\t.addAnimation("${bone}", new AnimationChannel(AnimationChannel.Targets.${target[channel]},\n\t\t\t${keys.map((k) => kf(channel, k)).join(',\n\t\t\t')}))`);
			}
		}
		return `\t/** ${clip.name} (${clip.loop}, ${clip.length}s)${clip.description ? ': ' + clip.description : ''} */\n\tpublic static final AnimationDefinition ${constName(clip.name)} = AnimationDefinition.Builder.withLength(${f(clip.length)})${clip.loop === 'loop' ? '.looping()' : ''}\n${channels.join('\n')}\n\t\t.build();`;
	});
	return `package ${pkg};

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

/**
 * Generated by tools/bbmodel-generator (${model.id}.bbmodel). Play with HierarchicalModel#animate(state, DEFINITION, ageInTicks).
 * "hold" clips should keep their AnimationState running at the last frame; "once" clips stop at their length.
 */
public final class ${cls}
{
\tprivate ${cls}()
\t{
\t}

${defs.join('\n\n')}
}
`;
}
