package com.abyssia.client.anim;

import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import com.mojang.math.Axis;
import net.minecraft.client.renderer.LightTexture;
import net.minecraft.client.renderer.texture.OverlayTexture;

/**
 * Loader-neutral renderer for per-group baked meshes generated by tools/anim_model.py (e.g. {@code DockMesh.PARTS}).
 * Parts are in depth-first order (parents before children). Per part: translate(pivot / 16 + pose offset) then rotate
 * Z, Y, X (rest + pose degrees; Blockbench / three.js 'ZYX'), then the part's quads, then its children.
 */
public final class AnimMeshRenderer
{
    public static final int STRIDE = 23;

    /** One Blockbench group: pivot in px relative to the parent's pivot, rest rotation in degrees, quads in blocks. */
    public record Part(String name, int parent, float px, float py, float pz, float rx, float ry, float rz, float[] quads) {}

    /** Per-part pose override added on top of the rest pose: rotation in degrees, offset in blocks. */
    public static final class Pose
    {
        public float rx, ry, rz, ox, oy, oz;

        public void reset()
        {
            rx = ry = rz = ox = oy = oz = 0.0f;
        }
    }

    /** Supplies the pose of part {@code index}; {@code out} is zeroed before each call (leave untouched for rest pose). */
    @FunctionalInterface
    public interface PoseProvider
    {
        void pose(int index, Part part, Pose out);
    }

    private AnimMeshRenderer() {}

    public static void render(PoseStack stack, VertexConsumer out, Part[] parts, PoseProvider poses, int light)
    {
        render(stack, out, parts, poses, light, OverlayTexture.NO_OVERLAY, 255, 255, 255, 255);
    }

    public static void render(PoseStack stack, VertexConsumer out, Part[] parts, PoseProvider poses, int light, int overlay,
                              int r, int g, int b, int a)
    {
        render(stack, out, parts, poses, light, overlay, r, g, b, a, null);
    }

    /** {@code glow} = atlas region {u0, v0, u1, v1} (0..1) whose quads are drawn full-bright (emissive tile), or null. */
    public static void render(PoseStack stack, VertexConsumer out, Part[] parts, PoseProvider poses, int light, int overlay,
                              int r, int g, int b, int a, float[] glow)
    {
        Pose pose = new Pose();
        int[] open = new int[parts.length + 1]; // stack of part indices whose pushPose is still active
        int depth = 0;
        for (int i = 0; i < parts.length; i++)
        {
            Part p = parts[i];
            // close finished siblings/subtrees until the top of the stack is this part's parent
            while (depth > 0 && open[depth - 1] != p.parent())
            {
                stack.popPose();
                depth--;
            }
            pose.reset();
            if (poses != null) poses.pose(i, p, pose);
            stack.pushPose();
            open[depth++] = i;
            stack.translate(p.px() / 16.0f + pose.ox, p.py() / 16.0f + pose.oy, p.pz() / 16.0f + pose.oz);
            float rz = p.rz() + pose.rz, ry = p.ry() + pose.ry, rx = p.rx() + pose.rx;
            if (rz != 0.0f) stack.mulPose(Axis.ZP.rotationDegrees(rz));
            if (ry != 0.0f) stack.mulPose(Axis.YP.rotationDegrees(ry));
            if (rx != 0.0f) stack.mulPose(Axis.XP.rotationDegrees(rx));
            quads(stack.last(), out, p.quads(), light, overlay, r, g, b, a, glow);
        }
        while (depth > 0)
        {
            stack.popPose();
            depth--;
        }
    }

    private static void quads(PoseStack.Pose pose, VertexConsumer out, float[] mesh, int light, int overlay, int r, int g, int b, int a, float[] glow)
    {
        for (int q = 0; q + STRIDE <= mesh.length; q += STRIDE)
        {
            float nx = mesh[q + 20], ny = mesh[q + 21], nz = mesh[q + 22];
            int ql = light;
            if (glow != null)
            {
                float cu = (mesh[q + 3] + mesh[q + 8] + mesh[q + 13] + mesh[q + 18]) * 0.25f;
                float cv = (mesh[q + 4] + mesh[q + 9] + mesh[q + 14] + mesh[q + 19]) * 0.25f;
                if (cu >= glow[0] && cu <= glow[2] && cv >= glow[1] && cv <= glow[3]) ql = LightTexture.FULL_BRIGHT;
            }
            for (int v = 0; v < 4; v++)
            {
                int i = q + v * 5;
                out.addVertex(pose, mesh[i], mesh[i + 1], mesh[i + 2]).setColor(r, g, b, a).setUv(mesh[i + 3], mesh[i + 4])
                        .setOverlay(overlay).setLight(ql).setNormal(pose, nx, ny, nz);
            }
        }
    }
}
