package com.abyssia.client.entity.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Generated by tools/bbmodel-generator (deep_sea_shrimp.bbmodel, template crustacean, seed 1).
 * Texture 64x64 UV (64x64 px): textures/entity/deep_sea_shrimp.png, glow mask textures/entity/deep_sea_shrimp_glow.png.
 * Regenerate with: node tools/bbmodel-generator/cli.js deep_sea_shrimp
 */
public final class DeepSeaShrimpGeometry
{
	public static final String DEEP_SEA_SHRIMP = "deep_sea_shrimp";
	public static final String BODY = "body";
	public static final String RIGHT_EYE = "right_eye";
	public static final String LEFT_EYE = "left_eye";
	public static final String ROSTRUM = "rostrum";
	public static final String RIGHT_ANTENNA = "right_antenna";
	public static final String RIGHT_ANTENNA_2 = "right_antenna_2";
	public static final String RIGHT_ANTENNA_3 = "right_antenna_3";
	public static final String LEFT_ANTENNA = "left_antenna";
	public static final String LEFT_ANTENNA_2 = "left_antenna_2";
	public static final String LEFT_ANTENNA_3 = "left_antenna_3";
	public static final String RIGHT_LEG_1 = "right_leg_1";
	public static final String RIGHT_LEG_1_FOOT = "right_leg_1_foot";
	public static final String LEFT_LEG_1 = "left_leg_1";
	public static final String LEFT_LEG_1_FOOT = "left_leg_1_foot";
	public static final String RIGHT_LEG_2 = "right_leg_2";
	public static final String RIGHT_LEG_2_FOOT = "right_leg_2_foot";
	public static final String LEFT_LEG_2 = "left_leg_2";
	public static final String LEFT_LEG_2_FOOT = "left_leg_2_foot";
	public static final String RIGHT_LEG_3 = "right_leg_3";
	public static final String RIGHT_LEG_3_FOOT = "right_leg_3_foot";
	public static final String LEFT_LEG_3 = "left_leg_3";
	public static final String LEFT_LEG_3_FOOT = "left_leg_3_foot";
	public static final String RIGHT_LEG_4 = "right_leg_4";
	public static final String RIGHT_LEG_4_FOOT = "right_leg_4_foot";
	public static final String LEFT_LEG_4 = "left_leg_4";
	public static final String LEFT_LEG_4_FOOT = "left_leg_4_foot";
	public static final String RIGHT_LEG_5 = "right_leg_5";
	public static final String RIGHT_LEG_5_FOOT = "right_leg_5_foot";
	public static final String LEFT_LEG_5 = "left_leg_5";
	public static final String LEFT_LEG_5_FOOT = "left_leg_5_foot";
	public static final String ABDOMEN = "abdomen";
	public static final String ABDOMEN_2 = "abdomen_2";
	public static final String ABDOMEN_3 = "abdomen_3";
	public static final String ABDOMEN_4 = "abdomen_4";
	public static final String ABDOMEN_5 = "abdomen_5";
	public static final String ABDOMEN_6 = "abdomen_6";
	public static final String TAIL_FAN = "tail_fan";
	public static final String RIGHT_UROPOD = "right_uropod";
	public static final String LEFT_UROPOD = "left_uropod";

	private DeepSeaShrimpGeometry()
	{
	}

	public static LayerDefinition create()
	{
		MeshDefinition mesh = new MeshDefinition();
		PartDefinition root = mesh.getRoot();
		PartDefinition deepSeaShrimp = root.addOrReplaceChild(DEEP_SEA_SHRIMP, CubeListBuilder.create(),
			PartPose.offset(0.0F, 24.0F, 0.0F));
		PartDefinition body = deepSeaShrimp.addOrReplaceChild(BODY, CubeListBuilder.create()
			.texOffs(0, 12).addBox(-2.0F, -1.5F, -3.5F, 4.0F, 4.0F, 7.0F, new CubeDeformation(0.0F))
			.texOffs(0, 56).addBox(-2.0F, -2.5F, -3.5F, 4.0F, 1.0F, 7.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -11.0564F, -7.0F));
		PartDefinition rightEye = body.addOrReplaceChild(RIGHT_EYE, CubeListBuilder.create()
			.texOffs(28, 38).addBox(-0.5F, -0.5F, -1.0F, 1.0F, 1.0F, 2.0F, new CubeDeformation(0.0F))
			.texOffs(56, 32).addBox(-1.0F, -1.0F, -2.5F, 2.0F, 2.0F, 2.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(-1.0F, -0.5F, -3.5F, 0.0F, 0.3491F, 0.0F));
		PartDefinition leftEye = body.addOrReplaceChild(LEFT_EYE, CubeListBuilder.create()
			.texOffs(22, 38).addBox(-0.5F, -0.5F, -1.0F, 1.0F, 1.0F, 2.0F, new CubeDeformation(0.0F))
			.texOffs(48, 32).addBox(-1.0F, -1.0F, -2.5F, 2.0F, 2.0F, 2.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(1.0F, -0.5F, -3.5F, 0.0F, -0.3491F, 0.0F));
		PartDefinition rostrum = body.addOrReplaceChild(ROSTRUM, CubeListBuilder.create()
			.texOffs(44, 18).addBox(-0.5F, 0.0F, -6.0F, 1.0F, 1.0F, 7.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, -1.5F, -3.5F, -0.2443F, 0.0F, 0.0F));
		PartDefinition rightAntenna = body.addOrReplaceChild(RIGHT_ANTENNA, CubeListBuilder.create()
			.texOffs(24, 0).addBox(-0.5F, -0.5F, -11.0F, 1.0F, 1.0F, 11.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(-0.5F, -1.0F, -2.5F, -0.384F, 0.6981F, 0.0F));
		PartDefinition rightAntenna2 = rightAntenna.addOrReplaceChild(RIGHT_ANTENNA_2, CubeListBuilder.create()
			.texOffs(0, 34).addBox(-0.5F, -0.5F, -10.0F, 1.0F, 1.0F, 10.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, -11.0F, 0.1536F, 1.0472F, 0.0F));
		PartDefinition rightAntenna3 = rightAntenna2.addOrReplaceChild(RIGHT_ANTENNA_3, CubeListBuilder.create()
			.texOffs(0, 45).addBox(-0.5F, -0.5F, -10.0F, 1.0F, 1.0F, 10.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, -10.0F, 0.1536F, 1.0472F, 0.0F));
		PartDefinition leftAntenna = body.addOrReplaceChild(LEFT_ANTENNA, CubeListBuilder.create()
			.texOffs(0, 0).addBox(-0.5F, -0.5F, -11.0F, 1.0F, 1.0F, 11.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.5F, -1.0F, -2.5F, -0.384F, -0.6981F, 0.0F));
		PartDefinition leftAntenna2 = leftAntenna.addOrReplaceChild(LEFT_ANTENNA_2, CubeListBuilder.create()
			.texOffs(22, 12).addBox(-0.5F, -0.5F, -10.0F, 1.0F, 1.0F, 10.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, -11.0F, 0.1536F, -1.0472F, 0.0F));
		PartDefinition leftAntenna3 = leftAntenna2.addOrReplaceChild(LEFT_ANTENNA_3, CubeListBuilder.create()
			.texOffs(0, 23).addBox(-0.5F, -0.5F, -10.0F, 1.0F, 1.0F, 10.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, -10.0F, 0.1536F, -1.0472F, 0.0F));
		PartDefinition rightLeg1 = body.addOrReplaceChild(RIGHT_LEG_1, CubeListBuilder.create(),
			PartPose.offset(-1.0F, 1.5F, -2.5F));
		rightLeg1.addOrReplaceChild("right_leg_1_r1", CubeListBuilder.create()
			.texOffs(30, 46).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 4.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, -0.1729F, -0.4026F, 0.4194F));
		PartDefinition rightLeg1Foot = rightLeg1.addOrReplaceChild(RIGHT_LEG_1_FOOT, CubeListBuilder.create(),
			PartPose.offset(-1.358F, 3.7087F, -0.6333F));
		rightLeg1Foot.addOrReplaceChild("right_leg_1_foot_r1", CubeListBuilder.create()
			.texOffs(30, 51).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 4.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, -0.0406F, -0.4346F, 0.0962F));
		PartDefinition leftLeg1 = body.addOrReplaceChild(LEFT_LEG_1, CubeListBuilder.create(),
			PartPose.offset(1.0F, 1.5F, -2.5F));
		leftLeg1.addOrReplaceChild("left_leg_1_r1", CubeListBuilder.create()
			.texOffs(60, 18).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 4.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, -0.1729F, 0.4026F, -0.4194F));
		PartDefinition leftLeg1Foot = leftLeg1.addOrReplaceChild(LEFT_LEG_1_FOOT, CubeListBuilder.create(),
			PartPose.offset(1.358F, 3.7087F, -0.6333F));
		leftLeg1Foot.addOrReplaceChild("left_leg_1_foot_r1", CubeListBuilder.create()
			.texOffs(22, 41).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 4.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, -0.0406F, 0.4346F, -0.0962F));
		PartDefinition rightLeg2 = body.addOrReplaceChild(RIGHT_LEG_2, CubeListBuilder.create(),
			PartPose.offset(-1.0F, 1.5F, -1.0F));
		rightLeg2.addOrReplaceChild("right_leg_2_r1", CubeListBuilder.create()
			.texOffs(30, 56).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 4.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, -0.0829F, -0.2021F, 0.3924F));
		PartDefinition rightLeg2Foot = rightLeg2.addOrReplaceChild(RIGHT_LEG_2_FOOT, CubeListBuilder.create(),
			PartPose.offset(-1.4629F, 3.7087F, -0.3243F));
		rightLeg2Foot.addOrReplaceChild("right_leg_2_foot_r1", CubeListBuilder.create()
			.texOffs(40, 36).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 4.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, -0.0193F, -0.2173F, 0.0894F));
		PartDefinition leftLeg2 = body.addOrReplaceChild(LEFT_LEG_2, CubeListBuilder.create(),
			PartPose.offset(1.0F, 1.5F, -1.0F));
		leftLeg2.addOrReplaceChild("left_leg_2_r1", CubeListBuilder.create()
			.texOffs(22, 46).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 4.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, -0.0829F, 0.2021F, -0.3924F));
		PartDefinition leftLeg2Foot = leftLeg2.addOrReplaceChild(LEFT_LEG_2_FOOT, CubeListBuilder.create(),
			PartPose.offset(1.4629F, 3.7087F, -0.3243F));
		leftLeg2Foot.addOrReplaceChild("left_leg_2_foot_r1", CubeListBuilder.create()
			.texOffs(22, 51).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 4.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, -0.0193F, 0.2173F, -0.0894F));
		PartDefinition rightLeg3 = body.addOrReplaceChild(RIGHT_LEG_3, CubeListBuilder.create(),
			PartPose.offset(-1.0F, 1.5F, 0.0F));
		rightLeg3.addOrReplaceChild("right_leg_3_r1", CubeListBuilder.create()
			.texOffs(34, 39).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 4.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.384F));
		PartDefinition rightLeg3Foot = rightLeg3.addOrReplaceChild(RIGHT_LEG_3_FOOT, CubeListBuilder.create(),
			PartPose.offset(-1.4984F, 3.7087F, 0.0F));
		rightLeg3Foot.addOrReplaceChild("right_leg_3_foot_r1", CubeListBuilder.create()
			.texOffs(34, 44).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 4.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0873F));
		PartDefinition leftLeg3 = body.addOrReplaceChild(LEFT_LEG_3, CubeListBuilder.create(),
			PartPose.offset(1.0F, 1.5F, 0.0F));
		leftLeg3.addOrReplaceChild("left_leg_3_r1", CubeListBuilder.create()
			.texOffs(22, 56).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 4.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, -0.384F));
		PartDefinition leftLeg3Foot = leftLeg3.addOrReplaceChild(LEFT_LEG_3_FOOT, CubeListBuilder.create(),
			PartPose.offset(1.4984F, 3.7087F, 0.0F));
		leftLeg3Foot.addOrReplaceChild("left_leg_3_foot_r1", CubeListBuilder.create()
			.texOffs(26, 41).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 4.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, -0.0873F));
		PartDefinition rightLeg4 = body.addOrReplaceChild(RIGHT_LEG_4, CubeListBuilder.create(),
			PartPose.offset(-1.0F, 1.5F, 1.5F));
		rightLeg4.addOrReplaceChild("right_leg_4_r1", CubeListBuilder.create()
			.texOffs(34, 49).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 4.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0829F, 0.2021F, 0.3924F));
		PartDefinition rightLeg4Foot = rightLeg4.addOrReplaceChild(RIGHT_LEG_4_FOOT, CubeListBuilder.create(),
			PartPose.offset(-1.4629F, 3.7087F, 0.3243F));
		rightLeg4Foot.addOrReplaceChild("right_leg_4_foot_r1", CubeListBuilder.create()
			.texOffs(34, 54).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 4.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0193F, 0.2173F, 0.0894F));
		PartDefinition leftLeg4 = body.addOrReplaceChild(LEFT_LEG_4, CubeListBuilder.create(),
			PartPose.offset(1.0F, 1.5F, 1.5F));
		leftLeg4.addOrReplaceChild("left_leg_4_r1", CubeListBuilder.create()
			.texOffs(26, 46).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 4.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0829F, -0.2021F, -0.3924F));
		PartDefinition leftLeg4Foot = leftLeg4.addOrReplaceChild(LEFT_LEG_4_FOOT, CubeListBuilder.create(),
			PartPose.offset(1.4629F, 3.7087F, 0.3243F));
		leftLeg4Foot.addOrReplaceChild("left_leg_4_foot_r1", CubeListBuilder.create()
			.texOffs(26, 51).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 4.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0193F, -0.2173F, -0.0894F));
		PartDefinition rightLeg5 = body.addOrReplaceChild(RIGHT_LEG_5, CubeListBuilder.create(),
			PartPose.offset(-1.0F, 1.5F, 2.5F));
		rightLeg5.addOrReplaceChild("right_leg_5_r1", CubeListBuilder.create()
			.texOffs(34, 59).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 4.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.1729F, 0.4026F, 0.4194F));
		PartDefinition rightLeg5Foot = rightLeg5.addOrReplaceChild(RIGHT_LEG_5_FOOT, CubeListBuilder.create(),
			PartPose.offset(-1.358F, 3.7087F, 0.6333F));
		rightLeg5Foot.addOrReplaceChild("right_leg_5_foot_r1", CubeListBuilder.create()
			.texOffs(44, 36).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 4.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0406F, 0.4346F, 0.0962F));
		PartDefinition leftLeg5 = body.addOrReplaceChild(LEFT_LEG_5, CubeListBuilder.create(),
			PartPose.offset(1.0F, 1.5F, 2.5F));
		leftLeg5.addOrReplaceChild("left_leg_5_r1", CubeListBuilder.create()
			.texOffs(26, 56).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 4.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.1729F, -0.4026F, -0.4194F));
		PartDefinition leftLeg5Foot = leftLeg5.addOrReplaceChild(LEFT_LEG_5_FOOT, CubeListBuilder.create(),
			PartPose.offset(1.358F, 3.7087F, 0.6333F));
		leftLeg5Foot.addOrReplaceChild("left_leg_5_foot_r1", CubeListBuilder.create()
			.texOffs(30, 41).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 4.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0406F, -0.4346F, -0.0962F));
		PartDefinition abdomen = body.addOrReplaceChild(ABDOMEN, CubeListBuilder.create()
			.texOffs(48, 0).addBox(-2.0F, -2.5F, 0.0F, 4.0F, 5.0F, 4.0F, new CubeDeformation(0.0F))
			.texOffs(40, 33).addBox(-1.5F, 1.5F, 1.0F, 3.0F, 3.0F, 0.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 2.5F, -0.1571F, 0.0F, 0.0F));
		PartDefinition abdomen2 = abdomen.addOrReplaceChild(ABDOMEN_2, CubeListBuilder.create()
			.texOffs(48, 9).addBox(-2.0F, -2.5F, 0.0F, 4.0F, 5.0F, 4.0F, new CubeDeformation(0.0F))
			.texOffs(36, 23).addBox(-1.5F, 1.5F, 1.0F, 3.0F, 3.0F, 0.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 3.0F, -0.1571F, 0.0F, 0.0F));
		PartDefinition abdomen3 = abdomen2.addOrReplaceChild(ABDOMEN_3, CubeListBuilder.create()
			.texOffs(22, 23).addBox(-1.5F, -2.0F, 0.0F, 3.0F, 4.0F, 4.0F, new CubeDeformation(0.0F))
			.texOffs(60, 23).addBox(-1.0F, 1.0F, 1.0F, 2.0F, 3.0F, 0.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, -0.5F, 3.0F, -0.1571F, 0.0F, 0.0F));
		PartDefinition abdomen4 = abdomen3.addOrReplaceChild(ABDOMEN_4, CubeListBuilder.create()
			.texOffs(36, 26).addBox(-1.5F, -2.0F, 0.0F, 3.0F, 4.0F, 3.0F, new CubeDeformation(0.0F))
			.texOffs(22, 61).addBox(-1.0F, 1.0F, 1.0F, 2.0F, 3.0F, 0.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 3.0F, -0.1571F, 0.0F, 0.0F));
		PartDefinition abdomen5 = abdomen4.addOrReplaceChild(ABDOMEN_5, CubeListBuilder.create()
			.texOffs(22, 31).addBox(-1.0F, -1.5F, 0.0F, 2.0F, 3.0F, 4.0F, new CubeDeformation(0.0F))
			.texOffs(42, 23).addBox(-0.5F, 0.5F, 1.0F, 1.0F, 3.0F, 0.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, -0.5F, 2.0F, -0.1571F, 0.0F, 0.0F));
		PartDefinition abdomen6 = abdomen5.addOrReplaceChild(ABDOMEN_6, CubeListBuilder.create()
			.texOffs(48, 26).addBox(-1.0F, -1.5F, 0.0F, 2.0F, 3.0F, 3.0F, new CubeDeformation(0.0F))
			.texOffs(46, 33).addBox(-0.5F, 0.5F, 1.0F, 1.0F, 3.0F, 0.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 3.0F, -0.1571F, 0.0F, 0.0F));
		PartDefinition tailFan = abdomen6.addOrReplaceChild(TAIL_FAN, CubeListBuilder.create()
			.texOffs(38, 12).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 0.0F, 6.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 2.0F, -0.0785F, 0.0F, 0.0F));
		PartDefinition rightUropod = tailFan.addOrReplaceChild(RIGHT_UROPOD, CubeListBuilder.create()
			.texOffs(28, 33).addBox(-3.0F, 0.0F, -1.0F, 3.0F, 0.0F, 6.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(-1.0F, 0.0F, 0.0F, 0.0F, -0.384F, 0.0F));
		PartDefinition leftUropod = tailFan.addOrReplaceChild(LEFT_UROPOD, CubeListBuilder.create()
			.texOffs(52, 26).addBox(0.0F, 0.0F, -1.0F, 3.0F, 0.0F, 6.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(1.0F, 0.0F, 0.0F, 0.0F, 0.384F, 0.0F));
		return LayerDefinition.create(mesh, 64, 64);
	}
}
