package com.abyssia.client.entity.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Generated by tools/bbmodel-generator (barreleye.bbmodel, template fish, seed 1).
 * Texture 64x32 UV (64x32 px): textures/entity/barreleye.png, glow mask textures/entity/barreleye_glow.png.
 * Regenerate with: node tools/bbmodel-generator/cli.js barreleye
 */
public final class BarreleyeGeometry
{
	public static final String BARRELEYE = "barreleye";
	public static final String BODY = "body";
	public static final String HEAD = "head";
	public static final String MOUTH = "mouth";
	public static final String RIGHT_EYE = "right_eye";
	public static final String LEFT_EYE = "left_eye";
	public static final String DOME = "dome";
	public static final String RIGHT_FIN = "right_fin";
	public static final String LEFT_FIN = "left_fin";
	public static final String RIGHT_PELVIC_FIN = "right_pelvic_fin";
	public static final String LEFT_PELVIC_FIN = "left_pelvic_fin";
	public static final String DORSAL_FIN = "dorsal_fin";
	public static final String ANAL_FIN = "anal_fin";
	public static final String TAIL = "tail";
	public static final String TAIL_FIN = "tail_fin";

	private BarreleyeGeometry()
	{
	}

	public static LayerDefinition create()
	{
		MeshDefinition mesh = new MeshDefinition();
		PartDefinition root = mesh.getRoot();
		PartDefinition barreleye = root.addOrReplaceChild(BARRELEYE, CubeListBuilder.create(),
			PartPose.offset(0.0F, 24.0F, 0.0F));
		PartDefinition body = barreleye.addOrReplaceChild(BODY, CubeListBuilder.create()
			.texOffs(0, 0).addBox(-2.5F, -2.0F, -1.0F, 5.0F, 4.0F, 8.0F, new CubeDeformation(0.0F))
			.texOffs(20, 23).addBox(-1.5F, -3.0F, -1.0F, 3.0F, 1.0F, 7.0F, new CubeDeformation(0.0F))
			.texOffs(0, 23).addBox(-1.5F, 2.0F, -1.0F, 3.0F, 1.0F, 7.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -5.2214F, -2.0F));
		PartDefinition head = body.addOrReplaceChild(HEAD, CubeListBuilder.create()
			.texOffs(24, 12).addBox(-2.5F, -3.0F, -6.0F, 5.0F, 4.0F, 6.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 0.0F));
		PartDefinition mouth = head.addOrReplaceChild(MOUTH, CubeListBuilder.create()
			.texOffs(46, 0).addBox(-1.5F, 0.0F, -5.0F, 3.0F, 1.0F, 6.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 1.0F, -1.0F));
		PartDefinition rightEye = head.addOrReplaceChild(RIGHT_EYE, CubeListBuilder.create()
			.texOffs(46, 11).addBox(-1.0F, -3.0F, -1.0F, 2.0F, 3.0F, 2.0F, new CubeDeformation(0.0F)),
			PartPose.offset(-1.5F, -2.0F, -3.0F));
		PartDefinition leftEye = head.addOrReplaceChild(LEFT_EYE, CubeListBuilder.create()
			.texOffs(38, 0).addBox(-1.0F, -3.0F, -1.0F, 2.0F, 3.0F, 2.0F, new CubeDeformation(0.0F)),
			PartPose.offset(1.5F, -2.0F, -3.0F));
		PartDefinition dome = head.addOrReplaceChild(DOME, CubeListBuilder.create()
			.texOffs(0, 12).addBox(-3.0F, -4.0F, -0.5F, 6.0F, 5.0F, 6.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -3.0F, -6.0F));
		PartDefinition rightFin = body.addOrReplaceChild(RIGHT_FIN, CubeListBuilder.create()
			.texOffs(40, 0).addBox(0.0F, -2.0F, -1.0F, 0.0F, 4.0F, 7.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(-2.5F, 0.0F, 1.0F, 0.0F, -0.9599F, -0.6109F));
		PartDefinition leftFin = body.addOrReplaceChild(LEFT_FIN, CubeListBuilder.create()
			.texOffs(26, 0).addBox(0.0F, -2.0F, -1.0F, 0.0F, 4.0F, 7.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(2.5F, 0.0F, 1.0F, 0.0F, 0.9599F, 0.6109F));
		PartDefinition rightPelvicFin = body.addOrReplaceChild(RIGHT_PELVIC_FIN, CubeListBuilder.create()
			.texOffs(40, 18).addBox(0.0F, -1.0F, -1.0F, 0.0F, 3.0F, 4.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(-1.5F, 3.0F, 4.0F, 0.3491F, -0.3491F, 0.0F));
		PartDefinition leftPelvicFin = body.addOrReplaceChild(LEFT_PELVIC_FIN, CubeListBuilder.create()
			.texOffs(54, 9).addBox(0.0F, -1.0F, -1.0F, 0.0F, 3.0F, 4.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(1.5F, 3.0F, 4.0F, 0.3491F, 0.3491F, 0.0F));
		PartDefinition dorsalFin = body.addOrReplaceChild(DORSAL_FIN, CubeListBuilder.create()
			.texOffs(46, 13).addBox(0.0F, -2.0F, 0.0F, 0.0F, 3.0F, 3.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -3.0F, 1.0F));
		PartDefinition analFin = body.addOrReplaceChild(ANAL_FIN, CubeListBuilder.create()
			.texOffs(46, 17).addBox(0.0F, -1.0F, 0.0F, 0.0F, 3.0F, 2.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 3.0F, 4.0F));
		PartDefinition tail = body.addOrReplaceChild(TAIL, CubeListBuilder.create()
			.texOffs(26, 0).addBox(-1.5F, -2.0F, 0.0F, 3.0F, 4.0F, 3.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 6.0F));
		PartDefinition tailFin = tail.addOrReplaceChild(TAIL_FIN, CubeListBuilder.create()
			.texOffs(54, 2).addBox(0.0F, -3.0F, -1.0F, 0.0F, 6.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 3.0F));
		return LayerDefinition.create(mesh, 64, 32);
	}
}
