package com.abyssia.client.entity.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Generated by tools/bbmodel-generator (brittle_star.bbmodel, template parts, seed 1).
 * Texture 64x64 UV (64x64 px): textures/entity/brittle_star.png.
 * Regenerate with: node tools/bbmodel-generator/cli.js brittle_star
 */
public final class BrittleStarGeometry
{
	public static final String BRITTLE_STAR = "brittle_star";
	public static final String DISC = "disc";
	public static final String DISC_TOP = "disc_top";
	public static final String ARM_1 = "arm_1";
	public static final String ARM_1_2 = "arm_1_2";
	public static final String ARM_1_3 = "arm_1_3";
	public static final String ARM_1_4 = "arm_1_4";
	public static final String ARM_2 = "arm_2";
	public static final String ARM_2_2 = "arm_2_2";
	public static final String ARM_2_3 = "arm_2_3";
	public static final String ARM_2_4 = "arm_2_4";
	public static final String ARM_3 = "arm_3";
	public static final String ARM_3_2 = "arm_3_2";
	public static final String ARM_3_3 = "arm_3_3";
	public static final String ARM_3_4 = "arm_3_4";
	public static final String ARM_4 = "arm_4";
	public static final String ARM_4_2 = "arm_4_2";
	public static final String ARM_4_3 = "arm_4_3";
	public static final String ARM_4_4 = "arm_4_4";
	public static final String ARM_5 = "arm_5";
	public static final String ARM_5_2 = "arm_5_2";
	public static final String ARM_5_3 = "arm_5_3";
	public static final String ARM_5_4 = "arm_5_4";

	private BrittleStarGeometry()
	{
	}

	public static LayerDefinition create()
	{
		MeshDefinition mesh = new MeshDefinition();
		PartDefinition root = mesh.getRoot();
		PartDefinition brittleStar = root.addOrReplaceChild(BRITTLE_STAR, CubeListBuilder.create(),
			PartPose.offset(0.0F, 24.0F, 0.0F));
		PartDefinition disc = brittleStar.addOrReplaceChild(DISC, CubeListBuilder.create()
			.texOffs(0, 0).addBox(-4.0F, -2.0F, -3.0F, 7.0F, 2.0F, 7.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, -1.0F));
		PartDefinition discTop = disc.addOrReplaceChild(DISC_TOP, CubeListBuilder.create()
			.texOffs(28, 0).addBox(-2.5F, -1.0F, -1.5F, 4.0F, 1.0F, 4.0F, new CubeDeformation(0.0F)),
			PartPose.offset(-0.5F, -1.5F, 0.5F));
		PartDefinition arm1 = disc.addOrReplaceChild(ARM_1, CubeListBuilder.create()
			.texOffs(44, 0).addBox(-0.5F, -0.5F, -6.0F, 1.0F, 1.0F, 6.0F, new CubeDeformation(0.0F)),
			PartPose.offset(-0.5F, -0.5F, -3.0F));
		PartDefinition arm12 = arm1.addOrReplaceChild(ARM_1_2, CubeListBuilder.create()
			.texOffs(42, 21).addBox(-0.5F, -0.5F, -5.0F, 1.0F, 1.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, -6.0F, 0.0F, -0.2094F, 0.0F));
		PartDefinition arm13 = arm12.addOrReplaceChild(ARM_1_3, CubeListBuilder.create()
			.texOffs(28, 5).addBox(-0.5F, -0.5F, -6.0F, 1.0F, 1.0F, 6.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, -5.0F, 0.0F, -0.2094F, 0.0F));
		PartDefinition arm14 = arm13.addOrReplaceChild(ARM_1_4, CubeListBuilder.create()
			.texOffs(0, 23).addBox(-0.5F, -0.5F, -5.0F, 1.0F, 1.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, -6.0F, 0.0F, -0.2094F, 0.0F));
		PartDefinition arm2 = disc.addOrReplaceChild(ARM_2, CubeListBuilder.create()
			.texOffs(42, 7).addBox(-1.0F, -0.5F, -6.0F, 1.0F, 1.0F, 6.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(3.0F, -0.5F, -0.5F, 0.0F, -1.2566F, 0.0F));
		PartDefinition arm22 = arm2.addOrReplaceChild(ARM_2_2, CubeListBuilder.create()
			.texOffs(12, 23).addBox(-1.0F, -0.5F, -5.0F, 1.0F, 1.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, -6.0F, 0.0F, -0.2094F, 0.0F));
		PartDefinition arm23 = arm22.addOrReplaceChild(ARM_2_3, CubeListBuilder.create()
			.texOffs(0, 9).addBox(-1.0F, -0.5F, -6.0F, 1.0F, 1.0F, 6.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, -5.0F, 0.0F, -0.2094F, 0.0F));
		PartDefinition arm24 = arm23.addOrReplaceChild(ARM_2_4, CubeListBuilder.create()
			.texOffs(24, 26).addBox(-1.0F, -0.5F, -5.0F, 1.0F, 1.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, -6.0F, 0.0F, -0.2094F, 0.0F));
		PartDefinition arm3 = disc.addOrReplaceChild(ARM_3, CubeListBuilder.create()
			.texOffs(14, 9).addBox(-0.5F, -0.5F, -6.0F, 1.0F, 1.0F, 6.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(1.5F, -0.5F, 3.5F, 3.1416F, -0.6283F, 3.1416F));
		PartDefinition arm32 = arm3.addOrReplaceChild(ARM_3_2, CubeListBuilder.create()
			.texOffs(0, 29).addBox(-0.5F, -0.5F, -5.0F, 1.0F, 1.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, -6.0F, 0.0F, -0.2094F, 0.0F));
		PartDefinition arm33 = arm32.addOrReplaceChild(ARM_3_3, CubeListBuilder.create()
			.texOffs(28, 12).addBox(-0.5F, -0.5F, -6.0F, 1.0F, 1.0F, 6.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, -5.0F, 0.0F, -0.2094F, 0.0F));
		PartDefinition arm34 = arm33.addOrReplaceChild(ARM_3_4, CubeListBuilder.create()
			.texOffs(12, 29).addBox(-0.5F, -0.5F, -5.0F, 1.0F, 1.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, -6.0F, 0.0F, -0.2094F, 0.0F));
		PartDefinition arm4 = disc.addOrReplaceChild(ARM_4, CubeListBuilder.create()
			.texOffs(42, 14).addBox(-0.5F, -0.5F, -6.0F, 1.0F, 1.0F, 6.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(-2.5F, -0.5F, 3.5F, -3.1416F, 0.6283F, 3.1416F));
		PartDefinition arm42 = arm4.addOrReplaceChild(ARM_4_2, CubeListBuilder.create()
			.texOffs(36, 27).addBox(-0.5F, -0.5F, -5.0F, 1.0F, 1.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, -6.0F, 0.0F, -0.2094F, 0.0F));
		PartDefinition arm43 = arm42.addOrReplaceChild(ARM_4_3, CubeListBuilder.create()
			.texOffs(0, 16).addBox(-0.5F, -0.5F, -6.0F, 1.0F, 1.0F, 6.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, -5.0F, 0.0F, -0.2094F, 0.0F));
		PartDefinition arm44 = arm43.addOrReplaceChild(ARM_4_4, CubeListBuilder.create()
			.texOffs(24, 32).addBox(-0.5F, -0.5F, -5.0F, 1.0F, 1.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, -6.0F, 0.0F, -0.2094F, 0.0F));
		PartDefinition arm5 = disc.addOrReplaceChild(ARM_5, CubeListBuilder.create()
			.texOffs(14, 16).addBox(-1.0F, -0.5F, -6.0F, 1.0F, 1.0F, 6.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(-4.0F, -0.5F, -0.5F, 0.0F, 1.2566F, 0.0F));
		PartDefinition arm52 = arm5.addOrReplaceChild(ARM_5_2, CubeListBuilder.create()
			.texOffs(48, 27).addBox(-1.0F, -0.5F, -5.0F, 1.0F, 1.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, -6.0F, 0.0F, -0.2094F, 0.0F));
		PartDefinition arm53 = arm52.addOrReplaceChild(ARM_5_3, CubeListBuilder.create()
			.texOffs(28, 19).addBox(-1.0F, -0.5F, -6.0F, 1.0F, 1.0F, 6.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, -5.0F, 0.0F, -0.2094F, 0.0F));
		PartDefinition arm54 = arm53.addOrReplaceChild(ARM_5_4, CubeListBuilder.create()
			.texOffs(0, 35).addBox(-1.0F, -0.5F, -5.0F, 1.0F, 1.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, -6.0F, 0.0F, -0.2094F, 0.0F));
		return LayerDefinition.create(mesh, 64, 64);
	}
}
