package com.abyssia.client.entity.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Generated by tools/bbmodel-generator (frilled_shark.bbmodel, template eel, seed 1).
 * Texture 64x64 UV (64x64 px): textures/entity/frilled_shark.png, glow mask textures/entity/frilled_shark_glow.png.
 * Regenerate with: node tools/bbmodel-generator/cli.js frilled_shark
 */
public final class FrilledSharkGeometry
{
	public static final String FRILLED_SHARK = "frilled_shark";
	public static final String BODY = "body";
	public static final String BODY_2 = "body_2";
	public static final String BODY_3 = "body_3";
	public static final String BODY_4 = "body_4";
	public static final String BODY_5 = "body_5";
	public static final String BODY_6 = "body_6";
	public static final String BODY_7 = "body_7";
	public static final String HEAD = "head";
	public static final String MOUTH = "mouth";
	public static final String LOWER_TEETH = "lower_teeth";
	public static final String UPPER_TEETH = "upper_teeth";
	public static final String RIGHT_EYE = "right_eye";
	public static final String LEFT_EYE = "left_eye";
	public static final String RIGHT_GILLS = "right_gills";
	public static final String LEFT_GILLS = "left_gills";
	public static final String RIGHT_FIN = "right_fin";
	public static final String LEFT_FIN = "left_fin";
	public static final String RIGHT_PELVIC_FIN = "right_pelvic_fin";
	public static final String LEFT_PELVIC_FIN = "left_pelvic_fin";
	public static final String DORSAL_FIN = "dorsal_fin";
	public static final String DORSAL_FIN_2 = "dorsal_fin_2";
	public static final String ANAL_FIN = "anal_fin";
	public static final String ANAL_FIN_2 = "anal_fin_2";
	public static final String TAIL_FIN = "tail_fin";

	private FrilledSharkGeometry()
	{
	}

	public static LayerDefinition create()
	{
		MeshDefinition mesh = new MeshDefinition();
		PartDefinition root = mesh.getRoot();
		PartDefinition frilledShark = root.addOrReplaceChild(FRILLED_SHARK, CubeListBuilder.create(),
			PartPose.offset(0.0F, 24.0F, 0.0F));
		PartDefinition body = frilledShark.addOrReplaceChild(BODY, CubeListBuilder.create()
			.texOffs(24, 9).addBox(-2.5F, -3.0F, 0.0F, 5.0F, 5.0F, 6.0F, new CubeDeformation(0.0F))
			.texOffs(0, 31).addBox(-2.5F, 2.0F, 0.0F, 5.0F, 1.0F, 2.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -3.2214F, -17.0F));
		PartDefinition body2 = body.addOrReplaceChild(BODY_2, CubeListBuilder.create()
			.texOffs(0, 0).addBox(-2.5F, -3.0F, -1.0F, 5.0F, 5.0F, 7.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 6.0F));
		PartDefinition body3 = body2.addOrReplaceChild(BODY_3, CubeListBuilder.create()
			.texOffs(0, 12).addBox(-2.0F, -2.0F, -1.0F, 4.0F, 4.0F, 7.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 6.0F));
		PartDefinition body4 = body3.addOrReplaceChild(BODY_4, CubeListBuilder.create()
			.texOffs(22, 20).addBox(-2.0F, -2.0F, -1.0F, 4.0F, 4.0F, 7.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 6.0F));
		PartDefinition body5 = body4.addOrReplaceChild(BODY_5, CubeListBuilder.create()
			.texOffs(46, 9).addBox(-1.5F, -2.0F, -1.0F, 3.0F, 3.0F, 6.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 6.0F));
		PartDefinition body6 = body5.addOrReplaceChild(BODY_6, CubeListBuilder.create()
			.texOffs(44, 20).addBox(-1.5F, -2.0F, -1.0F, 3.0F, 3.0F, 7.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 5.0F));
		PartDefinition body7 = body6.addOrReplaceChild(BODY_7, CubeListBuilder.create()
			.texOffs(48, 0).addBox(-1.0F, -1.0F, -1.0F, 2.0F, 2.0F, 6.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 6.0F));
		PartDefinition tailFin = body7.addOrReplaceChild(TAIL_FIN, CubeListBuilder.create()
			.texOffs(44, 20).addBox(0.0F, -3.0F, -1.0F, 0.0F, 5.0F, 10.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 5.0F));
		PartDefinition dorsalFin2 = body6.addOrReplaceChild(DORSAL_FIN_2, CubeListBuilder.create()
			.texOffs(26, 25).addBox(0.0F, -2.0F, 0.0F, 0.0F, 3.0F, 6.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -2.0F, 0.0F));
		PartDefinition analFin2 = body6.addOrReplaceChild(ANAL_FIN_2, CubeListBuilder.create()
			.texOffs(14, 25).addBox(0.0F, -1.0F, 0.0F, 0.0F, 3.0F, 6.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 1.0F, 0.0F));
		PartDefinition rightPelvicFin = body5.addOrReplaceChild(RIGHT_PELVIC_FIN, CubeListBuilder.create()
			.texOffs(6, 57).addBox(0.0F, -1.0F, -1.0F, 0.0F, 3.0F, 3.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(-1.0F, 1.0F, 1.0F, 0.3491F, -0.3491F, 0.0F));
		PartDefinition leftPelvicFin = body5.addOrReplaceChild(LEFT_PELVIC_FIN, CubeListBuilder.create()
			.texOffs(0, 57).addBox(0.0F, -1.0F, -1.0F, 0.0F, 3.0F, 3.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(1.0F, 1.0F, 1.0F, 0.3491F, 0.3491F, 0.0F));
		PartDefinition dorsalFin = body5.addOrReplaceChild(DORSAL_FIN, CubeListBuilder.create()
			.texOffs(28, 29).addBox(0.0F, -2.0F, 0.0F, 0.0F, 3.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -2.0F, 0.0F));
		PartDefinition analFin = body5.addOrReplaceChild(ANAL_FIN, CubeListBuilder.create()
			.texOffs(18, 29).addBox(0.0F, -1.0F, 0.0F, 0.0F, 3.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 1.0F, 0.0F));
		PartDefinition head = body.addOrReplaceChild(HEAD, CubeListBuilder.create()
			.texOffs(24, 0).addBox(-2.5F, -2.0F, -6.0F, 5.0F, 2.0F, 7.0F, new CubeDeformation(0.0F))
			.texOffs(0, 35).addBox(-1.5F, -3.0F, -5.0F, 3.0F, 1.0F, 6.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 0.0F));
		PartDefinition mouth = head.addOrReplaceChild(MOUTH, CubeListBuilder.create()
			.texOffs(0, 23).addBox(-2.5F, 0.0F, -5.0F, 5.0F, 2.0F, 6.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, -1.0F, 0.0873F, 0.0F, 0.0F));
		PartDefinition lowerTeeth = mouth.addOrReplaceChild(LOWER_TEETH, CubeListBuilder.create()
			.texOffs(62, 18).addBox(0.5F, -1.0F, 0.5F, 1.0F, 1.0F, 0.0F, new CubeDeformation(0.0F))
			.texOffs(62, 19).addBox(-0.5F, -1.0F, 0.5F, 1.0F, 1.0F, 0.0F, new CubeDeformation(0.0F))
			.texOffs(22, 12).addBox(-1.5F, -1.0F, 0.5F, 1.0F, 1.0F, 0.0F, new CubeDeformation(0.0F))
			.texOffs(22, 13).addBox(0.5F, -1.0F, 2.5F, 1.0F, 1.0F, 0.0F, new CubeDeformation(0.0F))
			.texOffs(22, 14).addBox(-0.5F, -1.0F, 2.5F, 1.0F, 1.0F, 0.0F, new CubeDeformation(0.0F))
			.texOffs(22, 15).addBox(-1.5F, -1.0F, 2.5F, 1.0F, 1.0F, 0.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, -5.0F));
		PartDefinition upperTeeth = head.addOrReplaceChild(UPPER_TEETH, CubeListBuilder.create()
			.texOffs(22, 16).addBox(0.0F, 0.0F, 0.5F, 1.0F, 1.0F, 0.0F, new CubeDeformation(0.0F))
			.texOffs(22, 17).addBox(-1.0F, 0.0F, 0.5F, 1.0F, 1.0F, 0.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, -6.0F));
		PartDefinition rightEye = head.addOrReplaceChild(RIGHT_EYE, CubeListBuilder.create()
			.texOffs(12, 56).addBox(-0.5F, -0.5F, -0.5F, 1.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offset(-2.5F, -2.5F, -4.5F));
		PartDefinition leftEye = head.addOrReplaceChild(LEFT_EYE, CubeListBuilder.create()
			.texOffs(12, 54).addBox(-0.5F, -0.5F, -0.5F, 1.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offset(2.5F, -2.5F, -4.5F));
		PartDefinition rightGills = body.addOrReplaceChild(RIGHT_GILLS, CubeListBuilder.create()
			.texOffs(4, 54).addBox(-2.0F, -3.0F, 0.5F, 2.0F, 6.0F, 0.0F, new CubeDeformation(0.0F))
			.texOffs(8, 42).addBox(-2.0F, -3.0F, 1.5F, 2.0F, 6.0F, 0.0F, new CubeDeformation(0.0F))
			.texOffs(8, 48).addBox(-2.0F, -3.0F, 2.5F, 2.0F, 6.0F, 0.0F, new CubeDeformation(0.0F))
			.texOffs(8, 54).addBox(-2.0F, -3.0F, 3.5F, 2.0F, 6.0F, 0.0F, new CubeDeformation(0.0F))
			.texOffs(12, 42).addBox(-2.0F, -3.0F, 4.5F, 2.0F, 6.0F, 0.0F, new CubeDeformation(0.0F))
			.texOffs(12, 48).addBox(-2.0F, -3.0F, 5.5F, 2.0F, 6.0F, 0.0F, new CubeDeformation(0.0F)),
			PartPose.offset(-2.5F, 0.0F, 0.0F));
		PartDefinition leftGills = body.addOrReplaceChild(LEFT_GILLS, CubeListBuilder.create()
			.texOffs(38, 31).addBox(0.0F, -3.0F, 0.5F, 2.0F, 6.0F, 0.0F, new CubeDeformation(0.0F))
			.texOffs(0, 42).addBox(0.0F, -3.0F, 1.5F, 2.0F, 6.0F, 0.0F, new CubeDeformation(0.0F))
			.texOffs(0, 48).addBox(0.0F, -3.0F, 2.5F, 2.0F, 6.0F, 0.0F, new CubeDeformation(0.0F))
			.texOffs(0, 54).addBox(0.0F, -3.0F, 3.5F, 2.0F, 6.0F, 0.0F, new CubeDeformation(0.0F))
			.texOffs(4, 42).addBox(0.0F, -3.0F, 4.5F, 2.0F, 6.0F, 0.0F, new CubeDeformation(0.0F))
			.texOffs(4, 48).addBox(0.0F, -3.0F, 5.5F, 2.0F, 6.0F, 0.0F, new CubeDeformation(0.0F)),
			PartPose.offset(2.5F, 0.0F, 0.0F));
		PartDefinition rightFin = body.addOrReplaceChild(RIGHT_FIN, CubeListBuilder.create()
			.texOffs(54, 14).addBox(0.0F, -1.0F, -1.0F, 0.0F, 2.0F, 4.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(-2.5F, 0.0F, 7.0F, 0.0F, -0.7854F, -0.2618F));
		PartDefinition leftFin = body.addOrReplaceChild(LEFT_FIN, CubeListBuilder.create()
			.texOffs(46, 14).addBox(0.0F, -1.0F, -1.0F, 0.0F, 2.0F, 4.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(2.5F, 0.0F, 7.0F, 0.0F, 0.7854F, 0.2618F));
		return LayerDefinition.create(mesh, 64, 64);
	}
}
