package com.abyssia.client.entity.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Generated by tools/bbmodel-generator (ohara_shrimp.bbmodel, template crustacean, seed 1).
 * Texture 64x64 UV (64x64 px): textures/entity/ohara_shrimp.png, glow mask textures/entity/ohara_shrimp_glow.png.
 * Regenerate with: node tools/bbmodel-generator/cli.js ohara_shrimp
 */
public final class OharaShrimpGeometry
{
	public static final String OHARA_SHRIMP = "ohara_shrimp";
	public static final String BODY = "body";
	public static final String RIGHT_EYE = "right_eye";
	public static final String LEFT_EYE = "left_eye";
	public static final String ROSTRUM = "rostrum";
	public static final String RIGHT_ANTENNA = "right_antenna";
	public static final String RIGHT_ANTENNA_2 = "right_antenna_2";
	public static final String RIGHT_ANTENNA_3 = "right_antenna_3";
	public static final String LEFT_ANTENNA = "left_antenna";
	public static final String LEFT_ANTENNA_2 = "left_antenna_2";
	public static final String LEFT_ANTENNA_3 = "left_antenna_3";
	public static final String RIGHT_LEG_1 = "right_leg_1";
	public static final String RIGHT_LEG_1_FOOT = "right_leg_1_foot";
	public static final String LEFT_LEG_1 = "left_leg_1";
	public static final String LEFT_LEG_1_FOOT = "left_leg_1_foot";
	public static final String RIGHT_LEG_2 = "right_leg_2";
	public static final String RIGHT_LEG_2_FOOT = "right_leg_2_foot";
	public static final String LEFT_LEG_2 = "left_leg_2";
	public static final String LEFT_LEG_2_FOOT = "left_leg_2_foot";
	public static final String RIGHT_LEG_3 = "right_leg_3";
	public static final String RIGHT_LEG_3_FOOT = "right_leg_3_foot";
	public static final String LEFT_LEG_3 = "left_leg_3";
	public static final String LEFT_LEG_3_FOOT = "left_leg_3_foot";
	public static final String RIGHT_LEG_4 = "right_leg_4";
	public static final String RIGHT_LEG_4_FOOT = "right_leg_4_foot";
	public static final String LEFT_LEG_4 = "left_leg_4";
	public static final String LEFT_LEG_4_FOOT = "left_leg_4_foot";
	public static final String RIGHT_LEG_5 = "right_leg_5";
	public static final String RIGHT_LEG_5_FOOT = "right_leg_5_foot";
	public static final String LEFT_LEG_5 = "left_leg_5";
	public static final String LEFT_LEG_5_FOOT = "left_leg_5_foot";
	public static final String ABDOMEN = "abdomen";
	public static final String ABDOMEN_2 = "abdomen_2";
	public static final String ABDOMEN_3 = "abdomen_3";
	public static final String ABDOMEN_4 = "abdomen_4";
	public static final String ABDOMEN_5 = "abdomen_5";
	public static final String TAIL_FAN = "tail_fan";
	public static final String RIGHT_UROPOD = "right_uropod";
	public static final String LEFT_UROPOD = "left_uropod";

	private OharaShrimpGeometry()
	{
	}

	public static LayerDefinition create()
	{
		MeshDefinition mesh = new MeshDefinition();
		PartDefinition root = mesh.getRoot();
		PartDefinition oharaShrimp = root.addOrReplaceChild(OHARA_SHRIMP, CubeListBuilder.create(),
			PartPose.offset(0.0F, 24.0F, 0.0F));
		PartDefinition body = oharaShrimp.addOrReplaceChild(BODY, CubeListBuilder.create()
			.texOffs(0, 10).addBox(-2.0F, -1.0F, -3.0F, 4.0F, 3.0F, 6.0F, new CubeDeformation(0.0F))
			.texOffs(20, 10).addBox(-2.0F, -2.0F, -3.0F, 4.0F, 1.0F, 6.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -6.8072F, -6.0F));
		PartDefinition rightEye = body.addOrReplaceChild(RIGHT_EYE, CubeListBuilder.create()
			.texOffs(58, 34).addBox(-0.5F, -0.5F, -1.0F, 1.0F, 1.0F, 2.0F, new CubeDeformation(0.0F))
			.texOffs(60, 32).addBox(-0.5F, -0.5F, -1.5F, 1.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(-1.5F, -1.0F, -3.0F, 0.0F, 0.3491F, 0.0F));
		PartDefinition leftEye = body.addOrReplaceChild(LEFT_EYE, CubeListBuilder.create()
			.texOffs(58, 16).addBox(-0.5F, -0.5F, -1.0F, 1.0F, 1.0F, 2.0F, new CubeDeformation(0.0F))
			.texOffs(34, 26).addBox(-0.5F, -0.5F, -1.5F, 1.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(1.5F, -1.0F, -3.0F, 0.0F, -0.3491F, 0.0F));
		PartDefinition rostrum = body.addOrReplaceChild(ROSTRUM, CubeListBuilder.create()
			.texOffs(40, 0).addBox(-0.5F, 0.0F, -8.0F, 1.0F, 1.0F, 9.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, -1.0F, -3.0F, -0.1047F, 0.0F, 0.0F));
		PartDefinition rightAntenna = body.addOrReplaceChild(RIGHT_ANTENNA, CubeListBuilder.create()
			.texOffs(20, 0).addBox(-0.5F, -0.5F, -9.0F, 1.0F, 1.0F, 9.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(-0.5F, -0.5F, -2.0F, -0.3491F, 0.6981F, 0.0F));
		PartDefinition rightAntenna2 = rightAntenna.addOrReplaceChild(RIGHT_ANTENNA_2, CubeListBuilder.create()
			.texOffs(0, 19).addBox(-0.5F, -0.5F, -8.0F, 1.0F, 1.0F, 8.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, -9.0F, 0.1396F, 1.0472F, 0.0F));
		PartDefinition rightAntenna3 = rightAntenna2.addOrReplaceChild(RIGHT_ANTENNA_3, CubeListBuilder.create()
			.texOffs(38, 19).addBox(-0.5F, -0.5F, -8.0F, 1.0F, 1.0F, 8.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, -8.0F, 0.1396F, 1.0472F, 0.0F));
		PartDefinition leftAntenna = body.addOrReplaceChild(LEFT_ANTENNA, CubeListBuilder.create()
			.texOffs(0, 0).addBox(-0.5F, -0.5F, -9.0F, 1.0F, 1.0F, 9.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.5F, -0.5F, -2.0F, -0.3491F, -0.6981F, 0.0F));
		PartDefinition leftAntenna2 = leftAntenna.addOrReplaceChild(LEFT_ANTENNA_2, CubeListBuilder.create()
			.texOffs(40, 10).addBox(-0.5F, -0.5F, -8.0F, 1.0F, 1.0F, 8.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, -9.0F, 0.1396F, -1.0472F, 0.0F));
		PartDefinition leftAntenna3 = leftAntenna2.addOrReplaceChild(LEFT_ANTENNA_3, CubeListBuilder.create()
			.texOffs(20, 17).addBox(-0.5F, -0.5F, -8.0F, 1.0F, 1.0F, 8.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, -8.0F, 0.1396F, -1.0472F, 0.0F));
		PartDefinition rightLeg1 = body.addOrReplaceChild(RIGHT_LEG_1, CubeListBuilder.create(),
			PartPose.offset(-1.0F, 1.0F, -2.0F));
		rightLeg1.addOrReplaceChild("right_leg_1_r1", CubeListBuilder.create()
			.texOffs(4, 36).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 3.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, -0.1874F, -0.3964F, 0.4566F));
		PartDefinition rightLeg1Foot = rightLeg1.addOrReplaceChild(RIGHT_LEG_1_FOOT, CubeListBuilder.create(),
			PartPose.offset(-1.1059F, 2.7406F, -0.5157F));
		rightLeg1Foot.addOrReplaceChild("right_leg_1_foot_r1", CubeListBuilder.create()
			.texOffs(8, 36).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 3.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, -0.0406F, -0.4346F, 0.0962F));
		PartDefinition leftLeg1 = body.addOrReplaceChild(LEFT_LEG_1, CubeListBuilder.create(),
			PartPose.offset(1.0F, 1.0F, -2.0F));
		leftLeg1.addOrReplaceChild("left_leg_1_r1", CubeListBuilder.create()
			.texOffs(56, 24).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 3.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, -0.1874F, 0.3964F, -0.4566F));
		PartDefinition leftLeg1Foot = leftLeg1.addOrReplaceChild(LEFT_LEG_1_FOOT, CubeListBuilder.create(),
			PartPose.offset(1.1059F, 2.7406F, -0.5157F));
		leftLeg1Foot.addOrReplaceChild("left_leg_1_foot_r1", CubeListBuilder.create()
			.texOffs(56, 19).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 3.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, -0.0406F, 0.4346F, -0.0962F));
		PartDefinition rightLeg2 = body.addOrReplaceChild(RIGHT_LEG_2, CubeListBuilder.create(),
			PartPose.offset(-1.0F, 1.0F, -1.0F));
		rightLeg2.addOrReplaceChild("right_leg_2_r1", CubeListBuilder.create()
			.texOffs(12, 36).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 3.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, -0.0899F, -0.199F, 0.4279F));
		PartDefinition rightLeg2Foot = rightLeg2.addOrReplaceChild(RIGHT_LEG_2_FOOT, CubeListBuilder.create(),
			PartPose.offset(-1.1913F, 2.7406F, -0.2641F));
		rightLeg2Foot.addOrReplaceChild("right_leg_2_foot_r1", CubeListBuilder.create()
			.texOffs(32, 35).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 3.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, -0.0193F, -0.2173F, 0.0894F));
		PartDefinition leftLeg2 = body.addOrReplaceChild(LEFT_LEG_2, CubeListBuilder.create(),
			PartPose.offset(1.0F, 1.0F, -1.0F));
		leftLeg2.addOrReplaceChild("left_leg_2_r1", CubeListBuilder.create()
			.texOffs(60, 24).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 3.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, -0.0899F, 0.199F, -0.4279F));
		PartDefinition leftLeg2Foot = leftLeg2.addOrReplaceChild(LEFT_LEG_2_FOOT, CubeListBuilder.create(),
			PartPose.offset(1.1913F, 2.7406F, -0.2641F));
		leftLeg2Foot.addOrReplaceChild("left_leg_2_foot_r1", CubeListBuilder.create()
			.texOffs(60, 28).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 3.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, -0.0193F, 0.2173F, -0.0894F));
		PartDefinition rightLeg3 = body.addOrReplaceChild(RIGHT_LEG_3, CubeListBuilder.create(),
			PartPose.offset(-1.0F, 1.0F, 0.0F));
		rightLeg3.addOrReplaceChild("right_leg_3_r1", CubeListBuilder.create()
			.texOffs(36, 35).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 3.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.4189F));
		PartDefinition rightLeg3Foot = rightLeg3.addOrReplaceChild(RIGHT_LEG_3_FOOT, CubeListBuilder.create(),
			PartPose.offset(-1.2202F, 2.7406F, 0.0F));
		rightLeg3Foot.addOrReplaceChild("right_leg_3_foot_r1", CubeListBuilder.create()
			.texOffs(40, 35).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 3.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0873F));
		PartDefinition leftLeg3 = body.addOrReplaceChild(LEFT_LEG_3, CubeListBuilder.create(),
			PartPose.offset(1.0F, 1.0F, 0.0F));
		leftLeg3.addOrReplaceChild("left_leg_3_r1", CubeListBuilder.create()
			.texOffs(58, 37).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 3.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, -0.4189F));
		PartDefinition leftLeg3Foot = leftLeg3.addOrReplaceChild(LEFT_LEG_3_FOOT, CubeListBuilder.create(),
			PartPose.offset(1.2202F, 2.7406F, 0.0F));
		leftLeg3Foot.addOrReplaceChild("left_leg_3_foot_r1", CubeListBuilder.create()
			.texOffs(16, 34).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 3.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, -0.0873F));
		PartDefinition rightLeg4 = body.addOrReplaceChild(RIGHT_LEG_4, CubeListBuilder.create(),
			PartPose.offset(-1.0F, 1.0F, 1.0F));
		rightLeg4.addOrReplaceChild("right_leg_4_r1", CubeListBuilder.create()
			.texOffs(44, 35).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 3.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0899F, 0.199F, 0.4279F));
		PartDefinition rightLeg4Foot = rightLeg4.addOrReplaceChild(RIGHT_LEG_4_FOOT, CubeListBuilder.create(),
			PartPose.offset(-1.1913F, 2.7406F, 0.2641F));
		rightLeg4Foot.addOrReplaceChild("right_leg_4_foot_r1", CubeListBuilder.create()
			.texOffs(16, 38).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 3.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0193F, 0.2173F, 0.0894F));
		PartDefinition leftLeg4 = body.addOrReplaceChild(LEFT_LEG_4, CubeListBuilder.create(),
			PartPose.offset(1.0F, 1.0F, 1.0F));
		leftLeg4.addOrReplaceChild("left_leg_4_r1", CubeListBuilder.create()
			.texOffs(20, 34).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 3.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0899F, -0.199F, -0.4279F));
		PartDefinition leftLeg4Foot = leftLeg4.addOrReplaceChild(LEFT_LEG_4_FOOT, CubeListBuilder.create(),
			PartPose.offset(1.1913F, 2.7406F, 0.2641F));
		leftLeg4Foot.addOrReplaceChild("left_leg_4_foot_r1", CubeListBuilder.create()
			.texOffs(24, 34).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 3.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0193F, -0.2173F, -0.0894F));
		PartDefinition rightLeg5 = body.addOrReplaceChild(RIGHT_LEG_5, CubeListBuilder.create(),
			PartPose.offset(-1.0F, 1.0F, 2.0F));
		rightLeg5.addOrReplaceChild("right_leg_5_r1", CubeListBuilder.create()
			.texOffs(20, 38).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 3.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.1874F, 0.3964F, 0.4566F));
		PartDefinition rightLeg5Foot = rightLeg5.addOrReplaceChild(RIGHT_LEG_5_FOOT, CubeListBuilder.create(),
			PartPose.offset(-1.1059F, 2.7406F, 0.5157F));
		rightLeg5Foot.addOrReplaceChild("right_leg_5_foot_r1", CubeListBuilder.create()
			.texOffs(24, 38).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 3.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0406F, 0.4346F, 0.0962F));
		PartDefinition leftLeg5 = body.addOrReplaceChild(LEFT_LEG_5, CubeListBuilder.create(),
			PartPose.offset(1.0F, 1.0F, 2.0F));
		leftLeg5.addOrReplaceChild("left_leg_5_r1", CubeListBuilder.create()
			.texOffs(28, 34).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 3.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.1874F, -0.3964F, -0.4566F));
		PartDefinition leftLeg5Foot = leftLeg5.addOrReplaceChild(LEFT_LEG_5_FOOT, CubeListBuilder.create(),
			PartPose.offset(1.1059F, 2.7406F, 0.5157F));
		leftLeg5Foot.addOrReplaceChild("left_leg_5_foot_r1", CubeListBuilder.create()
			.texOffs(0, 36).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 3.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0406F, -0.4346F, -0.0962F));
		PartDefinition abdomen = body.addOrReplaceChild(ABDOMEN, CubeListBuilder.create()
			.texOffs(18, 26).addBox(-2.0F, -2.0F, 0.0F, 4.0F, 4.0F, 4.0F, new CubeDeformation(0.0F))
			.texOffs(58, 13).addBox(-1.5F, 1.0F, 1.0F, 3.0F, 3.0F, 0.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 2.0F, -0.1396F, 0.0F, 0.0F));
		PartDefinition abdomen2 = abdomen.addOrReplaceChild(ABDOMEN_2, CubeListBuilder.create()
			.texOffs(0, 28).addBox(-2.0F, -2.0F, 0.0F, 4.0F, 4.0F, 4.0F, new CubeDeformation(0.0F))
			.texOffs(58, 10).addBox(-1.5F, 1.0F, 1.0F, 3.0F, 3.0F, 0.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 3.0F, -0.1396F, 0.0F, 0.0F));
		PartDefinition abdomen3 = abdomen2.addOrReplaceChild(ABDOMEN_3, CubeListBuilder.create()
			.texOffs(48, 28).addBox(-1.5F, -1.5F, 0.0F, 3.0F, 3.0F, 3.0F, new CubeDeformation(0.0F))
			.texOffs(28, 38).addBox(-1.0F, 0.5F, 1.0F, 2.0F, 3.0F, 0.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, -0.5F, 3.0F, -0.1396F, 0.0F, 0.0F));
		PartDefinition abdomen4 = abdomen3.addOrReplaceChild(ABDOMEN_4, CubeListBuilder.create()
			.texOffs(34, 28).addBox(-1.5F, -1.5F, 0.0F, 3.0F, 3.0F, 4.0F, new CubeDeformation(0.0F))
			.texOffs(0, 40).addBox(-1.0F, 0.5F, 1.0F, 2.0F, 3.0F, 0.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 2.0F, -0.1396F, 0.0F, 0.0F));
		PartDefinition abdomen5 = abdomen4.addOrReplaceChild(ABDOMEN_5, CubeListBuilder.create()
			.texOffs(48, 34).addBox(-1.0F, -1.0F, 0.0F, 2.0F, 2.0F, 3.0F, new CubeDeformation(0.0F))
			.texOffs(16, 28).addBox(-0.5F, 0.0F, 1.0F, 1.0F, 3.0F, 0.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, -0.5F, 3.0F, -0.1396F, 0.0F, 0.0F));
		PartDefinition tailFan = abdomen5.addOrReplaceChild(TAIL_FAN, CubeListBuilder.create()
			.texOffs(55, 19).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 0.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 2.0F, -0.0698F, 0.0F, 0.0F));
		PartDefinition rightUropod = tailFan.addOrReplaceChild(RIGHT_UROPOD, CubeListBuilder.create()
			.texOffs(55, 5).addBox(-2.0F, 0.0F, -1.0F, 2.0F, 0.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(-1.0F, 0.0F, 0.0F, 0.0F, -0.384F, 0.0F));
		PartDefinition leftUropod = tailFan.addOrReplaceChild(LEFT_UROPOD, CubeListBuilder.create()
			.texOffs(55, 0).addBox(0.0F, 0.0F, -1.0F, 2.0F, 0.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(1.0F, 0.0F, 0.0F, 0.0F, 0.384F, 0.0F));
		return LayerDefinition.create(mesh, 64, 64);
	}
}
