package com.abyssia.client.entity.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Generated by tools/bbmodel-generator (sablefish.bbmodel, template fish, seed 1).
 * Texture 64x64 UV (64x64 px): textures/entity/sablefish.png.
 * Regenerate with: node tools/bbmodel-generator/cli.js sablefish
 */
public final class SablefishGeometry
{
	public static final String SABLEFISH = "sablefish";
	public static final String BODY = "body";
	public static final String HEAD = "head";
	public static final String SNOUT = "snout";
	public static final String MOUTH = "mouth";
	public static final String RIGHT_EYE = "right_eye";
	public static final String LEFT_EYE = "left_eye";
	public static final String RIGHT_FIN = "right_fin";
	public static final String LEFT_FIN = "left_fin";
	public static final String RIGHT_PELVIC_FIN = "right_pelvic_fin";
	public static final String LEFT_PELVIC_FIN = "left_pelvic_fin";
	public static final String DORSAL_FIN = "dorsal_fin";
	public static final String DORSAL_FIN_2 = "dorsal_fin_2";
	public static final String ANAL_FIN = "anal_fin";
	public static final String TAIL = "tail";
	public static final String TAIL_2 = "tail_2";
	public static final String TAIL_FIN = "tail_fin";

	private SablefishGeometry()
	{
	}

	public static LayerDefinition create()
	{
		MeshDefinition mesh = new MeshDefinition();
		PartDefinition root = mesh.getRoot();
		PartDefinition sablefish = root.addOrReplaceChild(SABLEFISH, CubeListBuilder.create(),
			PartPose.offset(0.0F, 24.0F, 0.0F));
		PartDefinition body = sablefish.addOrReplaceChild(BODY, CubeListBuilder.create()
			.texOffs(0, 0).addBox(-2.0F, -2.0F, -1.0F, 4.0F, 3.0F, 14.0F, new CubeDeformation(0.0F))
			.texOffs(30, 17).addBox(-1.0F, -3.0F, -1.0F, 2.0F, 1.0F, 13.0F, new CubeDeformation(0.0F))
			.texOffs(0, 17).addBox(-1.0F, 1.0F, -1.0F, 2.0F, 1.0F, 13.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -4.0F, -7.0F));
		PartDefinition head = body.addOrReplaceChild(HEAD, CubeListBuilder.create()
			.texOffs(36, 0).addBox(-2.0F, -2.0F, -5.0F, 4.0F, 3.0F, 5.0F, new CubeDeformation(0.0F))
			.texOffs(54, 5).addBox(-1.0F, -3.0F, -4.0F, 2.0F, 1.0F, 3.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 0.0F));
		PartDefinition snout = head.addOrReplaceChild(SNOUT, CubeListBuilder.create()
			.texOffs(0, 50).addBox(-1.0F, -1.0F, -1.0F, 2.0F, 2.0F, 2.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -1.0F, -5.0F));
		PartDefinition mouth = head.addOrReplaceChild(MOUTH, CubeListBuilder.create()
			.texOffs(36, 8).addBox(-1.5F, 0.0F, -4.0F, 3.0F, 1.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 1.0F, -1.0F));
		PartDefinition rightEye = head.addOrReplaceChild(RIGHT_EYE, CubeListBuilder.create()
			.texOffs(0, 46).addBox(-1.0F, -1.0F, -1.0F, 2.0F, 2.0F, 2.0F, new CubeDeformation(0.0F)),
			PartPose.offset(-1.8F, -2.0F, -3.0F));
		PartDefinition leftEye = head.addOrReplaceChild(LEFT_EYE, CubeListBuilder.create()
			.texOffs(0, 42).addBox(-1.0F, -1.0F, -1.0F, 2.0F, 2.0F, 2.0F, new CubeDeformation(0.0F)),
			PartPose.offset(1.8F, -2.0F, -3.0F));
		PartDefinition rightFin = body.addOrReplaceChild(RIGHT_FIN, CubeListBuilder.create()
			.texOffs(52, 11).addBox(0.0F, -1.0F, -1.0F, 0.0F, 2.0F, 4.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(-2.0F, 0.0F, 0.0F, 0.0F, -0.5236F, -0.2618F));
		PartDefinition leftFin = body.addOrReplaceChild(LEFT_FIN, CubeListBuilder.create()
			.texOffs(44, 10).addBox(0.0F, -1.0F, -1.0F, 0.0F, 2.0F, 4.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(2.0F, 0.0F, 0.0F, 0.0F, 0.5236F, 0.2618F));
		PartDefinition rightPelvicFin = body.addOrReplaceChild(RIGHT_PELVIC_FIN, CubeListBuilder.create()
			.texOffs(0, 56).addBox(0.0F, -1.0F, -1.0F, 0.0F, 2.0F, 3.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(-1.0F, 2.0F, 3.0F, 0.3491F, -0.3491F, 0.0F));
		PartDefinition leftPelvicFin = body.addOrReplaceChild(LEFT_PELVIC_FIN, CubeListBuilder.create()
			.texOffs(0, 54).addBox(0.0F, -1.0F, -1.0F, 0.0F, 2.0F, 3.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(1.0F, 2.0F, 3.0F, 0.3491F, 0.3491F, 0.0F));
		PartDefinition dorsalFin = body.addOrReplaceChild(DORSAL_FIN, CubeListBuilder.create()
			.texOffs(0, 34).addBox(0.0F, -3.0F, 0.0F, 0.0F, 4.0F, 4.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -3.0F, 1.0F));
		PartDefinition dorsalFin2 = body.addOrReplaceChild(DORSAL_FIN_2, CubeListBuilder.create()
			.texOffs(0, 51).addBox(0.0F, -2.0F, 0.0F, 0.0F, 3.0F, 3.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -3.0F, 7.0F));
		PartDefinition analFin = body.addOrReplaceChild(ANAL_FIN, CubeListBuilder.create()
			.texOffs(36, 10).addBox(0.0F, -1.0F, 0.0F, 0.0F, 3.0F, 4.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 2.0F, 7.0F));
		PartDefinition tail = body.addOrReplaceChild(TAIL, CubeListBuilder.create()
			.texOffs(0, 31).addBox(-1.5F, -2.0F, 0.0F, 3.0F, 3.0F, 4.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 12.0F));
		PartDefinition tail2 = tail.addOrReplaceChild(TAIL_2, CubeListBuilder.create()
			.texOffs(54, 0).addBox(-1.0F, -1.0F, 0.0F, 2.0F, 2.0F, 3.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 3.0F));
		PartDefinition tailFin = tail2.addOrReplaceChild(TAIL_FIN, CubeListBuilder.create()
			.texOffs(52, 5).addBox(0.0F, -3.0F, -1.0F, 0.0F, 6.0F, 4.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 3.0F));
		return LayerDefinition.create(mesh, 64, 64);
	}
}
