package com.abyssia.client.entity.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Generated by tools/bbmodel-generator (satsuma_tubeworm.bbmodel, template worm, seed 1).
 * Texture 64x64 UV (64x64 px): textures/entity/satsuma_tubeworm.png.
 * Regenerate with: node tools/bbmodel-generator/cli.js satsuma_tubeworm
 */
public final class SatsumaTubewormGeometry
{
	public static final String SATSUMA_TUBEWORM = "satsuma_tubeworm";
	public static final String BODY = "body";
	public static final String WORM_1 = "worm_1";
	public static final String WORM_1_2 = "worm_1_2";
	public static final String WORM_1_3 = "worm_1_3";
	public static final String PLUME_1 = "plume_1";
	public static final String WORM_2 = "worm_2";
	public static final String WORM_2_2 = "worm_2_2";
	public static final String WORM_2_3 = "worm_2_3";
	public static final String PLUME_2 = "plume_2";
	public static final String WORM_3 = "worm_3";
	public static final String WORM_3_2 = "worm_3_2";
	public static final String WORM_3_3 = "worm_3_3";
	public static final String PLUME_3 = "plume_3";
	public static final String WORM_4 = "worm_4";
	public static final String WORM_4_2 = "worm_4_2";
	public static final String WORM_4_3 = "worm_4_3";
	public static final String PLUME_4 = "plume_4";
	public static final String WORM_5 = "worm_5";
	public static final String WORM_5_2 = "worm_5_2";
	public static final String WORM_5_3 = "worm_5_3";
	public static final String PLUME_5 = "plume_5";
	public static final String WORM_6 = "worm_6";
	public static final String WORM_6_2 = "worm_6_2";
	public static final String WORM_6_3 = "worm_6_3";
	public static final String PLUME_6 = "plume_6";
	public static final String WORM_7 = "worm_7";
	public static final String WORM_7_2 = "worm_7_2";
	public static final String WORM_7_3 = "worm_7_3";
	public static final String PLUME_7 = "plume_7";
	public static final String WORM_8 = "worm_8";
	public static final String WORM_8_2 = "worm_8_2";
	public static final String WORM_8_3 = "worm_8_3";
	public static final String PLUME_8 = "plume_8";
	public static final String WORM_9 = "worm_9";
	public static final String WORM_9_2 = "worm_9_2";
	public static final String WORM_9_3 = "worm_9_3";
	public static final String PLUME_9 = "plume_9";

	private SatsumaTubewormGeometry()
	{
	}

	public static LayerDefinition create()
	{
		MeshDefinition mesh = new MeshDefinition();
		PartDefinition root = mesh.getRoot();
		PartDefinition satsumaTubeworm = root.addOrReplaceChild(SATSUMA_TUBEWORM, CubeListBuilder.create(),
			PartPose.offset(0.0F, 24.0F, 0.0F));
		PartDefinition body = satsumaTubeworm.addOrReplaceChild(BODY, CubeListBuilder.create()
			.texOffs(0, 0).addBox(-6.0F, -1.0F, -6.0F, 12.0F, 1.0F, 12.0F, new CubeDeformation(0.0F))
			.texOffs(0, 13).addBox(-5.0F, -2.0F, -5.0F, 10.0F, 1.0F, 10.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 0.0F));
		PartDefinition worm1 = body.addOrReplaceChild(WORM_1, CubeListBuilder.create()
			.texOffs(60, 33).addBox(-0.5F, -8.0F, -0.5F, 1.0F, 8.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(-3.5F, -1.0F, -2.5F, -0.1065F, 0.0F, 0.0908F));
		PartDefinition worm12 = worm1.addOrReplaceChild(WORM_1_2, CubeListBuilder.create()
			.texOffs(0, 42).addBox(-0.5F, -7.0F, -0.5F, 1.0F, 8.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -8.0F, 0.0F));
		PartDefinition worm13 = worm12.addOrReplaceChild(WORM_1_3, CubeListBuilder.create()
			.texOffs(0, 34).addBox(-0.5F, -6.0F, -0.5F, 1.0F, 7.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -7.0F, 0.0F));
		PartDefinition plume1 = worm13.addOrReplaceChild(PLUME_1, CubeListBuilder.create()
			.texOffs(30, 24).addBox(-0.5F, -3.0F, -0.5F, 1.0F, 3.0F, 1.0F, new CubeDeformation(0.0F))
			.texOffs(0, 60).addBox(-1.5F, -3.0F, 0.0F, 3.0F, 3.0F, 0.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -5.0F, 0.0F));
		plume1.addOrReplaceChild("plume_1_2_r1", CubeListBuilder.create()
			.texOffs(6, 60).addBox(-1.5F, -2.0F, 0.0F, 3.0F, 3.0F, 0.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, -1.0F, 0.0F, 0.0F, -1.5708F, 0.0F));
		PartDefinition worm2 = body.addOrReplaceChild(WORM_2, CubeListBuilder.create()
			.texOffs(60, 13).addBox(-0.5F, -9.0F, -0.5F, 1.0F, 9.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(2.5F, -1.0F, 0.5F, -0.1222F, 0.0F, 0.1484F));
		PartDefinition worm22 = worm2.addOrReplaceChild(WORM_2_2, CubeListBuilder.create()
			.texOffs(60, 23).addBox(-0.5F, -8.0F, -0.5F, 1.0F, 9.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -9.0F, 0.0F));
		PartDefinition worm23 = worm22.addOrReplaceChild(WORM_2_3, CubeListBuilder.create()
			.texOffs(48, 24).addBox(-0.5F, -8.0F, -0.5F, 1.0F, 9.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -8.0F, 0.0F));
		PartDefinition plume2 = worm23.addOrReplaceChild(PLUME_2, CubeListBuilder.create()
			.texOffs(24, 27).addBox(-0.5F, -3.0F, -0.5F, 1.0F, 3.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -7.0F, 0.0F));
		plume2.addOrReplaceChild("plume_2_1_r1", CubeListBuilder.create()
			.texOffs(8, 57).addBox(-1.5F, -2.0F, 0.0F, 3.0F, 3.0F, 0.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, -1.0F, 0.0F, 0.0F, -0.7854F, 0.0F));
		plume2.addOrReplaceChild("plume_2_2_r1", CubeListBuilder.create()
			.texOffs(12, 60).addBox(-1.5F, -2.0F, 0.0F, 3.0F, 3.0F, 0.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, -1.0F, 0.0F, 0.0F, -2.3562F, 0.0F));
		PartDefinition worm3 = body.addOrReplaceChild(WORM_3, CubeListBuilder.create()
			.texOffs(0, 51).addBox(-0.5F, -8.0F, -0.5F, 1.0F, 8.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(-3.5F, -1.0F, 4.5F, -0.089F, 0.0F, -0.0157F));
		PartDefinition worm32 = worm3.addOrReplaceChild(WORM_3_2, CubeListBuilder.create()
			.texOffs(0, 25).addBox(-0.5F, -7.0F, -0.5F, 1.0F, 8.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -8.0F, 0.0F));
		PartDefinition worm33 = worm32.addOrReplaceChild(WORM_3_3, CubeListBuilder.create()
			.texOffs(4, 42).addBox(-0.5F, -7.0F, -0.5F, 1.0F, 8.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -7.0F, 0.0F));
		PartDefinition plume3 = worm33.addOrReplaceChild(PLUME_3, CubeListBuilder.create()
			.texOffs(20, 27).addBox(-0.5F, -3.0F, -0.5F, 1.0F, 3.0F, 1.0F, new CubeDeformation(0.0F))
			.texOffs(12, 42).addBox(-1.5F, -3.0F, 0.0F, 3.0F, 3.0F, 0.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -6.0F, 0.0F));
		plume3.addOrReplaceChild("plume_3_2_r1", CubeListBuilder.create()
			.texOffs(12, 34).addBox(-1.5F, -2.0F, 0.0F, 3.0F, 3.0F, 0.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, -1.0F, 0.0F, 0.0F, -1.5708F, 0.0F));
		PartDefinition worm4 = body.addOrReplaceChild(WORM_4, CubeListBuilder.create()
			.texOffs(48, 0).addBox(-0.5F, -12.0F, -0.5F, 1.0F, 12.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(2.5F, -1.0F, -2.5F, 0.1152F, 0.0F, 0.11F));
		PartDefinition worm42 = worm4.addOrReplaceChild(WORM_4_2, CubeListBuilder.create()
			.texOffs(52, 0).addBox(-0.5F, -11.0F, -0.5F, 1.0F, 12.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -12.0F, 0.0F));
		PartDefinition worm43 = worm42.addOrReplaceChild(WORM_4_3, CubeListBuilder.create()
			.texOffs(56, 0).addBox(-0.5F, -11.0F, -0.5F, 1.0F, 12.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -11.0F, 0.0F));
		PartDefinition plume4 = worm43.addOrReplaceChild(PLUME_4, CubeListBuilder.create()
			.texOffs(34, 24).addBox(-0.5F, -3.0F, -0.5F, 1.0F, 3.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -10.0F, 0.0F));
		plume4.addOrReplaceChild("plume_4_1_r1", CubeListBuilder.create()
			.texOffs(12, 37).addBox(-1.5F, -2.0F, 0.0F, 3.0F, 3.0F, 0.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, -1.0F, 0.0F, 0.0F, -0.7854F, 0.0F));
		plume4.addOrReplaceChild("plume_4_2_r1", CubeListBuilder.create()
			.texOffs(12, 25).addBox(-1.5F, -2.0F, 0.0F, 3.0F, 3.0F, 0.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, -1.0F, 0.0F, 0.0F, -2.3562F, 0.0F));
		PartDefinition worm5 = body.addOrReplaceChild(WORM_5, CubeListBuilder.create()
			.texOffs(52, 24).addBox(-0.5F, -9.0F, -0.5F, 1.0F, 9.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(2.5F, -1.0F, 4.5F, -0.1239F, 0.0F, -0.0454F));
		PartDefinition worm52 = worm5.addOrReplaceChild(WORM_5_2, CubeListBuilder.create()
			.texOffs(56, 24).addBox(-0.5F, -8.0F, -0.5F, 1.0F, 9.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -9.0F, 0.0F));
		PartDefinition worm53 = worm52.addOrReplaceChild(WORM_5_3, CubeListBuilder.create()
			.texOffs(4, 51).addBox(-0.5F, -7.0F, -0.5F, 1.0F, 8.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -8.0F, 0.0F));
		PartDefinition plume5 = worm53.addOrReplaceChild(PLUME_5, CubeListBuilder.create()
			.texOffs(38, 25).addBox(-0.5F, -3.0F, -0.5F, 1.0F, 3.0F, 1.0F, new CubeDeformation(0.0F))
			.texOffs(12, 28).addBox(-1.5F, -3.0F, 0.0F, 3.0F, 3.0F, 0.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -6.0F, 0.0F));
		plume5.addOrReplaceChild("plume_5_2_r1", CubeListBuilder.create()
			.texOffs(12, 31).addBox(-1.5F, -2.0F, 0.0F, 3.0F, 3.0F, 0.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, -1.0F, 0.0F, 0.0F, -1.5708F, 0.0F));
		PartDefinition worm6 = body.addOrReplaceChild(WORM_6, CubeListBuilder.create()
			.texOffs(40, 13).addBox(-0.5F, -11.0F, -0.5F, 1.0F, 11.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(-1.5F, -1.0F, 2.5F, 0.1501F, 0.0F, -0.0646F));
		PartDefinition worm62 = worm6.addOrReplaceChild(WORM_6_2, CubeListBuilder.create()
			.texOffs(60, 0).addBox(-0.5F, -11.0F, -0.5F, 1.0F, 12.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -11.0F, 0.0F));
		PartDefinition worm63 = worm62.addOrReplaceChild(WORM_6_3, CubeListBuilder.create()
			.texOffs(44, 13).addBox(-0.5F, -10.0F, -0.5F, 1.0F, 11.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -11.0F, 0.0F));
		PartDefinition plume6 = worm63.addOrReplaceChild(PLUME_6, CubeListBuilder.create()
			.texOffs(42, 25).addBox(-0.5F, -3.0F, -0.5F, 1.0F, 3.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -9.0F, 0.0F));
		plume6.addOrReplaceChild("plume_6_1_r1", CubeListBuilder.create()
			.texOffs(12, 45).addBox(-1.5F, -2.0F, 0.0F, 3.0F, 3.0F, 0.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, -1.0F, 0.0F, 0.0F, -0.7854F, 0.0F));
		plume6.addOrReplaceChild("plume_6_2_r1", CubeListBuilder.create()
			.texOffs(12, 48).addBox(-1.5F, -2.0F, 0.0F, 3.0F, 3.0F, 0.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, -1.0F, 0.0F, 0.0F, -2.3562F, 0.0F));
		PartDefinition worm7 = body.addOrReplaceChild(WORM_7, CubeListBuilder.create()
			.texOffs(4, 34).addBox(-0.5F, -7.0F, -0.5F, 1.0F, 7.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(-4.5F, -1.0F, 1.5F, -0.0052F, 0.0F, 0.0017F));
		PartDefinition worm72 = worm7.addOrReplaceChild(WORM_7_2, CubeListBuilder.create()
			.texOffs(4, 25).addBox(-0.5F, -6.0F, -0.5F, 1.0F, 7.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -7.0F, 0.0F));
		PartDefinition worm73 = worm72.addOrReplaceChild(WORM_7_3, CubeListBuilder.create()
			.texOffs(8, 34).addBox(-0.5F, -5.0F, -0.5F, 1.0F, 6.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -6.0F, 0.0F));
		PartDefinition plume7 = worm73.addOrReplaceChild(PLUME_7, CubeListBuilder.create()
			.texOffs(28, 28).addBox(-0.5F, -3.0F, -0.5F, 1.0F, 3.0F, 1.0F, new CubeDeformation(0.0F))
			.texOffs(12, 51).addBox(-1.5F, -3.0F, 0.0F, 3.0F, 3.0F, 0.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -4.0F, 0.0F));
		plume7.addOrReplaceChild("plume_7_2_r1", CubeListBuilder.create()
			.texOffs(12, 54).addBox(-1.5F, -2.0F, 0.0F, 3.0F, 3.0F, 0.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, -1.0F, 0.0F, 0.0F, -1.5708F, 0.0F));
		PartDefinition worm8 = body.addOrReplaceChild(WORM_8, CubeListBuilder.create()
			.texOffs(8, 25).addBox(-0.5F, -6.0F, -0.5F, 1.0F, 6.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(-1.5F, -1.0F, -0.5F, 0.007F, 0.0F, 0.0768F));
		PartDefinition worm82 = worm8.addOrReplaceChild(WORM_8_2, CubeListBuilder.create()
			.texOffs(8, 42).addBox(-0.5F, -6.0F, -0.5F, 1.0F, 7.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -6.0F, 0.0F));
		PartDefinition worm83 = worm82.addOrReplaceChild(WORM_8_3, CubeListBuilder.create()
			.texOffs(8, 50).addBox(-0.5F, -5.0F, -0.5F, 1.0F, 6.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -6.0F, 0.0F));
		PartDefinition plume8 = worm83.addOrReplaceChild(PLUME_8, CubeListBuilder.create()
			.texOffs(24, 31).addBox(-0.5F, -3.0F, -0.5F, 1.0F, 3.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -4.0F, 0.0F));
		plume8.addOrReplaceChild("plume_8_1_r1", CubeListBuilder.create()
			.texOffs(14, 57).addBox(-1.5F, -2.0F, 0.0F, 3.0F, 3.0F, 0.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, -1.0F, 0.0F, 0.0F, -0.7854F, 0.0F));
		plume8.addOrReplaceChild("plume_8_2_r1", CubeListBuilder.create()
			.texOffs(18, 60).addBox(-1.5F, -2.0F, 0.0F, 3.0F, 3.0F, 0.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, -1.0F, 0.0F, 0.0F, -2.3562F, 0.0F));
		PartDefinition worm9 = body.addOrReplaceChild(WORM_9, CubeListBuilder.create()
			.texOffs(48, 13).addBox(-0.5F, -10.0F, -0.5F, 1.0F, 10.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(-0.5F, -1.0F, 0.5F, -0.1134F, 0.0F, 0.0349F));
		PartDefinition worm92 = worm9.addOrReplaceChild(WORM_9_2, CubeListBuilder.create()
			.texOffs(52, 13).addBox(-0.5F, -9.0F, -0.5F, 1.0F, 10.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -10.0F, 0.0F));
		PartDefinition worm93 = worm92.addOrReplaceChild(WORM_9_3, CubeListBuilder.create()
			.texOffs(56, 13).addBox(-0.5F, -9.0F, -0.5F, 1.0F, 10.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -9.0F, 0.0F));
		PartDefinition plume9 = worm93.addOrReplaceChild(PLUME_9, CubeListBuilder.create()
			.texOffs(20, 31).addBox(-0.5F, -3.0F, -0.5F, 1.0F, 3.0F, 1.0F, new CubeDeformation(0.0F))
			.texOffs(24, 24).addBox(-1.5F, -3.0F, 0.0F, 3.0F, 3.0F, 0.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -8.0F, 0.0F));
		plume9.addOrReplaceChild("plume_9_2_r1", CubeListBuilder.create()
			.texOffs(18, 24).addBox(-1.5F, -2.0F, 0.0F, 3.0F, 3.0F, 0.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, -1.0F, 0.0F, 0.0F, -1.5708F, 0.0F));
		return LayerDefinition.create(mesh, 64, 64);
	}
}
