package com.abyssia.client.entity.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Generated by tools/bbmodel-generator (scaly_foot_snail.bbmodel, template gastropod, seed 1).
 * Texture 64x32 UV (64x32 px): textures/entity/scaly_foot_snail.png.
 * Regenerate with: node tools/bbmodel-generator/cli.js scaly_foot_snail
 */
public final class ScalyFootSnailGeometry
{
	public static final String SCALY_FOOT_SNAIL = "scaly_foot_snail";
	public static final String BODY = "body";
	public static final String HEAD = "head";
	public static final String RIGHT_TENTACLE = "right_tentacle";
	public static final String LEFT_TENTACLE = "left_tentacle";
	public static final String SHELL = "shell";
	public static final String SHELL_2 = "shell_2";
	public static final String SHELL_3 = "shell_3";
	public static final String RIGHT_SCALES = "right_scales";
	public static final String LEFT_SCALES = "left_scales";

	private ScalyFootSnailGeometry()
	{
	}

	public static LayerDefinition create()
	{
		MeshDefinition mesh = new MeshDefinition();
		PartDefinition root = mesh.getRoot();
		PartDefinition scalyFootSnail = root.addOrReplaceChild(SCALY_FOOT_SNAIL, CubeListBuilder.create(),
			PartPose.offset(0.0F, 24.0F, 0.0F));
		PartDefinition body = scalyFootSnail.addOrReplaceChild(BODY, CubeListBuilder.create()
			.texOffs(0, 0).addBox(-2.5F, -2.0F, -5.0F, 5.0F, 2.0F, 10.0F, new CubeDeformation(0.0F))
			.texOffs(0, 12).addBox(-1.5F, -3.0F, -4.0F, 3.0F, 1.0F, 8.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 0.0F));
		PartDefinition head = body.addOrReplaceChild(HEAD, CubeListBuilder.create()
			.texOffs(20, 27).addBox(-1.5F, -0.5F, -3.0F, 3.0F, 2.0F, 3.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -1.5F, -4.0F));
		PartDefinition rightTentacle = head.addOrReplaceChild(RIGHT_TENTACLE, CubeListBuilder.create()
			.texOffs(40, 17).addBox(-0.5F, -0.5F, -4.0F, 1.0F, 1.0F, 4.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(-1.0F, 0.0F, -2.0F, -0.3491F, 0.5236F, 0.0F));
		PartDefinition leftTentacle = head.addOrReplaceChild(LEFT_TENTACLE, CubeListBuilder.create()
			.texOffs(34, 12).addBox(-0.5F, -0.5F, -4.0F, 1.0F, 1.0F, 4.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(1.0F, 0.0F, -2.0F, -0.3491F, -0.5236F, 0.0F));
		PartDefinition shell = body.addOrReplaceChild(SHELL, CubeListBuilder.create()
			.texOffs(30, 0).addBox(-3.5F, -5.0F, -3.5F, 7.0F, 5.0F, 7.0F, new CubeDeformation(0.0F))
			.texOffs(20, 21).addBox(-2.5F, -6.0F, -2.5F, 5.0F, 1.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, -2.0F, 1.0F, 0.3142F, 0.0F, 0.0F));
		PartDefinition shell2 = shell.addOrReplaceChild(SHELL_2, CubeListBuilder.create()
			.texOffs(0, 21).addBox(-2.5F, -4.0F, -2.5F, 5.0F, 4.0F, 5.0F, new CubeDeformation(0.0F))
			.texOffs(32, 27).addBox(-1.5F, -5.0F, -1.5F, 3.0F, 1.0F, 3.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(-1.0F, -3.0F, 2.0F, 0.2094F, -0.4887F, 0.1396F));
		PartDefinition shell3 = shell2.addOrReplaceChild(SHELL_3, CubeListBuilder.create()
			.texOffs(22, 12).addBox(-1.5F, -3.0F, -1.5F, 3.0F, 3.0F, 3.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(-0.5F, -3.0F, 1.0F, 0.2094F, -0.4887F, 0.1396F));
		PartDefinition rightScales = body.addOrReplaceChild(RIGHT_SCALES, CubeListBuilder.create(),
			PartPose.offset(-2.5F, -3.0F, 0.0F));
		rightScales.addOrReplaceChild("right_scale_r1", CubeListBuilder.create()
			.texOffs(58, 4).addBox(0.0F, -1.0F, -1.0F, 0.0F, 4.0F, 2.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, -3.0F, 0.0F, 0.0F, -0.4887F));
		rightScales.addOrReplaceChild("right_scale_2_r1", CubeListBuilder.create()
			.texOffs(58, 8).addBox(0.0F, -1.0F, -1.0F, 0.0F, 4.0F, 2.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, -2.0F, 0.0F, 0.0F, -0.4887F));
		rightScales.addOrReplaceChild("right_scale_3_r1", CubeListBuilder.create()
			.texOffs(52, 10).addBox(0.0F, -1.0F, -1.0F, 0.0F, 4.0F, 2.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, -0.4887F));
		rightScales.addOrReplaceChild("right_scale_4_r1", CubeListBuilder.create()
			.texOffs(56, 12).addBox(0.0F, -1.0F, -1.0F, 0.0F, 4.0F, 2.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 2.0F, 0.0F, 0.0F, -0.4887F));
		rightScales.addOrReplaceChild("right_scale_5_r1", CubeListBuilder.create()
			.texOffs(60, 12).addBox(0.0F, -1.0F, -1.0F, 0.0F, 4.0F, 2.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 3.0F, 0.0F, 0.0F, -0.4887F));
		PartDefinition leftScales = body.addOrReplaceChild(LEFT_SCALES, CubeListBuilder.create(),
			PartPose.offset(2.5F, -3.0F, 0.0F));
		leftScales.addOrReplaceChild("left_scale_r1", CubeListBuilder.create()
			.texOffs(34, 15).addBox(0.0F, -1.0F, -1.0F, 0.0F, 4.0F, 2.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, -3.0F, 0.0F, 0.0F, 0.4887F));
		leftScales.addOrReplaceChild("left_scale_2_r1", CubeListBuilder.create()
			.texOffs(44, 10).addBox(0.0F, -1.0F, -1.0F, 0.0F, 4.0F, 2.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, -2.0F, 0.0F, 0.0F, 0.4887F));
		leftScales.addOrReplaceChild("left_scale_3_r1", CubeListBuilder.create()
			.texOffs(48, 10).addBox(0.0F, -1.0F, -1.0F, 0.0F, 4.0F, 2.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.4887F));
		leftScales.addOrReplaceChild("left_scale_4_r1", CubeListBuilder.create()
			.texOffs(40, 20).addBox(0.0F, -1.0F, -1.0F, 0.0F, 4.0F, 2.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 2.0F, 0.0F, 0.0F, 0.4887F));
		leftScales.addOrReplaceChild("left_scale_5_r1", CubeListBuilder.create()
			.texOffs(58, 0).addBox(0.0F, -1.0F, -1.0F, 0.0F, 4.0F, 2.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 3.0F, 0.0F, 0.0F, 0.4887F));
		return LayerDefinition.create(mesh, 64, 32);
	}
}
