package com.abyssia.client.entity.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Generated by tools/bbmodel-generator (yumenamako.bbmodel, template softbody, seed 1).
 * Texture 64x32 UV (64x32 px): textures/entity/yumenamako.png, glow mask textures/entity/yumenamako_glow.png.
 * Regenerate with: node tools/bbmodel-generator/cli.js yumenamako
 */
public final class YumenamakoGeometry
{
	public static final String YUMENAMAKO = "yumenamako";
	public static final String BODY = "body";
	public static final String BODY_2 = "body_2";
	public static final String BODY_3 = "body_3";
	public static final String VEIL = "veil";
	public static final String BRIM = "brim";
	public static final String TENTACLES = "tentacles";

	private YumenamakoGeometry()
	{
	}

	public static LayerDefinition create()
	{
		MeshDefinition mesh = new MeshDefinition();
		PartDefinition root = mesh.getRoot();
		PartDefinition yumenamako = root.addOrReplaceChild(YUMENAMAKO, CubeListBuilder.create(),
			PartPose.offset(0.0F, 24.0F, 0.0F));
		PartDefinition body = yumenamako.addOrReplaceChild(BODY, CubeListBuilder.create()
			.texOffs(0, 0).addBox(-3.5F, -2.0F, 0.0F, 7.0F, 4.0F, 5.0F, new CubeDeformation(0.0F))
			.texOffs(24, 5).addBox(-2.5F, -3.0F, 1.0F, 5.0F, 1.0F, 4.0F, new CubeDeformation(0.0F))
			.texOffs(24, 0).addBox(-2.5F, 2.0F, 1.0F, 5.0F, 1.0F, 4.0F, new CubeDeformation(0.0F))
			.texOffs(38, 16).addBox(-4.5F, 2.0F, 2.5F, 1.0F, 1.0F, 1.0F, new CubeDeformation(0.0F))
			.texOffs(28, 26).addBox(3.5F, 2.0F, 2.5F, 1.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -4.1213F, -7.0F));
		PartDefinition body2 = body.addOrReplaceChild(BODY_2, CubeListBuilder.create()
			.texOffs(0, 9).addBox(-3.0F, -2.0F, -1.0F, 6.0F, 3.0F, 6.0F, new CubeDeformation(0.0F))
			.texOffs(42, 7).addBox(-2.0F, -3.0F, -1.0F, 4.0F, 1.0F, 6.0F, new CubeDeformation(0.0F))
			.texOffs(42, 0).addBox(-2.0F, 1.0F, -1.0F, 4.0F, 1.0F, 6.0F, new CubeDeformation(0.0F))
			.texOffs(28, 28).addBox(-4.0F, 1.0F, 2.5F, 1.0F, 1.0F, 1.0F, new CubeDeformation(0.0F))
			.texOffs(28, 30).addBox(3.0F, 1.0F, 2.5F, 1.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 5.0F));
		PartDefinition body3 = body2.addOrReplaceChild(BODY_3, CubeListBuilder.create()
			.texOffs(22, 18).addBox(-2.5F, -2.0F, -1.0F, 5.0F, 3.0F, 5.0F, new CubeDeformation(0.0F))
			.texOffs(14, 26).addBox(-1.5F, -3.0F, -1.0F, 3.0F, 1.0F, 4.0F, new CubeDeformation(0.0F))
			.texOffs(0, 26).addBox(-1.5F, 1.0F, -1.0F, 3.0F, 1.0F, 4.0F, new CubeDeformation(0.0F))
			.texOffs(32, 26).addBox(-3.5F, 1.0F, 1.5F, 1.0F, 1.0F, 1.0F, new CubeDeformation(0.0F))
			.texOffs(32, 28).addBox(2.5F, 1.0F, 1.5F, 1.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 5.0F));
		PartDefinition brim = body3.addOrReplaceChild(BRIM, CubeListBuilder.create()
			.texOffs(24, 14).addBox(-3.5F, -4.0F, 0.0F, 7.0F, 4.0F, 0.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, -2.0F, 3.0F, -0.4363F, 0.0F, 0.0F));
		PartDefinition veil = body.addOrReplaceChild(VEIL, CubeListBuilder.create()
			.texOffs(0, 18).addBox(-5.5F, -8.0F, 0.0F, 11.0F, 8.0F, 0.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, -2.0F, 1.0F, 0.6109F, 0.0F, 0.0F));
		PartDefinition tentacles = body.addOrReplaceChild(TENTACLES, CubeListBuilder.create()
			.texOffs(38, 10).addBox(1.5F, 0.0F, -1.0F, 1.0F, 2.0F, 1.0F, new CubeDeformation(0.0F))
			.texOffs(38, 13).addBox(0.5F, 0.0F, 0.0F, 1.0F, 2.0F, 1.0F, new CubeDeformation(0.0F))
			.texOffs(24, 10).addBox(-0.5F, 0.0F, -1.0F, 1.0F, 2.0F, 1.0F, new CubeDeformation(0.0F))
			.texOffs(28, 10).addBox(-1.5F, 0.0F, 0.0F, 1.0F, 2.0F, 1.0F, new CubeDeformation(0.0F))
			.texOffs(32, 10).addBox(-2.5F, 0.0F, -1.0F, 1.0F, 2.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 2.0F, 1.0F, -0.7854F, 0.0F, 0.0F));
		return LayerDefinition.create(mesh, 64, 32);
	}
}
