package com.abyssia.client.entity.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Generated by tools/bbmodel-generator (blue_ling.bbmodel, template eel, seed 1).
 * Texture 64x64 UV (64x64 px): textures/entity/blue_ling.png.
 * Regenerate with: node tools/bbmodel-generator/cli.js blue_ling
 */
public final class BlueLingGeometry
{
	public static final String BLUE_LING = "blue_ling";
	public static final String BODY = "body";
	public static final String BODY_2 = "body_2";
	public static final String BODY_3 = "body_3";
	public static final String BODY_4 = "body_4";
	public static final String BODY_5 = "body_5";
	public static final String BODY_6 = "body_6";
	public static final String HEAD = "head";
	public static final String MOUTH = "mouth";
	public static final String RIGHT_EYE = "right_eye";
	public static final String LEFT_EYE = "left_eye";
	public static final String RIGHT_FIN = "right_fin";
	public static final String LEFT_FIN = "left_fin";
	public static final String RIGHT_PELVIC_FIN = "right_pelvic_fin";
	public static final String LEFT_PELVIC_FIN = "left_pelvic_fin";
	public static final String DORSAL_FIN = "dorsal_fin";
	public static final String DORSAL_FIN_2 = "dorsal_fin_2";
	public static final String DORSAL_FIN_3 = "dorsal_fin_3";
	public static final String DORSAL_FIN_4 = "dorsal_fin_4";
	public static final String DORSAL_FIN_5 = "dorsal_fin_5";
	public static final String DORSAL_FIN_6 = "dorsal_fin_6";
	public static final String ANAL_FIN = "anal_fin";
	public static final String ANAL_FIN_2 = "anal_fin_2";
	public static final String ANAL_FIN_3 = "anal_fin_3";
	public static final String ANAL_FIN_4 = "anal_fin_4";
	public static final String ANAL_FIN_5 = "anal_fin_5";
	public static final String TAIL_FIN = "tail_fin";

	private BlueLingGeometry()
	{
	}

	public static LayerDefinition create()
	{
		MeshDefinition mesh = new MeshDefinition();
		PartDefinition root = mesh.getRoot();
		PartDefinition blueLing = root.addOrReplaceChild(BLUE_LING, CubeListBuilder.create(),
			PartPose.offset(0.0F, 24.0F, 0.0F));
		PartDefinition body = blueLing.addOrReplaceChild(BODY, CubeListBuilder.create()
			.texOffs(0, 11).addBox(-2.5F, -3.0F, 0.0F, 5.0F, 6.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -4.2817F, -11.0F));
		PartDefinition body2 = body.addOrReplaceChild(BODY_2, CubeListBuilder.create()
			.texOffs(26, 0).addBox(-2.5F, -3.0F, -1.0F, 5.0F, 5.0F, 6.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 5.0F));
		PartDefinition body3 = body2.addOrReplaceChild(BODY_3, CubeListBuilder.create()
			.texOffs(20, 11).addBox(-2.0F, -3.0F, -1.0F, 4.0F, 5.0F, 6.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 5.0F));
		PartDefinition body4 = body3.addOrReplaceChild(BODY_4, CubeListBuilder.create()
			.texOffs(0, 22).addBox(-2.0F, -2.0F, -1.0F, 4.0F, 4.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 5.0F));
		PartDefinition body5 = body4.addOrReplaceChild(BODY_5, CubeListBuilder.create()
			.texOffs(40, 19).addBox(-1.5F, -2.0F, -1.0F, 3.0F, 4.0F, 6.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 4.0F));
		PartDefinition body6 = body5.addOrReplaceChild(BODY_6, CubeListBuilder.create()
			.texOffs(48, 0).addBox(-1.5F, -2.0F, -1.0F, 3.0F, 3.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 5.0F));
		PartDefinition dorsalFin6 = body6.addOrReplaceChild(DORSAL_FIN_6, CubeListBuilder.create()
			.texOffs(52, 28).addBox(0.0F, -1.0F, 0.0F, 0.0F, 2.0F, 4.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -2.0F, 0.0F));
		PartDefinition analFin5 = body6.addOrReplaceChild(ANAL_FIN_5, CubeListBuilder.create()
			.texOffs(44, 28).addBox(0.0F, -1.0F, 0.0F, 0.0F, 2.0F, 4.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 1.0F, 0.0F));
		PartDefinition tailFin = body6.addOrReplaceChild(TAIL_FIN, CubeListBuilder.create()
			.texOffs(0, 29).addBox(0.0F, -2.0F, -1.0F, 0.0F, 4.0F, 4.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 4.0F));
		PartDefinition dorsalFin5 = body5.addOrReplaceChild(DORSAL_FIN_5, CubeListBuilder.create()
			.texOffs(48, 24).addBox(0.0F, -2.0F, 0.0F, 0.0F, 3.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -2.0F, 0.0F));
		PartDefinition analFin4 = body5.addOrReplaceChild(ANAL_FIN_4, CubeListBuilder.create()
			.texOffs(18, 23).addBox(0.0F, -1.0F, 0.0F, 0.0F, 3.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 2.0F, 0.0F));
		PartDefinition dorsalFin4 = body4.addOrReplaceChild(DORSAL_FIN_4, CubeListBuilder.create()
			.texOffs(36, 28).addBox(0.0F, -2.0F, 0.0F, 0.0F, 3.0F, 4.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -2.0F, 0.0F));
		PartDefinition analFin3 = body4.addOrReplaceChild(ANAL_FIN_3, CubeListBuilder.create()
			.texOffs(8, 29).addBox(0.0F, -1.0F, 0.0F, 0.0F, 3.0F, 4.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 2.0F, 0.0F));
		PartDefinition dorsalFin3 = body3.addOrReplaceChild(DORSAL_FIN_3, CubeListBuilder.create()
			.texOffs(38, 24).addBox(0.0F, -2.0F, 0.0F, 0.0F, 3.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -3.0F, 0.0F));
		PartDefinition analFin2 = body3.addOrReplaceChild(ANAL_FIN_2, CubeListBuilder.create()
			.texOffs(48, 3).addBox(0.0F, -1.0F, 0.0F, 0.0F, 3.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 2.0F, 0.0F));
		PartDefinition dorsalFin2 = body2.addOrReplaceChild(DORSAL_FIN_2, CubeListBuilder.create()
			.texOffs(28, 23).addBox(0.0F, -2.0F, 0.0F, 0.0F, 3.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -3.0F, 0.0F));
		PartDefinition analFin = body2.addOrReplaceChild(ANAL_FIN, CubeListBuilder.create()
			.texOffs(0, 26).addBox(0.0F, -1.0F, 0.0F, 0.0F, 2.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 2.0F, 0.0F));
		PartDefinition head = body.addOrReplaceChild(HEAD, CubeListBuilder.create()
			.texOffs(0, 0).addBox(-2.5F, -2.0F, -7.0F, 5.0F, 3.0F, 8.0F, new CubeDeformation(0.0F))
			.texOffs(40, 11).addBox(-1.5F, -3.0F, -6.0F, 3.0F, 1.0F, 7.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 0.0F));
		PartDefinition mouth = head.addOrReplaceChild(MOUTH, CubeListBuilder.create()
			.texOffs(18, 22).addBox(-2.5F, 0.0F, -3.0F, 5.0F, 2.0F, 4.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 1.0F, -1.0F));
		PartDefinition rightEye = head.addOrReplaceChild(RIGHT_EYE, CubeListBuilder.create()
			.texOffs(28, 31).addBox(-1.0F, -1.0F, -1.0F, 2.0F, 2.0F, 2.0F, new CubeDeformation(0.0F)),
			PartPose.offset(-2.3F, -2.0F, -5.0F));
		PartDefinition leftEye = head.addOrReplaceChild(LEFT_EYE, CubeListBuilder.create()
			.texOffs(20, 31).addBox(-1.0F, -1.0F, -1.0F, 2.0F, 2.0F, 2.0F, new CubeDeformation(0.0F)),
			PartPose.offset(2.3F, -2.0F, -5.0F));
		PartDefinition rightFin = body.addOrReplaceChild(RIGHT_FIN, CubeListBuilder.create()
			.texOffs(52, 30).addBox(0.0F, -1.0F, -1.0F, 0.0F, 2.0F, 4.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(-2.5F, 0.0F, 1.0F, 0.0F, -0.6109F, -0.2618F));
		PartDefinition leftFin = body.addOrReplaceChild(LEFT_FIN, CubeListBuilder.create()
			.texOffs(44, 30).addBox(0.0F, -1.0F, -1.0F, 0.0F, 2.0F, 4.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(2.5F, 0.0F, 1.0F, 0.0F, 0.6109F, 0.2618F));
		PartDefinition rightPelvicFin = body.addOrReplaceChild(RIGHT_PELVIC_FIN, CubeListBuilder.create()
			.texOffs(36, 22).addBox(0.0F, -1.0F, -1.0F, 0.0F, 2.0F, 2.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(-2.0F, 3.0F, 1.0F, 0.3491F, -0.3491F, 0.0F));
		PartDefinition leftPelvicFin = body.addOrReplaceChild(LEFT_PELVIC_FIN, CubeListBuilder.create()
			.texOffs(36, 20).addBox(0.0F, -1.0F, -1.0F, 0.0F, 2.0F, 2.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(2.0F, 3.0F, 1.0F, 0.3491F, 0.3491F, 0.0F));
		PartDefinition dorsalFin = body.addOrReplaceChild(DORSAL_FIN, CubeListBuilder.create()
			.texOffs(10, 26).addBox(0.0F, -1.0F, 0.0F, 0.0F, 2.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -3.0F, 0.0F));
		return LayerDefinition.create(mesh, 64, 64);
	}
}
