package com.abyssia.client.entity.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Generated by tools/bbmodel-generator (cookiecutter_shark.bbmodel, template fish, seed 1).
 * Texture 64x32 UV (64x32 px): textures/entity/cookiecutter_shark.png, glow mask textures/entity/cookiecutter_shark_glow.png.
 * Regenerate with: node tools/bbmodel-generator/cli.js cookiecutter_shark
 */
public final class CookiecutterSharkGeometry
{
	public static final String COOKIECUTTER_SHARK = "cookiecutter_shark";
	public static final String BODY = "body";
	public static final String HEAD = "head";
	public static final String MOUTH = "mouth";
	public static final String LOWER_TEETH = "lower_teeth";
	public static final String RIGHT_EYE = "right_eye";
	public static final String LEFT_EYE = "left_eye";
	public static final String RIGHT_FIN = "right_fin";
	public static final String LEFT_FIN = "left_fin";
	public static final String RIGHT_PELVIC_FIN = "right_pelvic_fin";
	public static final String LEFT_PELVIC_FIN = "left_pelvic_fin";
	public static final String DORSAL_FIN = "dorsal_fin";
	public static final String DORSAL_FIN_2 = "dorsal_fin_2";
	public static final String TAIL = "tail";
	public static final String TAIL_2 = "tail_2";
	public static final String TAIL_FIN = "tail_fin";

	private CookiecutterSharkGeometry()
	{
	}

	public static LayerDefinition create()
	{
		MeshDefinition mesh = new MeshDefinition();
		PartDefinition root = mesh.getRoot();
		PartDefinition cookiecutterShark = root.addOrReplaceChild(COOKIECUTTER_SHARK, CubeListBuilder.create(),
			PartPose.offset(0.0F, 24.0F, 0.0F));
		PartDefinition body = cookiecutterShark.addOrReplaceChild(BODY, CubeListBuilder.create()
			.texOffs(0, 0).addBox(-2.0F, -1.0F, -1.0F, 4.0F, 2.0F, 13.0F, new CubeDeformation(0.0F))
			.texOffs(34, 13).addBox(-1.0F, -2.0F, -1.0F, 2.0F, 1.0F, 12.0F, new CubeDeformation(0.0F))
			.texOffs(34, 0).addBox(-1.0F, 1.0F, -1.0F, 2.0F, 1.0F, 12.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -3.2817F, -7.0F));
		PartDefinition head = body.addOrReplaceChild(HEAD, CubeListBuilder.create()
			.texOffs(0, 15).addBox(-2.0F, -2.0F, -4.0F, 4.0F, 3.0F, 4.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 0.0F));
		PartDefinition mouth = head.addOrReplaceChild(MOUTH, CubeListBuilder.create()
			.texOffs(14, 26).addBox(-1.5F, 0.0F, -3.0F, 3.0F, 1.0F, 4.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 1.0F, -1.0F, 0.0524F, 0.0F, 0.0F));
		PartDefinition lowerTeeth = mouth.addOrReplaceChild(LOWER_TEETH, CubeListBuilder.create()
			.texOffs(14, 22).addBox(-0.5F, -1.0F, 0.5F, 1.0F, 1.0F, 0.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, -3.0F));
		PartDefinition rightEye = head.addOrReplaceChild(RIGHT_EYE, CubeListBuilder.create()
			.texOffs(26, 19).addBox(-1.0F, -1.0F, -1.0F, 2.0F, 2.0F, 2.0F, new CubeDeformation(0.0F)),
			PartPose.offset(-2.0F, -1.0F, -3.0F));
		PartDefinition leftEye = head.addOrReplaceChild(LEFT_EYE, CubeListBuilder.create()
			.texOffs(26, 15).addBox(-1.0F, -1.0F, -1.0F, 2.0F, 2.0F, 2.0F, new CubeDeformation(0.0F)),
			PartPose.offset(2.0F, -1.0F, -3.0F));
		PartDefinition rightFin = body.addOrReplaceChild(RIGHT_FIN, CubeListBuilder.create()
			.texOffs(14, 20).addBox(0.0F, -1.0F, -1.0F, 0.0F, 2.0F, 3.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(-2.0F, 0.0F, 1.0F, 0.0F, -0.5236F, -0.4363F));
		PartDefinition leftFin = body.addOrReplaceChild(LEFT_FIN, CubeListBuilder.create()
			.texOffs(0, 26).addBox(0.0F, -1.0F, -1.0F, 0.0F, 2.0F, 3.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(2.0F, 0.0F, 1.0F, 0.0F, 0.5236F, 0.4363F));
		PartDefinition rightPelvicFin = body.addOrReplaceChild(RIGHT_PELVIC_FIN, CubeListBuilder.create()
			.texOffs(20, 19).addBox(0.0F, -1.0F, -1.0F, 0.0F, 2.0F, 3.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(-1.0F, 2.0F, 10.0F, 0.3491F, -0.3491F, 0.0F));
		PartDefinition leftPelvicFin = body.addOrReplaceChild(LEFT_PELVIC_FIN, CubeListBuilder.create()
			.texOffs(6, 26).addBox(0.0F, -1.0F, -1.0F, 0.0F, 2.0F, 3.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(1.0F, 2.0F, 10.0F, 0.3491F, 0.3491F, 0.0F));
		PartDefinition dorsalFin = body.addOrReplaceChild(DORSAL_FIN, CubeListBuilder.create()
			.texOffs(20, 22).addBox(0.0F, -1.0F, 0.0F, 0.0F, 2.0F, 2.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -2.0F, 8.0F));
		PartDefinition dorsalFin2 = body.addOrReplaceChild(DORSAL_FIN_2, CubeListBuilder.create()
			.texOffs(12, 28).addBox(0.0F, -1.0F, 0.0F, 0.0F, 2.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -2.0F, 11.0F));
		PartDefinition tail = body.addOrReplaceChild(TAIL, CubeListBuilder.create()
			.texOffs(0, 22).addBox(-1.5F, -2.0F, 0.0F, 3.0F, 3.0F, 4.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 11.0F));
		PartDefinition tail2 = tail.addOrReplaceChild(TAIL_2, CubeListBuilder.create()
			.texOffs(28, 26).addBox(-1.0F, -1.0F, 0.0F, 2.0F, 2.0F, 3.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 3.0F));
		PartDefinition tailFin = tail2.addOrReplaceChild(TAIL_FIN, CubeListBuilder.create()
			.texOffs(16, 10).addBox(0.0F, -4.0F, -1.0F, 0.0F, 7.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 3.0F));
		return LayerDefinition.create(mesh, 64, 32);
	}
}
