package com.abyssia.client.entity.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Generated by tools/bbmodel-generator (stalked_sea_squirt.bbmodel, template photo, seed 1).
 * Texture 128x64 UV (128x64 px): textures/entity/stalked_sea_squirt.png.
 * Regenerate with: node tools/bbmodel-generator/cli.js stalked_sea_squirt
 */
public final class StalkedSeaSquirtGeometry
{
	public static final String STALKED_SEA_SQUIRT = "stalked_sea_squirt";
	public static final String BASE = "base";
	public static final String PART_2 = "part_2";
	public static final String PART_3 = "part_3";
	public static final String PART_4 = "part_4";

	private StalkedSeaSquirtGeometry()
	{
	}

	public static LayerDefinition create()
	{
		MeshDefinition mesh = new MeshDefinition();
		PartDefinition root = mesh.getRoot();
		PartDefinition stalkedSeaSquirt = root.addOrReplaceChild(STALKED_SEA_SQUIRT, CubeListBuilder.create(),
			PartPose.offset(0.0F, 24.0F, 0.0F));
		PartDefinition base = stalkedSeaSquirt.addOrReplaceChild(BASE, CubeListBuilder.create()
			.texOffs(104, 34).addBox(-3.0F, -3.0F, -2.0F, 6.0F, 3.0F, 4.0F, new CubeDeformation(0.0F))
			.texOffs(104, 25).addBox(-2.0F, -3.0F, -3.0F, 4.0F, 3.0F, 6.0F, new CubeDeformation(0.0F))
			.texOffs(108, 0).addBox(-4.0F, -7.0F, -2.0F, 6.0F, 4.0F, 4.0F, new CubeDeformation(0.0F))
			.texOffs(84, 18).addBox(-3.0F, -7.0F, -3.0F, 4.0F, 4.0F, 6.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 0.0F));
		PartDefinition part2 = base.addOrReplaceChild(PART_2, CubeListBuilder.create()
			.texOffs(40, 35).addBox(-3.5F, -2.0F, -2.0F, 7.0F, 2.0F, 5.0F, new CubeDeformation(0.0F))
			.texOffs(104, 8).addBox(-2.5F, -2.0F, -3.0F, 5.0F, 2.0F, 7.0F, new CubeDeformation(0.0F))
			.texOffs(64, 46).addBox(-3.5F, -3.0F, -2.0F, 6.0F, 1.0F, 4.0F, new CubeDeformation(0.0F))
			.texOffs(84, 37).addBox(-2.5F, -3.0F, -3.0F, 4.0F, 1.0F, 6.0F, new CubeDeformation(0.0F))
			.texOffs(84, 28).addBox(-4.5F, -8.0F, -2.0F, 6.0F, 5.0F, 4.0F, new CubeDeformation(0.0F))
			.texOffs(64, 35).addBox(-3.5F, -8.0F, -3.0F, 4.0F, 5.0F, 6.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.5F, -7.0F, 0.0F));
		PartDefinition part3 = part2.addOrReplaceChild(PART_3, CubeListBuilder.create()
			.texOffs(40, 23).addBox(-4.5F, -1.0F, -2.0F, 9.0F, 1.0F, 5.0F, new CubeDeformation(0.0F))
			.texOffs(76, 8).addBox(-2.5F, -1.0F, -4.0F, 5.0F, 1.0F, 9.0F, new CubeDeformation(0.0F))
			.texOffs(0, 52).addBox(-4.5F, -3.0F, -3.0F, 11.0F, 2.0F, 7.0F, new CubeDeformation(0.0F))
			.texOffs(40, 0).addBox(-2.5F, -3.0F, -5.0F, 7.0F, 2.0F, 11.0F, new CubeDeformation(0.0F))
			.texOffs(0, 31).addBox(-5.5F, -7.0F, -3.0F, 13.0F, 4.0F, 7.0F, new CubeDeformation(0.0F))
			.texOffs(0, 0).addBox(-2.5F, -7.0F, -6.0F, 7.0F, 4.0F, 13.0F, new CubeDeformation(0.0F)),
			PartPose.offset(-1.0F, -8.0F, 0.0F));
		PartDefinition part4 = part3.addOrReplaceChild(PART_4, CubeListBuilder.create()
			.texOffs(0, 42).addBox(-6.0F, -2.0F, -4.0F, 12.0F, 2.0F, 8.0F, new CubeDeformation(0.0F))
			.texOffs(0, 17).addBox(-4.0F, -2.0F, -6.0F, 8.0F, 2.0F, 12.0F, new CubeDeformation(0.0F))
			.texOffs(76, 0).addBox(-5.0F, -4.0F, -3.0F, 10.0F, 2.0F, 6.0F, new CubeDeformation(0.0F))
			.texOffs(36, 52).addBox(-3.0F, -4.0F, -5.0F, 6.0F, 2.0F, 10.0F, new CubeDeformation(0.0F))
			.texOffs(40, 29).addBox(-4.0F, -5.0F, -2.0F, 9.0F, 1.0F, 5.0F, new CubeDeformation(0.0F))
			.texOffs(40, 13).addBox(-2.0F, -5.0F, -4.0F, 5.0F, 1.0F, 9.0F, new CubeDeformation(0.0F))
			.texOffs(40, 42).addBox(-3.0F, -6.0F, -2.0F, 7.0F, 1.0F, 5.0F, new CubeDeformation(0.0F))
			.texOffs(104, 17).addBox(-2.0F, -6.0F, -3.0F, 5.0F, 1.0F, 7.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.5F, -7.0F, 0.0F));
		return LayerDefinition.create(mesh, 128, 64);
	}
}
