package com.abyssia.client.entity.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Generated by tools/bbmodel-generator (abyssal_grenadier.bbmodel, template fish, seed 1).
 * Texture 64x32 UV (64x32 px): textures/entity/abyssal_grenadier.png.
 * Regenerate with: node tools/bbmodel-generator/cli.js abyssal_grenadier
 */
public final class AbyssalGrenadierGeometry
{
	public static final String ABYSSAL_GRENADIER = "abyssal_grenadier";
	public static final String BODY = "body";
	public static final String HEAD = "head";
	public static final String SNOUT = "snout";
	public static final String MOUTH = "mouth";
	public static final String UPPER_TEETH = "upper_teeth";
	public static final String RIGHT_EYE = "right_eye";
	public static final String LEFT_EYE = "left_eye";
	public static final String RIGHT_FIN = "right_fin";
	public static final String LEFT_FIN = "left_fin";
	public static final String RIGHT_PELVIC_FIN = "right_pelvic_fin";
	public static final String LEFT_PELVIC_FIN = "left_pelvic_fin";
	public static final String DORSAL_FIN = "dorsal_fin";
	public static final String ANAL_FIN = "anal_fin";
	public static final String TAIL = "tail";
	public static final String TAIL_2 = "tail_2";
	public static final String TAIL_3 = "tail_3";
	public static final String TAIL_4 = "tail_4";
	public static final String TAIL_FIN = "tail_fin";

	private AbyssalGrenadierGeometry()
	{
	}

	public static LayerDefinition create()
	{
		MeshDefinition mesh = new MeshDefinition();
		PartDefinition root = mesh.getRoot();
		PartDefinition abyssalGrenadier = root.addOrReplaceChild(ABYSSAL_GRENADIER, CubeListBuilder.create(),
			PartPose.offset(0.0F, 24.0F, 0.0F));
		PartDefinition body = abyssalGrenadier.addOrReplaceChild(BODY, CubeListBuilder.create()
			.texOffs(0, 11).addBox(-2.5F, -2.0F, -1.0F, 5.0F, 4.0F, 7.0F, new CubeDeformation(0.0F))
			.texOffs(26, 0).addBox(-1.5F, -3.0F, -1.0F, 3.0F, 1.0F, 6.0F, new CubeDeformation(0.0F))
			.texOffs(24, 11).addBox(-1.5F, 2.0F, -1.0F, 3.0F, 1.0F, 6.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -5.2214F, -7.0F));
		PartDefinition head = body.addOrReplaceChild(HEAD, CubeListBuilder.create()
			.texOffs(0, 0).addBox(-3.0F, -3.0F, -7.0F, 6.0F, 4.0F, 7.0F, new CubeDeformation(0.0F))
			.texOffs(44, 0).addBox(-2.0F, -4.0F, -6.0F, 4.0F, 1.0F, 5.0F, new CubeDeformation(0.0F))
			.texOffs(24, 18).addBox(-1.0F, 1.0F, -4.0F, 2.0F, 1.0F, 3.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 0.0F));
		PartDefinition snout = head.addOrReplaceChild(SNOUT, CubeListBuilder.create()
			.texOffs(52, 15).addBox(-1.5F, -1.0F, -2.0F, 3.0F, 2.0F, 3.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -2.0F, -7.0F));
		PartDefinition mouth = head.addOrReplaceChild(MOUTH, CubeListBuilder.create()
			.texOffs(0, 22).addBox(-2.0F, 0.0F, -5.0F, 4.0F, 2.0F, 6.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 1.0F, -1.0F));
		PartDefinition upperTeeth = head.addOrReplaceChild(UPPER_TEETH, CubeListBuilder.create()
			.texOffs(50, 15).addBox(-1.0F, 0.0F, 1.5F, 1.0F, 1.0F, 0.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 1.0F, -7.0F));
		PartDefinition rightEye = head.addOrReplaceChild(RIGHT_EYE, CubeListBuilder.create()
			.texOffs(34, 7).addBox(-1.0F, -1.0F, -1.0F, 2.0F, 2.0F, 2.0F, new CubeDeformation(0.0F)),
			PartPose.offset(-3.0F, -2.0F, -4.0F));
		PartDefinition leftEye = head.addOrReplaceChild(LEFT_EYE, CubeListBuilder.create()
			.texOffs(26, 7).addBox(-1.0F, -1.0F, -1.0F, 2.0F, 2.0F, 2.0F, new CubeDeformation(0.0F)),
			PartPose.offset(3.0F, -2.0F, -4.0F));
		PartDefinition rightFin = body.addOrReplaceChild(RIGHT_FIN, CubeListBuilder.create()
			.texOffs(8, 26).addBox(0.0F, -1.0F, -1.0F, 0.0F, 2.0F, 4.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(-2.5F, 0.0F, 0.0F, 0.0F, -0.5236F, -0.3491F));
		PartDefinition leftFin = body.addOrReplaceChild(LEFT_FIN, CubeListBuilder.create()
			.texOffs(0, 26).addBox(0.0F, -1.0F, -1.0F, 0.0F, 2.0F, 4.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(2.5F, 0.0F, 0.0F, 0.0F, 0.5236F, 0.3491F));
		PartDefinition rightPelvicFin = body.addOrReplaceChild(RIGHT_PELVIC_FIN, CubeListBuilder.create()
			.texOffs(60, 4).addBox(0.0F, -1.0F, -1.0F, 0.0F, 3.0F, 2.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(-1.5F, 3.0F, 1.0F, 0.3491F, -0.3491F, 0.0F));
		PartDefinition leftPelvicFin = body.addOrReplaceChild(LEFT_PELVIC_FIN, CubeListBuilder.create()
			.texOffs(34, 16).addBox(0.0F, -1.0F, -1.0F, 0.0F, 3.0F, 2.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(1.5F, 3.0F, 1.0F, 0.3491F, 0.3491F, 0.0F));
		PartDefinition dorsalFin = body.addOrReplaceChild(DORSAL_FIN, CubeListBuilder.create()
			.texOffs(38, 22).addBox(0.0F, -4.0F, 0.0F, 0.0F, 5.0F, 3.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -3.0F, 0.0F));
		PartDefinition analFin = body.addOrReplaceChild(ANAL_FIN, CubeListBuilder.create()
			.texOffs(42, 11).addBox(0.0F, -1.0F, 0.0F, 0.0F, 3.0F, 4.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 3.0F, 2.0F));
		PartDefinition tail = body.addOrReplaceChild(TAIL, CubeListBuilder.create()
			.texOffs(20, 22).addBox(-2.0F, -3.0F, 0.0F, 4.0F, 5.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 5.0F));
		PartDefinition tail2 = tail.addOrReplaceChild(TAIL_2, CubeListBuilder.create()
			.texOffs(44, 6).addBox(-1.5F, -2.0F, 0.0F, 3.0F, 4.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 4.0F));
		PartDefinition tail3 = tail2.addOrReplaceChild(TAIL_3, CubeListBuilder.create()
			.texOffs(38, 18).addBox(-1.0F, -1.0F, 0.0F, 2.0F, 2.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 4.0F));
		PartDefinition tail4 = tail3.addOrReplaceChild(TAIL_4, CubeListBuilder.create()
			.texOffs(52, 20).addBox(-0.5F, -1.0F, 0.0F, 1.0F, 1.0F, 4.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 4.0F));
		PartDefinition tailFin = tail4.addOrReplaceChild(TAIL_FIN, CubeListBuilder.create()
			.texOffs(34, 19).addBox(0.0F, -1.0F, -1.0F, 0.0F, 1.0F, 2.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 4.0F));
		return LayerDefinition.create(mesh, 64, 32);
	}
}
