package com.abyssia.client.entity.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Generated by tools/bbmodel-generator (helmet_jelly.bbmodel, template medusa, seed 1).
 * Texture 64x64 UV (64x64 px): textures/entity/helmet_jelly.png, glow mask textures/entity/helmet_jelly_glow.png.
 * Regenerate with: node tools/bbmodel-generator/cli.js helmet_jelly
 */
public final class HelmetJellyGeometry
{
	public static final String HELMET_JELLY = "helmet_jelly";
	public static final String BELL = "bell";
	public static final String STOMACH = "stomach";
	public static final String GROOVE_1 = "groove_1";
	public static final String GROOVE_2 = "groove_2";
	public static final String GROOVE_3 = "groove_3";
	public static final String GROOVE_4 = "groove_4";
	public static final String GROOVE_5 = "groove_5";
	public static final String GROOVE_6 = "groove_6";
	public static final String GROOVE_7 = "groove_7";
	public static final String GROOVE_8 = "groove_8";
	public static final String LAPPETS_FRONT = "lappets_front";
	public static final String LAPPETS_RIGHT = "lappets_right";
	public static final String LAPPETS_BACK = "lappets_back";
	public static final String LAPPETS_LEFT = "lappets_left";
	public static final String TENTACLE_1 = "tentacle_1";
	public static final String TENTACLE_1_S2 = "tentacle_1_s2";
	public static final String TENTACLE_2 = "tentacle_2";
	public static final String TENTACLE_2_S2 = "tentacle_2_s2";
	public static final String TENTACLE_3 = "tentacle_3";
	public static final String TENTACLE_3_S2 = "tentacle_3_s2";
	public static final String TENTACLE_4 = "tentacle_4";
	public static final String TENTACLE_4_S2 = "tentacle_4_s2";
	public static final String TENTACLE_5 = "tentacle_5";
	public static final String TENTACLE_5_S2 = "tentacle_5_s2";
	public static final String TENTACLE_6 = "tentacle_6";
	public static final String TENTACLE_6_S2 = "tentacle_6_s2";
	public static final String TENTACLE_7 = "tentacle_7";
	public static final String TENTACLE_7_S2 = "tentacle_7_s2";
	public static final String TENTACLE_8 = "tentacle_8";
	public static final String TENTACLE_8_S2 = "tentacle_8_s2";
	public static final String TENTACLE_9 = "tentacle_9";
	public static final String TENTACLE_9_S2 = "tentacle_9_s2";
	public static final String TENTACLE_10 = "tentacle_10";
	public static final String TENTACLE_10_S2 = "tentacle_10_s2";
	public static final String TENTACLE_11 = "tentacle_11";
	public static final String TENTACLE_11_S2 = "tentacle_11_s2";
	public static final String TENTACLE_12 = "tentacle_12";
	public static final String TENTACLE_12_S2 = "tentacle_12_s2";

	private HelmetJellyGeometry()
	{
	}

	public static LayerDefinition create()
	{
		MeshDefinition mesh = new MeshDefinition();
		PartDefinition root = mesh.getRoot();
		PartDefinition helmetJelly = root.addOrReplaceChild(HELMET_JELLY, CubeListBuilder.create(),
			PartPose.offset(0.0F, 24.0F, 0.0F));
		PartDefinition bell = helmetJelly.addOrReplaceChild(BELL, CubeListBuilder.create()
			.texOffs(0, 0).addBox(-5.0F, -3.0F, -5.0F, 10.0F, 3.0F, 10.0F, new CubeDeformation(0.0F))
			.texOffs(0, 13).addBox(-4.0F, -6.0F, -4.0F, 8.0F, 3.0F, 8.0F, new CubeDeformation(0.0F))
			.texOffs(32, 14).addBox(-3.0F, -9.0F, -3.0F, 6.0F, 3.0F, 6.0F, new CubeDeformation(0.0F))
			.texOffs(40, 25).addBox(-2.0F, -12.0F, -2.0F, 4.0F, 3.0F, 4.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 0.0F));
		PartDefinition stomach = bell.addOrReplaceChild(STOMACH, CubeListBuilder.create()
			.texOffs(40, 0).addBox(-3.0F, -8.0F, -3.0F, 6.0F, 8.0F, 6.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -1.0F, 0.0F));
		PartDefinition groove1 = bell.addOrReplaceChild(GROOVE_1, CubeListBuilder.create()
			.texOffs(20, 24).addBox(-2.5F, -1.0F, 0.0F, 5.0F, 1.0F, 0.0F, new CubeDeformation(0.0F)),
			PartPose.offset(2.5F, -1.0F, -5.05F));
		PartDefinition groove2 = bell.addOrReplaceChild(GROOVE_2, CubeListBuilder.create()
			.texOffs(52, 23).addBox(-2.5F, -1.0F, 0.0F, 5.0F, 1.0F, 0.0F, new CubeDeformation(0.0F)),
			PartPose.offset(-2.5F, -1.0F, -5.05F));
		PartDefinition groove3 = bell.addOrReplaceChild(GROOVE_3, CubeListBuilder.create()
			.texOffs(52, 19).addBox(0.0F, -1.0F, -2.5F, 0.0F, 1.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offset(-5.05F, -1.0F, -2.5F));
		PartDefinition groove4 = bell.addOrReplaceChild(GROOVE_4, CubeListBuilder.create()
			.texOffs(20, 22).addBox(0.0F, -1.0F, -2.5F, 0.0F, 1.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offset(-5.05F, -1.0F, 2.5F));
		PartDefinition groove5 = bell.addOrReplaceChild(GROOVE_5, CubeListBuilder.create()
			.texOffs(30, 27).addBox(-2.5F, -1.0F, 0.0F, 5.0F, 1.0F, 0.0F, new CubeDeformation(0.0F)),
			PartPose.offset(-2.5F, -1.0F, 5.05F));
		PartDefinition groove6 = bell.addOrReplaceChild(GROOVE_6, CubeListBuilder.create()
			.texOffs(0, 28).addBox(-2.5F, -1.0F, 0.0F, 5.0F, 1.0F, 0.0F, new CubeDeformation(0.0F)),
			PartPose.offset(2.5F, -1.0F, 5.05F));
		PartDefinition groove7 = bell.addOrReplaceChild(GROOVE_7, CubeListBuilder.create()
			.texOffs(10, 23).addBox(0.0F, -1.0F, -2.5F, 0.0F, 1.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offset(5.05F, -1.0F, 2.5F));
		PartDefinition groove8 = bell.addOrReplaceChild(GROOVE_8, CubeListBuilder.create()
			.texOffs(20, 23).addBox(0.0F, -1.0F, -2.5F, 0.0F, 1.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offset(5.05F, -1.0F, -2.5F));
		PartDefinition lappetsFront = bell.addOrReplaceChild(LAPPETS_FRONT, CubeListBuilder.create()
			.texOffs(0, 24).addBox(-5.0F, 0.0F, 0.0F, 10.0F, 2.0F, 0.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, -5.05F, -0.3142F, 0.0F, 0.0F));
		PartDefinition lappetsRight = bell.addOrReplaceChild(LAPPETS_RIGHT, CubeListBuilder.create()
			.texOffs(0, 16).addBox(0.0F, 0.0F, -5.0F, 0.0F, 2.0F, 10.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(-5.05F, 0.0F, 0.0F, 0.0F, 0.0F, 0.3142F));
		PartDefinition lappetsBack = bell.addOrReplaceChild(LAPPETS_BACK, CubeListBuilder.create()
			.texOffs(32, 23).addBox(-5.0F, 0.0F, 0.0F, 10.0F, 2.0F, 0.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 5.05F, 0.3142F, 0.0F, 0.0F));
		PartDefinition lappetsLeft = bell.addOrReplaceChild(LAPPETS_LEFT, CubeListBuilder.create()
			.texOffs(20, 15).addBox(0.0F, 0.0F, -5.0F, 0.0F, 2.0F, 10.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(5.05F, 0.0F, 0.0F, 0.0F, 0.0F, -0.3142F));
		PartDefinition tentacle1 = bell.addOrReplaceChild(TENTACLE_1, CubeListBuilder.create()
			.texOffs(56, 14).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 6.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(-4.5F, 0.0F, 1.0F, 0.1361F, 0.0F, 0.5061F));
		PartDefinition tentacle1S2 = tentacle1.addOrReplaceChild(TENTACLE_1_S2, CubeListBuilder.create()
			.texOffs(42, 32).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 6.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 6.0F, 0.0F, -0.0471F, 0.0F, -0.1763F));
		PartDefinition tentacle2 = bell.addOrReplaceChild(TENTACLE_2, CubeListBuilder.create()
			.texOffs(46, 32).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 6.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(-4.5F, 0.0F, 4.5F, 0.37F, 0.0F, 0.37F));
		PartDefinition tentacle2S2 = tentacle2.addOrReplaceChild(TENTACLE_2_S2, CubeListBuilder.create()
			.texOffs(50, 32).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 6.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 6.0F, 0.0F, -0.1292F, 0.0F, -0.1292F));
		PartDefinition tentacle3 = bell.addOrReplaceChild(TENTACLE_3, CubeListBuilder.create()
			.texOffs(54, 32).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 6.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(-1.0F, 0.0F, 4.5F, 0.5061F, 0.0F, 0.1361F));
		PartDefinition tentacle3S2 = tentacle3.addOrReplaceChild(TENTACLE_3_S2, CubeListBuilder.create()
			.texOffs(58, 32).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 6.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 6.0F, 0.0F, -0.1763F, 0.0F, -0.0471F));
		PartDefinition tentacle4 = bell.addOrReplaceChild(TENTACLE_4, CubeListBuilder.create()
			.texOffs(0, 39).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 6.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(1.0F, 0.0F, 4.5F, 0.5061F, 0.0F, -0.1361F));
		PartDefinition tentacle4S2 = tentacle4.addOrReplaceChild(TENTACLE_4_S2, CubeListBuilder.create()
			.texOffs(0, 29).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 6.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 6.0F, 0.0F, -0.1763F, 0.0F, 0.0471F));
		PartDefinition tentacle5 = bell.addOrReplaceChild(TENTACLE_5, CubeListBuilder.create()
			.texOffs(0, 46).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 6.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(4.5F, 0.0F, 4.5F, 0.37F, 0.0F, -0.37F));
		PartDefinition tentacle5S2 = tentacle5.addOrReplaceChild(TENTACLE_5_S2, CubeListBuilder.create()
			.texOffs(0, 53).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 6.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 6.0F, 0.0F, -0.1292F, 0.0F, 0.1292F));
		PartDefinition tentacle6 = bell.addOrReplaceChild(TENTACLE_6, CubeListBuilder.create()
			.texOffs(4, 39).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 6.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(4.5F, 0.0F, 1.0F, 0.1361F, 0.0F, -0.5061F));
		PartDefinition tentacle6S2 = tentacle6.addOrReplaceChild(TENTACLE_6_S2, CubeListBuilder.create()
			.texOffs(4, 29).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 6.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 6.0F, 0.0F, -0.0471F, 0.0F, 0.1763F));
		PartDefinition tentacle7 = bell.addOrReplaceChild(TENTACLE_7, CubeListBuilder.create()
			.texOffs(4, 46).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 6.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(4.5F, 0.0F, -1.0F, -0.1361F, 0.0F, -0.5061F));
		PartDefinition tentacle7S2 = tentacle7.addOrReplaceChild(TENTACLE_7_S2, CubeListBuilder.create()
			.texOffs(4, 53).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 6.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 6.0F, 0.0F, 0.0471F, 0.0F, 0.1763F));
		PartDefinition tentacle8 = bell.addOrReplaceChild(TENTACLE_8, CubeListBuilder.create()
			.texOffs(8, 29).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 6.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(4.5F, 0.0F, -4.5F, -0.37F, 0.0F, -0.37F));
		PartDefinition tentacle8S2 = tentacle8.addOrReplaceChild(TENTACLE_8_S2, CubeListBuilder.create()
			.texOffs(12, 29).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 6.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 6.0F, 0.0F, 0.1292F, 0.0F, 0.1292F));
		PartDefinition tentacle9 = bell.addOrReplaceChild(TENTACLE_9, CubeListBuilder.create()
			.texOffs(16, 29).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 6.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(1.0F, 0.0F, -4.5F, -0.5061F, 0.0F, -0.1361F));
		PartDefinition tentacle9S2 = tentacle9.addOrReplaceChild(TENTACLE_9_S2, CubeListBuilder.create()
			.texOffs(20, 29).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 6.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 6.0F, 0.0F, 0.1763F, 0.0F, 0.0471F));
		PartDefinition tentacle10 = bell.addOrReplaceChild(TENTACLE_10, CubeListBuilder.create()
			.texOffs(60, 14).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 6.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(-1.0F, 0.0F, -4.5F, -0.5061F, 0.0F, 0.1361F));
		PartDefinition tentacle10S2 = tentacle10.addOrReplaceChild(TENTACLE_10_S2, CubeListBuilder.create()
			.texOffs(56, 25).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 6.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 6.0F, 0.0F, 0.1763F, 0.0F, -0.0471F));
		PartDefinition tentacle11 = bell.addOrReplaceChild(TENTACLE_11, CubeListBuilder.create()
			.texOffs(60, 25).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 6.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(-4.5F, 0.0F, -4.5F, -0.37F, 0.0F, 0.37F));
		PartDefinition tentacle11S2 = tentacle11.addOrReplaceChild(TENTACLE_11_S2, CubeListBuilder.create()
			.texOffs(30, 28).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 6.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 6.0F, 0.0F, 0.1292F, 0.0F, -0.1292F));
		PartDefinition tentacle12 = bell.addOrReplaceChild(TENTACLE_12, CubeListBuilder.create()
			.texOffs(34, 28).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 6.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(-4.5F, 0.0F, -1.0F, -0.1361F, 0.0F, 0.5061F));
		PartDefinition tentacle12S2 = tentacle12.addOrReplaceChild(TENTACLE_12_S2, CubeListBuilder.create()
			.texOffs(38, 32).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 6.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 6.0F, 0.0F, 0.0471F, 0.0F, -0.1763F));
		return LayerDefinition.create(mesh, 64, 64);
	}
}
