"""Generates the Java registration of the species whose INFO has a "java" entry (the bulk-added fauna that use the
data-driven entity classes GenericSwimmer / GenericShark / GenericWalker / GenericMedusa / Tubeworm):

* src/main/java/com/abyssia/registry/GeneratedFauna.java           voices, traits, entity types, spawn eggs, prey
                                                                      tags, attributes, spawn placement list
* src/main/java/com/abyssia/client/entity/GeneratedFaunaRenderers.java  model layers and renderers (client only)

Called by gen_fauna.py after the models are synced (clip and bone names are checked against the generator
manifests). The 21 original species keep their hand-written classes and registrations.

INFO["java"] keys (all optional unless noted):
    kind       "swimmer" (default) | "shark" | "walker" | "medusa" | "sessile"
    size_m     real body length in metres: derives render scale, shadow and hitbox (see game_size)
    hitbox     (width, height) in blocks (overrides size_m); tracking: client tracking range (default 8)
    health, attack, armor
    traits     swimmer: steering=(pitch, yaw, thrust), zone=("open_water"|"near_floor"|"bottom", speed, chance),
               migrates=per_block, schools=radius, flees=(speed, distance), hunts=(reach, lunge, mouth_forward)
               [needs INFO prey], bite_clip, hangs_still=True, home=radius, ambient=interval
               shark: steering=(pitch, yaw, thrust), cruise_height, mouth_forward [needs INFO prey]
               walker: move_clip ("walk"), speed, wander (chance), home, ambient
               medusa: pulse_interval (ticks), pulse_strength
    render     scale=(scale, shadow) (overrides size_m), fish=True (tilts with swimming), pitch=True, translucent=[bones],
               eyeshine=(intensity, [bones]), glow=dict(bones=[bones], halos=[(bone, radius, r, g, b)], base, flicker)
"""
from __future__ import annotations

import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
JAVA = os.path.join(HERE, "..", "src", "main", "java", "com", "abyssia")
HEADER = ("// GENERATED by tools/gen_fauna.py (tools/fauna_java.py) from INFO[\"java\"] in tools/fauna/<id>.py.\n"
          "// DO NOT EDIT: change the species module and rerun `python tools/gen_fauna.py`.\n")

CLASSES = {"swimmer": "GenericSwimmer", "shark": "GenericShark", "walker": "GenericWalker", "medusa": "GenericMedusa",
           "sessile": "Tubeworm"}
ZONES = {"open_water": "OPEN_WATER", "near_floor": "NEAR_FLOOR", "bottom": "BOTTOM"}


def pascal(s):
    return "".join(w[:1].upper() + w[1:] for w in s.split("_"))


def const(s):
    return re.sub(r"[^A-Za-z0-9]+", "_", s).upper()


def f(x):
    """Java float literal."""
    return repr(float(x)) + "F"


def d(x):
    """Java double literal."""
    return repr(float(x))


def manifest(outputs, name):
    folder = outputs.get(name)
    if not folder:
        raise SystemExit(f"fauna_java: no generator output for {name}")
    with open(os.path.join(folder, name + ".json"), encoding="utf-8") as fh:
        return json.load(fh)


def game_size(j, man):
    """Render scale, shadow and hitbox from the real body length (INFO java size_m) and the model's size.

    In-game length ~ 1.4 * real_length_m ** 0.58 blocks: small animals stay visible, giants stay manageable, and the
    real size order is kept (35 cm viperfish -> 0.75 blocks, 3.5 m goblin shark -> 2.9 blocks, as hand-tuned before).
    Explicit render.scale / hitbox win.
    """
    sx, sy, sz = man["model"]["size_units"]
    longest = max(sx, sy, sz, 1)
    length = max(0.55, 1.4 * float(j["size_m"]) ** 0.58)  # small animals stay visible
    scale = length * 16 / longest
    w = min(2.5, max(0.2, max(sx, sz) * scale / 16 * 0.55))
    h = min(2.5, max(0.2, sy * scale / 16 * 0.8))
    return round(scale, 3), round(min(1.2, 0.25 * length + 0.05), 2), (round(w, 2), round(h, 2))


def traits_expr(name, j, voice):
    t = j.get("traits", {})
    parts = [f"SwimmerTraits.of({voice})"]
    if "steering" in t:
        p, y, th = t["steering"]
        parts.append(f".steering({int(p)}, {int(y)}, {f(th)})")
    if "zone" in t:
        z, speed, chance = t["zone"]
        parts.append(f".zone(SwimmerTraits.Zone.{ZONES[z]}, {d(speed)}, {int(chance)})")
    if t.get("migrates"):
        parts.append(f".migrates({d(t['migrates'])})")
    if t.get("schools"):
        parts.append(f".schools({d(t['schools'])})")
    if "flees" in t:
        sp, dist = t["flees"]
        parts.append(f".flees({d(sp)}, {int(dist)})")
    if "hunts" in t:
        r, l, m = t["hunts"]
        parts.append(f".hunts({const(name)}_PREY, {d(r)}, {d(l)}, {d(m)})")
    if t.get("bite_clip"):
        parts.append(f".biteClip(\"{t['bite_clip']}\")")
    if t.get("hangs_still"):
        parts.append(".hangsStill()")
    if t.get("home"):
        parts.append(f".home({int(t['home'])})")
    if t.get("ambient"):
        parts.append(f".ambient({int(t['ambient'])})")
    return "".join(parts)


def factory(name, j):
    kind = j.get("kind", "swimmer")
    c = const(name)
    t = j.get("traits", {})
    if kind == "swimmer":
        return f"(type, level) -> new GenericSwimmer(type, level, {c}_TRAITS)"
    if kind == "shark":
        p, y, th = t.get("steering", (12, 3, 0.003))
        return (f"(type, level) -> new GenericShark(type, level, {c}_VOICE, {int(p)}, {int(y)}, {f(th)}, {d(t.get('cruise_height', 3))}, "
                f"{c}_PREY, {d(t.get('mouth_forward', 0.8))})")
    if kind == "walker":
        return (f"(type, level) -> new GenericWalker(type, level, {c}_VOICE, \"{t.get('move_clip', 'walk')}\", {d(t.get('speed', 0.6))}, "
                f"{int(t.get('wander', 120))}, {int(t.get('home', 16))}, {int(t.get('ambient', 500))})")
    if kind == "medusa":
        return (f"(type, level) -> new GenericMedusa(type, level, {c}_VOICE, {int(t.get('pulse_interval', 60))}, "
                f"{d(t.get('pulse_strength', 0.04))})")
    if kind == "sessile":
        return f"(type, level) -> new Tubeworm(type, level, {c}_VOICE)"
    raise SystemExit(f"fauna_java: unknown kind {kind!r} for {name}")


def attributes_expr(j):
    kind = j.get("kind", "swimmer")
    cls = CLASSES[kind]
    if kind == "sessile":
        return "Tubeworm.createAttributes()"
    if kind == "medusa":
        return f"GenericMedusa.attributes({d(j.get('health', 6))})"
    return f"{cls}.attributes({d(j.get('health', 8))}, {d(j.get('attack', 0))}, {d(j.get('armor', 0))})"


def resolve_sizes(entries, outputs):
    """Fills render.scale and hitbox from size_m where they are not given explicitly."""
    for e in entries:
        j = e["java"]
        if "size_m" not in j and ("hitbox" not in j or "scale" not in j.get("render", {})):
            raise SystemExit(f"fauna_java: {e['name']} needs size_m (or explicit hitbox and render.scale)")
        if "size_m" in j:
            scale, shadow, hitbox = game_size(j, manifest(outputs, e["name"]))
            j.setdefault("hitbox", hitbox)
            j.setdefault("render", {}).setdefault("scale", (scale, shadow))


def registry_java(entries):
    L = [HEADER, "package com.abyssia.registry;", ""]
    used = sorted({CLASSES[e["java"].get("kind", "swimmer")] for e in entries} | ({"SwimmerTraits"} if any(e["java"].get("kind", "swimmer") == "swimmer" for e in entries) else set()))
    L += [f"import com.abyssia.entity.{c};" for c in used]
    L += ["import net.minecraft.tags.TagKey;", "import net.minecraft.world.entity.EntityType;", "import net.minecraft.world.entity.MobCategory;",
          "import net.minecraft.world.item.Item;", "import net.neoforged.neoforge.event.entity.EntityAttributeCreationEvent;",
          "import net.neoforged.neoforge.registries.DeferredHolder;", "import net.neoforged.neoforge.registries.DeferredItem;", "", "import java.util.List;", ""]
    L += ["/**", " * Registration of the species added through tools/fauna/&lt;id&gt;.py INFO[\"java\"] (data-driven entity classes).",
          " * Everything registers in static initialisers; {@link #init()} only forces the class to load from the mod constructor.",
          " */", "@SuppressWarnings(\"unused\")", "public final class GeneratedFauna", "{", "    private GeneratedFauna() {}", "",
          "    /** Loads this class (and with it every registration below). Called first in the mod constructor. */",
          "    public static void init() {}", ""]
    for e in entries:
        name, s, j = e["name"], e["module"], e["java"]
        c, kind = const(name), j.get("kind", "swimmer")
        en, ja = s.INFO["names"]
        kinds = ", ".join(f"\"{k}\"" for k in s.INFO["sounds"])
        L.append(f"    // ---- {name}: {en} / {ja}")
        L.append(f"    public static final ModSounds.Voice {c}_VOICE = ModSounds.voice(\"{name}\", {kinds});")
        if s.INFO.get("prey") is not None:
            L.append(f"    public static final TagKey<EntityType<?>> {c}_PREY = ModTags.entity(\"{name}_prey\");")
        elif kind == "shark" or "hunts" in j.get("traits", {}):
            raise SystemExit(f"fauna_java: {name} hunts but INFO has no prey list")
        if kind == "swimmer":
            L.append(f"    public static final SwimmerTraits {c}_TRAITS = {traits_expr(name, j, c + '_VOICE')};")
        cls = CLASSES[kind]
        w, h = j["hitbox"]
        L.append(f"    public static final DeferredHolder<EntityType<?>, EntityType<{cls}>> {c} = ModEntities.ENTITIES.register(\"{name}\",")
        L.append(f"            () -> EntityType.Builder.<{cls}>of({factory(name, j)}, MobCategory.WATER_CREATURE)")
        L.append(f"                    .sized({f(w)}, {f(h)}).clientTrackingRange({int(j.get('tracking', 8))}).build(\"{name}\"));")
        bg, hi = s.INFO["egg"]
        hexc = lambda c: f"0x{c:06X}" if isinstance(c, int) else "0x" + str(c).lstrip("#").upper()
        L.append(f"    public static final DeferredItem<Item> {c}_SPAWN_EGG = ModItems.spawnEgg(\"{name}_spawn_egg\", {c}, {hexc(bg)}, {hexc(hi)});")
        L.append("")
    L.append("    public static void attributes(EntityAttributeCreationEvent event)")
    L.append("    {")
    for e in entries:
        L.append(f"        event.put({const(e['name'])}.get(), {attributes_expr(e['java'])}.build());")
    L.append("    }")
    L.append("")
    L.append("    /** Entity types for the spawn placement registration (in water; the fauna spawner does the rest). */")
    L.append("    public static List<DeferredHolder<EntityType<?>, ? extends EntityType<?>>> types()")
    L.append("    {")
    L.append("        return List.of(" + ", ".join(const(e["name"]) for e in entries) + ");")
    L.append("    }")
    L.append("}")
    return "\n".join(L) + "\n"


def renderers_java(entries, outputs):
    L = [HEADER, "package com.abyssia.client.entity;", ""]
    imports = {"com.abyssia.Abyssia", "com.abyssia.registry.GeneratedFauna", "net.minecraft.client.model.geom.ModelLayerLocation",
               "net.minecraft.resources.ResourceLocation", "net.minecraft.util.Mth", "net.neoforged.neoforge.client.event.EntityRenderersEvent",
               "java.util.List", "java.util.Map", "java.util.Set"}
    for e in entries:
        p = pascal(e["name"])
        imports |= {f"com.abyssia.client.entity.model.{p}Geometry", f"com.abyssia.client.entity.model.{p}Animations",
                    f"com.abyssia.entity.{CLASSES[e['java'].get('kind', 'swimmer')]}"}
    L += [f"import {i};" for i in sorted(imports)] + [""]
    L += ["/** Model layers and renderers of the species in {@link GeneratedFauna}. Client only: called from ModEntityRenderers. */",
          "public final class GeneratedFaunaRenderers", "{", "    private GeneratedFaunaRenderers() {}", ""]
    for e in entries:
        L.append(f"    public static final ModelLayerLocation {const(e['name'])} = layer(\"{e['name']}\");")
    L += ["", "    private static ModelLayerLocation layer(String name)", "    {",
          "        return new ModelLayerLocation(ResourceLocation.fromNamespaceAndPath(Abyssia.MODID, name), \"main\");", "    }", "",
          "    public static void registerLayers(EntityRenderersEvent.RegisterLayerDefinitions event)", "    {"]
    for e in entries:
        L.append(f"        event.registerLayerDefinition({const(e['name'])}, {pascal(e['name'])}Geometry::create);")
    L += ["    }", "", "    public static void registerRenderers(EntityRenderersEvent.RegisterRenderers event)", "    {"]
    for e in entries:
        name, j = e["name"], e["java"]
        c, p, cls = const(name), pascal(name), CLASSES[j.get("kind", "swimmer")]
        man = manifest(outputs, name)
        clips = [a["name"] for a in man.get("animations", [])]
        bones = {b["name"] for b in man.get("bones", [])}
        r = j["render"]

        def bone(b):
            if b not in bones:
                raise SystemExit(f"fauna_java: {name}: bone {b!r} not in the model ({', '.join(sorted(bones))})")
            return f"{p}Geometry.{const(b)}"

        clip_map = ", ".join(f"Map.entry(\"{cl}\", {p}Animations.{const(cl)})" for cl in clips)
        translucent = ", ".join(bone(b) for b in r.get("translucent", []))
        L.append(f"        // {e['module'].INFO['names'][0]} / {e['module'].INFO['names'][1]}")
        L.append(f"        event.registerEntityRenderer(GeneratedFauna.{c}.get(), FaunaRenderer.<{cls}>spec(\"{name}\", {c},")
        L.append(f"                        root -> new FaunaModel<>(root, {p}Geometry.{c}, Map.ofEntries({clip_map}),")
        L.append(f"                                Set.of({translucent}), {'true' if r.get('pitch', True) else 'false'}))")
        sc, sh = r["scale"]
        chain = f"                .scale({f(sc)}, {f(sh)})"
        if r.get("fish", True):
            chain += ".fish()"
        L.append(chain)
        g = r.get("glow")
        if g:
            glow_bones = ", ".join(bone(b) for b in g["bones"])
            halos = ", ".join(f"new FaunaGlowLayer.Halo({bone(h[0])}, {f(h[1])}, {f(h[2])}, {f(h[3])}, {f(h[4])})" for h in g.get("halos", []))
            base, flick = g.get("base", 0.8), g.get("flicker", 0.15)
            L.append(f"                .light(List.of({glow_bones}), List.of({halos}),")
            L.append(f"                        (e, partial, age) -> new float[]{{1.0F, 1.0F, 1.0F, e.isInWater() ? {f(base)} + {f(flick)} * Mth.sin(age * 0.08F + e.getId()) : 0.2F}})")
        if r.get("eyeshine"):
            inten, eyes = r["eyeshine"]
            L.append(f"                .eyeshine({f(inten)}, {', '.join(bone(b) for b in eyes)})")
        L.append("                .provider());")
    L += ["    }", "}"]
    return "\n".join(L) + "\n"


def generate(species, sid, outputs):
    entries = [dict(name=sid(s), module=s, java=s.INFO["java"]) for s in species if "java" in s.INFO]
    entries.sort(key=lambda e: e["name"])
    resolve_sizes(entries, outputs)
    with open(os.path.join(JAVA, "registry", "GeneratedFauna.java"), "w", encoding="utf-8", newline="\n") as fh:
        fh.write(registry_java(entries))
    with open(os.path.join(JAVA, "client", "entity", "GeneratedFaunaRenderers.java"), "w", encoding="utf-8", newline="\n") as fh:
        fh.write(renderers_java(entries, outputs))
    print(f"  java registration for {len(entries)} data-driven species")
