"""Generates the resource-plant side of Abyssia from plant_defs.py; run by gen_deep_assets.py (never by hand-edits).

Writes:
* src/main/java/com/abyssia/registry/ModPlants.java  - new plant blocks + material items (growth, light, rarity, fuel)
* blockstates / block + item models for the new plants, item models for the materials (textures: plant_textures.py)
* loot_tables/blocks/<plant>.json  - the plant itself + its material drops (ripe / column tip only)
* loot_tables/harvest/<plant>.json - right-click harvest of a ripe resource plant (shears add one more)
* recipes/<id>.json                - processing and crafting (plant_defs.RECIPES)
* names for lang() (NAMES, ITEM_NAMES incl. "<material>.source" tooltip lines)

    python tools/plant_assets.py --check   # plant ids vs ModBlocks / ModPlants, catalogue checks (JSON)
"""
from __future__ import annotations

import json
import os
import re
import sys

import plant_defs as pd

HERE = os.path.dirname(os.path.abspath(__file__))
JAVA = os.path.join(HERE, "..", "src", "main", "java", "com", "abyssia", "registry")
RARITY_JAVA = {"common": "COMMON", "uncommon": "UNCOMMON", "rare": "RARE", "very_rare": "EPIC"}
# Plant state that marks the block whose drops roll: ripe resource plants, column tops, hanging tips.
PER_STATE = {"top": {"top": "true"}, "tip": {"tip": "true"}}

BLOCK_NAMES = {p.id: (p.en, p.ja) for p in pd.NEW_PLANTS}
ITEM_NAMES = {m.id: (m.en, m.ja) for m in pd.MATERIALS}
ITEM_NAMES.update({m.id + ".source": (m.source_en, m.source_ja) for m in pd.MATERIALS if m.source_en})


def ref(n: str) -> str:
    return "abyssia:block/" + n


def const(n: str) -> str:
    return n.upper()


# ================================================================ Java registry

def java_block(p: pd.Plant) -> str:
    props = f"ModBlocks.plantProps(MapColor.{p.colour}, 0)"
    if p.light:
        props += f".lightLevel(s -> s.getValue(ResourcePlantBlock.RIPE) ? {p.light} : 0)"
    spores = "SporeEmitter.GLOW_DUST" if p.category == "luminous" else "SporeEmitter.NONE"
    if p.harvest:
        make = f"new ResourcePlantBlock({props}, {spores}, {p.growth}f)"
    elif p.form == "hanging":
        make = f"new HangingPlantBlock({props}, 10, {spores})"
    elif p.form == "column":
        make = f"new StackingPlantBlock({props}, 6, false, {spores})"
    else:
        make = f"new UnderwaterPlantBlock({props}, {spores})"
    return f'    public static final RegistryObject<Block> {const(p.id)} = ModBlocks.block("{p.id}", () -> {make});'


def java_item(m: pd.Material) -> str:
    cls = "ResinItem" if m.id == "plant_resin" else "MaterialItem"
    props = f"new Item.Properties().rarity(Rarity.{RARITY_JAVA[m.rarity]})"
    return (f'    public static final RegistryObject<Item> {const(m.id)} = ModItems.tabItem("{m.id}", '
            f'() -> new {cls}({props}, {m.burn}, {"true" if m.source_en else "false"}));')


def java_source() -> str:
    phase = lambda p: next(k for k, v in PHASES.items() if p.id in v)
    lines = [
        "package com.abyssia.registry;",
        "",
        "import com.abyssia.block.HangingPlantBlock;",
        "import com.abyssia.block.ResourcePlantBlock;",
        "import com.abyssia.block.SporeEmitter;",
        "import com.abyssia.block.StackingPlantBlock;",
        "import com.abyssia.block.UnderwaterPlantBlock;",
        "import com.abyssia.item.MaterialItem;",
        "import com.abyssia.item.ResinItem;",
        "import net.minecraft.world.item.Item;",
        "import net.minecraft.world.item.Rarity;",
        "import net.minecraft.world.level.block.Block;",
        "import net.minecraft.world.level.material.MapColor;",
        "import net.minecraftforge.registries.RegistryObject;",
        "",
        "/**",
        " * Resource plants and their materials. GENERATED by tools/plant_assets.py from tools/plant_defs.py: edit the",
        " * table there and rerun tools/gen_deep_assets.py. Existing plants that also yield materials stay in ModBlocks;",
        " * only their loot tables change.",
        " */",
        "public final class ModPlants",
        "{",
    ]
    current = None
    for p in pd.NEW_PLANTS:
        if phase(p) != current:
            current = phase(p)
            lines.append(f"    // ---------- {current}")
        lines.append(java_block(p))
    lines.append("")
    for stage in ("base", "processed"):
        lines.append(f"    // ---------- materials: {stage}")
        lines += [java_item(m) for m in pd.MATERIALS if m.stage == stage]
    lines += ["", "    private ModPlants() {}", "", "    /** Loads the class, so the entries above join ModBlocks' and ModItems' registers. */",
              "    static void init() {}", "}", ""]
    return "\n".join(lines)


PHASES = {
    "Phase 1: fiber, resin, hard, luminous": {"strandweed", "amber_fan", "resin_root", "knotstalk", "lumen_quill"},
    "Phase 2: oil, crystal symbiosis": {"oil_bladder_weed", "glasslace"},
    "Phase 3: mud and volcanic flora": {"silt_comb", "cinder_stalk"},
    "Phase 4: hadal": {"pressure_gourd"},
}


# ================================================================ models

def models(write, bs, bm, im, cross_model, glowing: set[str]):
    for p in pd.NEW_PLANTS:
        n = p.id
        g = lambda t: ref(t + "_glow") if t in glowing else None
        if p.harvest:
            write(bs(n), {"variants": {"ripe=true": {"model": ref(n + "_ripe")}, "ripe=false": {"model": ref(n)}}})
            write(bm(n + "_ripe"), cross_model(ref(n + "_ripe"), g(n + "_ripe")))
            write(bm(n), cross_model(ref(n), g(n)))
            icon = n + "_ripe"
        elif p.form in ("column", "hanging"):
            end = "top" if p.form == "column" else "tip"
            write(bs(n), {"variants": {f"{end}=true": {"model": ref(f"{n}_{end}")}, f"{end}=false": {"model": ref(n)}}})
            write(bm(f"{n}_{end}"), cross_model(ref(f"{n}_{end}")))
            write(bm(n), cross_model(ref(n)))
            icon = f"{n}_{end}"
        else:
            write(bs(n), {"variants": {"": {"model": ref(n)}}})
            write(bm(n), cross_model(ref(n)))
            icon = n
        write(im(n), {"parent": "minecraft:item/generated", "textures": {"layer0": ref(icon)}})
    for m in pd.MATERIALS:
        write(im(m.id), {"parent": "minecraft:item/generated", "textures": {"layer0": "abyssia:item/" + m.id}})


# ================================================================ loot

def _entry(d: pd.Drop) -> dict:
    e = {"type": "minecraft:item", "name": d.id}
    funcs = []
    if (d.min, d.max) != (1, 1):
        funcs.append({"function": "minecraft:set_count", "count": {"type": "minecraft:uniform", "min": d.min, "max": d.max}})
    funcs.append({"function": "minecraft:explosion_decay"})
    e["functions"] = funcs
    return e


def _pool(d: pd.Drop, conditions: list) -> dict:
    conds = list(conditions)
    if d.chance < 1.0:
        conds.append({"condition": "minecraft:random_chance", "chance": d.chance})
    pool = {"rolls": 1, "bonus_rolls": 0, "entries": [_entry(d)]}
    if conds:
        pool["conditions"] = conds
    return pool


def _state(block: str, props: dict) -> dict:
    return {"condition": "minecraft:block_state_property", "block": "abyssia:" + block, "properties": props}


def loot_tables(write, data_dir: str):
    blocks = lambda n: os.path.join(data_dir, "abyssia", "loot_tables", "blocks", n + ".json")
    harvest = lambda n: os.path.join(data_dir, "abyssia", "loot_tables", "harvest", n + ".json")
    for p in pd.PLANTS:
        drop_self = "void_kelp" if p.id == "void_kelp_plant" else p.id
        pools = [{"rolls": 1, "bonus_rolls": 0, "entries": [{"type": "minecraft:item", "name": "abyssia:" + drop_self}],
                  "conditions": [{"condition": "minecraft:survives_explosion"}]}]
        when = []
        if p.harvest:
            when = [_state(p.id, {"ripe": "true"})]
        elif p.per in PER_STATE:
            when = [_state(p.id, PER_STATE[p.per])]
        pools += [_pool(d, when) for d in p.drops]
        write(blocks(p.id), {"type": "minecraft:block", "pools": pools, "random_sequence": "abyssia:blocks/" + p.id})
        if p.harvest:
            hp = [_pool(d, []) for d in p.harvest]
            shears = {"condition": "minecraft:match_tool", "predicate": {"items": ["minecraft:shears"]}}
            hp.append({"rolls": 1, "bonus_rolls": 0, "entries": [{"type": "minecraft:item", "name": p.harvest[0].id}],
                       "conditions": [shears]})
            write(harvest(p.id), {"type": "minecraft:block", "pools": hp, "random_sequence": "abyssia:harvest/" + p.id})


# ================================================================ recipes

def _ing(n: str) -> dict:
    return {"item": pd._i(n)}


def recipes(write, data_dir: str):
    rd = lambda n: os.path.join(data_dir, "abyssia", "recipes", n + ".json")
    for rid, kind, s in pd.RECIPES:
        if kind == "shaped":
            out = {"type": "minecraft:crafting_shaped", "category": "misc", "pattern": s["pattern"],
                   "key": {k: _ing(v) for k, v in s["key"].items()}, "result": {"item": pd._i(s["result"]), "count": s["count"]}}
        elif kind == "shapeless":
            out = {"type": "minecraft:crafting_shapeless", "category": "misc", "ingredients": [_ing(i) for i in s["ingredients"]],
                   "result": {"item": pd._i(s["result"]), "count": s["count"]}}
        elif kind == "smelting":
            out = {"type": "minecraft:smelting", "category": "misc", "ingredient": _ing(s["ingredient"]),
                   "result": pd._i(s["result"]), "experience": s["xp"], "cookingtime": 200}
        else:
            raise ValueError(kind)
        write(rd(rid), out)


# ================================================================ entry point (called by gen_deep_assets.main)

def generate(write, bs, bm, im, cross_model, data_dir: str) -> dict:
    import plant_textures
    plant_textures.run(quiet=True)
    models(write, bs, bm, im, cross_model, plant_textures.glowing())
    loot_tables(write, data_dir)
    recipes(write, data_dir)
    with open(os.path.join(JAVA, "ModPlants.java"), "w", encoding="utf-8", newline="\n") as f:
        f.write(java_source())
    errors = check()
    if errors:
        raise SystemExit("plant_assets: " + "; ".join(errors))
    return {"new_plants": len(pd.NEW_PLANTS), "plants": len(pd.PLANTS), "materials": len(pd.MATERIALS), "recipes": len(pd.RECIPES)}


def check() -> list[str]:
    errors = pd.check()
    registry = open(os.path.join(JAVA, "ModBlocks.java"), encoding="utf-8").read()
    for p in pd.PLANTS:
        if not p.new and not re.search(r'"%s"' % re.escape(p.id), registry):
            errors.append(f"{p.id}: not registered in ModBlocks")
    return errors


if __name__ == "__main__":
    errs = check()
    print(json.dumps({"ok": not errs, "errors": errs}, indent=1))
    sys.exit(1 if errs else 0)
