package com.abyssia.client.entity.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Generated by tools/bbmodel-generator (giant_sea_spider.bbmodel, template parts, seed 1).
 * Texture 64x32 UV (64x32 px): textures/entity/giant_sea_spider.png.
 * Regenerate with: node tools/bbmodel-generator/cli.js giant_sea_spider
 */
public final class GiantSeaSpiderGeometry
{
	public static final String GIANT_SEA_SPIDER = "giant_sea_spider";
	public static final String TRUNK = "trunk";
	public static final String PROBOSCIS = "proboscis";
	public static final String EYE_TUBERCLE = "eye_tubercle";
	public static final String PALP_RIGHT = "palp_right";
	public static final String PALP_RIGHT_2 = "palp_right_2";
	public static final String PALP_LEFT = "palp_left";
	public static final String PALP_LEFT_2 = "palp_left_2";
	public static final String ABDOMEN = "abdomen";
	public static final String LEG_FRONT_RIGHT = "leg_front_right";
	public static final String LEG_FRONT_RIGHT_2 = "leg_front_right_2";
	public static final String LEG_FRONT_RIGHT_3 = "leg_front_right_3";
	public static final String LEG_FRONT_LEFT = "leg_front_left";
	public static final String LEG_FRONT_LEFT_2 = "leg_front_left_2";
	public static final String LEG_FRONT_LEFT_3 = "leg_front_left_3";
	public static final String LEG_MID_RIGHT = "leg_mid_right";
	public static final String LEG_MID_RIGHT_2 = "leg_mid_right_2";
	public static final String LEG_MID_RIGHT_3 = "leg_mid_right_3";
	public static final String LEG_MID_LEFT = "leg_mid_left";
	public static final String LEG_MID_LEFT_2 = "leg_mid_left_2";
	public static final String LEG_MID_LEFT_3 = "leg_mid_left_3";
	public static final String LEG_REAR_RIGHT = "leg_rear_right";
	public static final String LEG_REAR_RIGHT_2 = "leg_rear_right_2";
	public static final String LEG_REAR_RIGHT_3 = "leg_rear_right_3";
	public static final String LEG_REAR_LEFT = "leg_rear_left";
	public static final String LEG_REAR_LEFT_2 = "leg_rear_left_2";
	public static final String LEG_REAR_LEFT_3 = "leg_rear_left_3";
	public static final String LEG_HIND_RIGHT = "leg_hind_right";
	public static final String LEG_HIND_RIGHT_2 = "leg_hind_right_2";
	public static final String LEG_HIND_RIGHT_3 = "leg_hind_right_3";
	public static final String LEG_HIND_LEFT = "leg_hind_left";
	public static final String LEG_HIND_LEFT_2 = "leg_hind_left_2";
	public static final String LEG_HIND_LEFT_3 = "leg_hind_left_3";

	private GiantSeaSpiderGeometry()
	{
	}

	public static LayerDefinition create()
	{
		MeshDefinition mesh = new MeshDefinition();
		PartDefinition root = mesh.getRoot();
		PartDefinition giantSeaSpider = root.addOrReplaceChild(GIANT_SEA_SPIDER, CubeListBuilder.create(),
			PartPose.offset(0.0F, 24.0F, 0.0F));
		PartDefinition trunk = giantSeaSpider.addOrReplaceChild(TRUNK, CubeListBuilder.create()
			.texOffs(44, 0).addBox(-1.0F, -1.0F, -8.0F, 2.0F, 2.0F, 8.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -2.8868F, 6.0F));
		PartDefinition proboscis = trunk.addOrReplaceChild(PROBOSCIS, CubeListBuilder.create()
			.texOffs(44, 10).addBox(-1.0F, -1.0F, -5.0F, 2.0F, 2.0F, 5.0F, new CubeDeformation(0.0F))
			.texOffs(58, 10).addBox(-1.0F, -1.0F, -7.0F, 1.0F, 1.0F, 2.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, -8.0F));
		PartDefinition eyeTubercle = trunk.addOrReplaceChild(EYE_TUBERCLE, CubeListBuilder.create()
			.texOffs(58, 13).addBox(-1.0F, -1.0F, 0.0F, 1.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -1.0F, -7.0F));
		PartDefinition palpRight = trunk.addOrReplaceChild(PALP_RIGHT, CubeListBuilder.create()
			.texOffs(22, 22).addBox(-0.5F, -1.0F, -4.0F, 1.0F, 1.0F, 4.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(-0.5F, 0.0F, -8.0F, -0.3491F, 0.3491F, 0.0F));
		PartDefinition palpRight2 = palpRight.addOrReplaceChild(PALP_RIGHT_2, CubeListBuilder.create()
			.texOffs(22, 27).addBox(-0.5F, -1.0F, -4.0F, 1.0F, 1.0F, 4.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, -4.0F, -0.4363F, 0.0F, 0.0F));
		PartDefinition palpLeft = trunk.addOrReplaceChild(PALP_LEFT, CubeListBuilder.create()
			.texOffs(22, 17).addBox(-0.5F, -1.0F, -4.0F, 1.0F, 1.0F, 4.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.5F, 0.0F, -8.0F, -0.3491F, -0.3491F, 0.0F));
		PartDefinition palpLeft2 = palpLeft.addOrReplaceChild(PALP_LEFT_2, CubeListBuilder.create()
			.texOffs(32, 16).addBox(-0.5F, -1.0F, -4.0F, 1.0F, 1.0F, 4.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, -4.0F, -0.4363F, 0.0F, 0.0F));
		PartDefinition abdomen = trunk.addOrReplaceChild(ABDOMEN, CubeListBuilder.create()
			.texOffs(32, 21).addBox(-1.0F, -1.0F, 0.0F, 1.0F, 1.0F, 3.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.3491F, 0.0F, 0.0F));
		PartDefinition legFrontRight = trunk.addOrReplaceChild(LEG_FRONT_RIGHT, CubeListBuilder.create()
			.texOffs(22, 2).addBox(-10.0F, -1.0F, 0.0F, 10.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(-1.0F, 0.0F, -7.0F, 0.0F, -0.6981F, 0.9599F));
		PartDefinition legFrontRight2 = legFrontRight.addOrReplaceChild(LEG_FRONT_RIGHT_2, CubeListBuilder.create()
			.texOffs(0, 4).addBox(-10.0F, -1.0F, 0.0F, 10.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(-10.0F, 0.0F, 0.0F, 0.0F, 0.0F, -0.9599F));
		PartDefinition legFrontRight3 = legFrontRight2.addOrReplaceChild(LEG_FRONT_RIGHT_3, CubeListBuilder.create()
			.texOffs(22, 4).addBox(-10.0F, -1.0F, 0.0F, 10.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(-10.0F, 0.0F, 0.0F, 0.0F, 0.0F, -0.9599F));
		PartDefinition legFrontLeft = trunk.addOrReplaceChild(LEG_FRONT_LEFT, CubeListBuilder.create()
			.texOffs(0, 0).addBox(0.0F, -1.0F, 0.0F, 10.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(1.0F, 0.0F, -7.0F, 0.0F, 0.6981F, -0.9599F));
		PartDefinition legFrontLeft2 = legFrontLeft.addOrReplaceChild(LEG_FRONT_LEFT_2, CubeListBuilder.create()
			.texOffs(22, 0).addBox(0.0F, -1.0F, 0.0F, 10.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(10.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.9599F));
		PartDefinition legFrontLeft3 = legFrontLeft2.addOrReplaceChild(LEG_FRONT_LEFT_3, CubeListBuilder.create()
			.texOffs(0, 2).addBox(0.0F, -1.0F, 0.0F, 10.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(10.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.9599F));
		PartDefinition legMidRight = trunk.addOrReplaceChild(LEG_MID_RIGHT, CubeListBuilder.create()
			.texOffs(0, 20).addBox(-10.0F, -1.0F, 0.0F, 10.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(-1.0F, 0.0F, -5.0F, 0.0F, -0.2269F, 0.9599F));
		PartDefinition legMidRight2 = legMidRight.addOrReplaceChild(LEG_MID_RIGHT_2, CubeListBuilder.create()
			.texOffs(0, 22).addBox(-10.0F, -1.0F, 0.0F, 10.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(-10.0F, 0.0F, 0.0F, 0.0F, 0.0F, -0.9599F));
		PartDefinition legMidRight3 = legMidRight2.addOrReplaceChild(LEG_MID_RIGHT_3, CubeListBuilder.create()
			.texOffs(0, 24).addBox(-10.0F, -1.0F, 0.0F, 10.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(-10.0F, 0.0F, 0.0F, 0.0F, 0.0F, -0.9599F));
		PartDefinition legMidLeft = trunk.addOrReplaceChild(LEG_MID_LEFT, CubeListBuilder.create()
			.texOffs(0, 14).addBox(0.0F, -1.0F, 0.0F, 10.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(1.0F, 0.0F, -5.0F, 0.0F, 0.2269F, -0.9599F));
		PartDefinition legMidLeft2 = legMidLeft.addOrReplaceChild(LEG_MID_LEFT_2, CubeListBuilder.create()
			.texOffs(0, 16).addBox(0.0F, -1.0F, 0.0F, 10.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(10.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.9599F));
		PartDefinition legMidLeft3 = legMidLeft2.addOrReplaceChild(LEG_MID_LEFT_3, CubeListBuilder.create()
			.texOffs(0, 18).addBox(0.0F, -1.0F, 0.0F, 10.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(10.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.9599F));
		PartDefinition legRearRight = trunk.addOrReplaceChild(LEG_REAR_RIGHT, CubeListBuilder.create()
			.texOffs(22, 10).addBox(-10.0F, -1.0F, 0.0F, 10.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(-1.0F, 0.0F, -3.0F, 0.0F, 0.2269F, 0.9599F));
		PartDefinition legRearRight2 = legRearRight.addOrReplaceChild(LEG_REAR_RIGHT_2, CubeListBuilder.create()
			.texOffs(22, 12).addBox(-10.0F, -1.0F, 0.0F, 10.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(-10.0F, 0.0F, 0.0F, 0.0F, 0.0F, -0.9599F));
		PartDefinition legRearRight3 = legRearRight2.addOrReplaceChild(LEG_REAR_RIGHT_3, CubeListBuilder.create()
			.texOffs(22, 14).addBox(-10.0F, -1.0F, 0.0F, 10.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(-10.0F, 0.0F, 0.0F, 0.0F, 0.0F, -0.9599F));
		PartDefinition legRearLeft = trunk.addOrReplaceChild(LEG_REAR_LEFT, CubeListBuilder.create()
			.texOffs(0, 26).addBox(0.0F, -1.0F, 0.0F, 10.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(1.0F, 0.0F, -3.0F, 0.0F, -0.2269F, -0.9599F));
		PartDefinition legRearLeft2 = legRearLeft.addOrReplaceChild(LEG_REAR_LEFT_2, CubeListBuilder.create()
			.texOffs(0, 28).addBox(0.0F, -1.0F, 0.0F, 10.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(10.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.9599F));
		PartDefinition legRearLeft3 = legRearLeft2.addOrReplaceChild(LEG_REAR_LEFT_3, CubeListBuilder.create()
			.texOffs(0, 30).addBox(0.0F, -1.0F, 0.0F, 10.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(10.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.9599F));
		PartDefinition legHindRight = trunk.addOrReplaceChild(LEG_HIND_RIGHT, CubeListBuilder.create()
			.texOffs(22, 8).addBox(-10.0F, -1.0F, 0.0F, 10.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(-1.0F, 0.0F, -1.0F, 0.0F, 0.6981F, 0.9599F));
		PartDefinition legHindRight2 = legHindRight.addOrReplaceChild(LEG_HIND_RIGHT_2, CubeListBuilder.create()
			.texOffs(0, 10).addBox(-10.0F, -1.0F, 0.0F, 10.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(-10.0F, 0.0F, 0.0F, 0.0F, 0.0F, -0.9599F));
		PartDefinition legHindRight3 = legHindRight2.addOrReplaceChild(LEG_HIND_RIGHT_3, CubeListBuilder.create()
			.texOffs(0, 12).addBox(-10.0F, -1.0F, 0.0F, 10.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(-10.0F, 0.0F, 0.0F, 0.0F, 0.0F, -0.9599F));
		PartDefinition legHindLeft = trunk.addOrReplaceChild(LEG_HIND_LEFT, CubeListBuilder.create()
			.texOffs(0, 6).addBox(0.0F, -1.0F, 0.0F, 10.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(1.0F, 0.0F, -1.0F, 0.0F, -0.6981F, -0.9599F));
		PartDefinition legHindLeft2 = legHindLeft.addOrReplaceChild(LEG_HIND_LEFT_2, CubeListBuilder.create()
			.texOffs(22, 6).addBox(0.0F, -1.0F, 0.0F, 10.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(10.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.9599F));
		PartDefinition legHindLeft3 = legHindLeft2.addOrReplaceChild(LEG_HIND_LEFT_3, CubeListBuilder.create()
			.texOffs(0, 8).addBox(0.0F, -1.0F, 0.0F, 10.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(10.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.9599F));
		return LayerDefinition.create(mesh, 64, 32);
	}
}
