package com.abyssia.client.entity.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Generated by tools/bbmodel-generator (stoplight_loosejaw.bbmodel, template fish, seed 1).
 * Texture 64x32 UV (64x32 px): textures/entity/stoplight_loosejaw.png, glow mask textures/entity/stoplight_loosejaw_glow.png.
 * Regenerate with: node tools/bbmodel-generator/cli.js stoplight_loosejaw
 */
public final class StoplightLoosejawGeometry
{
	public static final String STOPLIGHT_LOOSEJAW = "stoplight_loosejaw";
	public static final String BODY = "body";
	public static final String HEAD = "head";
	public static final String MOUTH = "mouth";
	public static final String UPPER_TEETH = "upper_teeth";
	public static final String LOWER_TEETH = "lower_teeth";
	public static final String RIGHT_EYE = "right_eye";
	public static final String LEFT_EYE = "left_eye";
	public static final String RIGHT_FIN = "right_fin";
	public static final String LEFT_FIN = "left_fin";
	public static final String RIGHT_PELVIC_FIN = "right_pelvic_fin";
	public static final String LEFT_PELVIC_FIN = "left_pelvic_fin";
	public static final String DORSAL_FIN = "dorsal_fin";
	public static final String ANAL_FIN = "anal_fin";
	public static final String TAIL = "tail";
	public static final String TAIL_2 = "tail_2";
	public static final String TAIL_FIN = "tail_fin";

	private StoplightLoosejawGeometry()
	{
	}

	public static LayerDefinition create()
	{
		MeshDefinition mesh = new MeshDefinition();
		PartDefinition root = mesh.getRoot();
		PartDefinition stoplightLoosejaw = root.addOrReplaceChild(STOPLIGHT_LOOSEJAW, CubeListBuilder.create(),
			PartPose.offset(0.0F, 24.0F, 0.0F));
		PartDefinition body = stoplightLoosejaw.addOrReplaceChild(BODY, CubeListBuilder.create()
			.texOffs(0, 0).addBox(-1.5F, -1.0F, -1.0F, 3.0F, 2.0F, 10.0F, new CubeDeformation(0.0F))
			.texOffs(42, 0).addBox(-0.5F, -2.0F, -1.0F, 1.0F, 1.0F, 9.0F, new CubeDeformation(0.0F))
			.texOffs(22, 21).addBox(-0.5F, 1.0F, -1.0F, 1.0F, 1.0F, 9.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -4.0F, -4.0F));
		PartDefinition head = body.addOrReplaceChild(HEAD, CubeListBuilder.create()
			.texOffs(0, 21).addBox(-2.0F, -2.0F, -7.0F, 4.0F, 3.0F, 7.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 0.0F));
		PartDefinition mouth = head.addOrReplaceChild(MOUTH, CubeListBuilder.create()
			.texOffs(0, 12).addBox(-2.0F, 0.0F, -7.0F, 4.0F, 1.0F, 8.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(0.0F, 1.0F, -1.0F, 0.2443F, 0.0F, 0.0F));
		PartDefinition lowerTeeth = mouth.addOrReplaceChild(LOWER_TEETH, CubeListBuilder.create()
			.texOffs(32, 3).addBox(-1.0F, -1.0F, 0.5F, 1.0F, 1.0F, 0.0F, new CubeDeformation(0.0F))
			.texOffs(38, 8).addBox(-0.5F, -1.0F, 2.0F, 0.0F, 1.0F, 1.0F, new CubeDeformation(0.0F))
			.texOffs(40, 8).addBox(0.5F, -1.0F, 2.0F, 0.0F, 1.0F, 1.0F, new CubeDeformation(0.0F))
			.texOffs(32, 0).addBox(-1.5F, -2.0F, -0.5F, 1.0F, 3.0F, 0.0F, new CubeDeformation(0.0F))
			.texOffs(26, 0).addBox(0.5F, -2.0F, -0.5F, 1.0F, 3.0F, 0.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, -7.0F));
		PartDefinition upperTeeth = head.addOrReplaceChild(UPPER_TEETH, CubeListBuilder.create()
			.texOffs(28, 0).addBox(-1.0F, 0.0F, 0.5F, 1.0F, 1.0F, 0.0F, new CubeDeformation(0.0F))
			.texOffs(40, 0).addBox(-0.5F, 0.0F, 2.0F, 0.0F, 1.0F, 1.0F, new CubeDeformation(0.0F))
			.texOffs(40, 1).addBox(0.5F, 0.0F, 2.0F, 0.0F, 1.0F, 1.0F, new CubeDeformation(0.0F))
			.texOffs(28, 0).addBox(-2.5F, -1.0F, 1.0F, 0.0F, 2.0F, 1.0F, new CubeDeformation(0.0F))
			.texOffs(30, 0).addBox(2.5F, -1.0F, 1.0F, 0.0F, 2.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 1.0F, -7.0F));
		PartDefinition rightEye = head.addOrReplaceChild(RIGHT_EYE, CubeListBuilder.create()
			.texOffs(34, 7).addBox(-0.5F, -0.5F, -0.5F, 1.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offset(-2.0F, -1.5F, -4.5F));
		PartDefinition leftEye = head.addOrReplaceChild(LEFT_EYE, CubeListBuilder.create()
			.texOffs(38, 7).addBox(-0.5F, -0.5F, -0.5F, 1.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)),
			PartPose.offset(2.0F, -1.5F, -4.5F));
		PartDefinition rightFin = body.addOrReplaceChild(RIGHT_FIN, CubeListBuilder.create()
			.texOffs(24, 17).addBox(0.0F, -0.5F, -1.0F, 0.0F, 1.0F, 3.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(-1.5F, 0.5F, 1.0F, 0.0F, -0.5236F, -0.3491F));
		PartDefinition leftFin = body.addOrReplaceChild(LEFT_FIN, CubeListBuilder.create()
			.texOffs(26, 0).addBox(0.0F, -0.5F, -1.0F, 0.0F, 1.0F, 3.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(1.5F, 0.5F, 1.0F, 0.0F, 0.5236F, 0.3491F));
		PartDefinition rightPelvicFin = body.addOrReplaceChild(RIGHT_PELVIC_FIN, CubeListBuilder.create()
			.texOffs(34, 2).addBox(0.0F, -1.0F, -1.0F, 0.0F, 2.0F, 3.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(-1.0F, 2.0F, 5.0F, 0.3491F, -0.3491F, 0.0F));
		PartDefinition leftPelvicFin = body.addOrReplaceChild(LEFT_PELVIC_FIN, CubeListBuilder.create()
			.texOffs(34, 0).addBox(0.0F, -1.0F, -1.0F, 0.0F, 2.0F, 3.0F, new CubeDeformation(0.0F)),
			PartPose.offsetAndRotation(1.0F, 2.0F, 5.0F, 0.3491F, 0.3491F, 0.0F));
		PartDefinition dorsalFin = body.addOrReplaceChild(DORSAL_FIN, CubeListBuilder.create()
			.texOffs(32, 6).addBox(0.0F, -2.0F, 0.0F, 0.0F, 3.0F, 3.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, -2.0F, 6.0F));
		PartDefinition analFin = body.addOrReplaceChild(ANAL_FIN, CubeListBuilder.create()
			.texOffs(26, 6).addBox(0.0F, -1.0F, 0.0F, 0.0F, 3.0F, 3.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 2.0F, 6.0F));
		PartDefinition tail = body.addOrReplaceChild(TAIL, CubeListBuilder.create()
			.texOffs(24, 12).addBox(-1.0F, -2.0F, 0.0F, 2.0F, 3.0F, 5.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 8.0F));
		PartDefinition tail2 = tail.addOrReplaceChild(TAIL_2, CubeListBuilder.create()
			.texOffs(38, 10).addBox(-0.5F, -1.0F, 0.0F, 1.0F, 2.0F, 3.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 4.0F));
		PartDefinition tailFin = tail2.addOrReplaceChild(TAIL_FIN, CubeListBuilder.create()
			.texOffs(26, 0).addBox(0.0F, -3.0F, -1.0F, 0.0F, 5.0F, 4.0F, new CubeDeformation(0.0F)),
			PartPose.offset(0.0F, 0.0F, 3.0F));
		return LayerDefinition.create(mesh, 64, 32);
	}
}
